"use client";
import {FormEvent,useEffect,useState} from "react";
type Memory={id:string;title:string;content:string;sourceType:string;sourceAccount:string;occurredAt:string;retentionUntil:string;tags:string[]};
const today=()=>new Date().toISOString().slice(0,10);
export default function MemoryAgentClient(){
 const [query,setQuery]=useState(""),[source,setSource]=useState("ALL"),[from,setFrom]=useState(new Date(Date.now()-3*365*86400000).toISOString().slice(0,10)),[to,setTo]=useState(today());
 const [answer,setAnswer]=useState("Ask about a person, decision, room, project, message, or event from the last three years."),[memories,setMemories]=useState<Memory[]>([]);
 const [title,setTitle]=useState(""),[content,setContent]=useState(""),[occurredAt,setOccurredAt]=useState(today()),[sourceAccount,setSourceAccount]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function recall(event?:FormEvent){event?.preventDefault();setBusy(true);const response=await fetch(`/api/v1/memory-agent?q=${encodeURIComponent(query)}&source=${source}&from=${from}&to=${to}`,{cache:"no-store"});const data=await response.json() as {answer?:string;memories?:Memory[];error?:string};setBusy(false);setAnswer(data.answer??data.error??"Recall failed.");setMemories(data.memories??[])}
 async function save(event:FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/v1/memory-agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,content,occurredAt:`${occurredAt}T12:00:00Z`,sourceType:source==="ALL"?"MANUAL":source,sourceAccount})});const data=await response.json() as {error?:string};setBusy(false);setNotice(response.ok?"Memory saved with three-year retention and source traceability.":data.error??"Memory could not be saved.");if(response.ok){setTitle("");setContent("");void recall()}}
 useEffect(()=>{void recall()},[]);
 return <main className="memory-agent"><header><a href="/">← AAI Q Home</a><p>Private, durable organizational recall</p><h1>AI Memory Agent</h1><span>Recall decisions and context across years while keeping every answer connected to its original source.</span></header>
  {notice&&<div className="memory-notice">{notice}</div>}<section className="memory-layout"><article className="memory-recall"><form onSubmit={recall}><label>What do you want to remember?<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What did we decide about the roof claim last summer?"/></label><div><label>Source<select value={source} onChange={e=>setSource(e.target.value)}><option>ALL</option><option>MANUAL</option><option>GMAIL</option><option>SMS</option><option>PHONE</option><option>VIDEO</option><option>TASK</option><option>REPORT</option></select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button disabled={busy}>{busy?"Recalling…":"Ask Memory"}</button></div></form><section className="memory-answer"><small>AI recall response</small><h2>{answer}</h2><span>{memories.length} cited record{memories.length===1?"":"s"} · private to your account</span></section><div className="memory-results">{memories.map(item=><article key={item.id}><time>{new Date(item.occurredAt).toLocaleDateString()}</time><div><strong>{item.title}</strong><p>{item.content}</p><span>{item.sourceType}{item.sourceAccount?` · ${item.sourceAccount}`:""} · retained through {new Date(item.retentionUntil).toLocaleDateString()}</span></div></article>)}</div></article>
   <aside className="memory-save"><h2>Teach the agent</h2><p>Save a decision, conversation outcome, instruction, or important context.</p><form onSubmit={save}><label>Memory title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>What should be remembered?<textarea required value={content} onChange={e=>setContent(e.target.value)}/></label><label>When did it happen?<input type="date" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label><label>Source or account<input value={sourceAccount} onChange={e=>setSourceAccount(e.target.value)} placeholder="mukeshmp@gmail.com or +1…"/></label><button disabled={busy}>Save to long-term memory</button></form><div><b>3-year searchable history</b><span>Owner-scoped · date indexed · source-separated · exact-record citations</span></div></aside></section></main>
}
