"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
type Module={key:string;name:string};type User={email:string;displayName:string;role:string;status:string;department:string;roleTier:string;mfaRequired:number;mfaStatus:string;recoveryEmail:string|null;recoveryPhone:string|null;accessStatus:string;lastAccessReviewAt:string|null;grants:string[]};
type Finding={severity:string;email:string;title:string;recommendation:string};type Audit={actorEmail:string;targetEmail:string;eventType:string;createdAt:string};
export default function UserManagementClient(){
 const [users,setUsers]=useState<User[]>([]),[modules,setModules]=useState<Module[]>([]),[findings,setFindings]=useState<Finding[]>([]),[audit,setAudit]=useState<Audit[]>([]),[role,setRole]=useState("staff");
 const [selected,setSelected]=useState<User|null>(null),[draft,setDraft]=useState<User|null>(null),[tab,setTab]=useState<"directory"|"access"|"security"|"advisor"|"audit">("directory"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const response=await fetch("/api/v1/access-management",{cache:"no-store"});const data=await response.json() as any;setUsers(data.users??[]);setModules(data.modules??[]);setFindings(data.findings??[]);setAudit(data.audit??[]);setRole(data.role??"staff")},[]);
 useEffect(()=>{void load()},[load]);function choose(user:User){setSelected(user);setDraft({...user,grants:[...user.grants]});setTab("access")}
 async function save(){if(!draft)return;setBusy(true);const response=await fetch("/api/v1/access-management",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...draft,modules:draft.grants})});const data=await response.json() as {error?:string};setBusy(false);setNotice(response.ok?"Access profile reviewed, enforced, and logged.":data.error??"Update failed.");if(response.ok){await load();setSelected(null);setDraft(null)}}
 async function recover(type:string,channel:string,user=selected??users[0]){if(!user)return;setBusy(true);const response=await fetch("/api/v1/access-management",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:user.email,recoveryType:type,channel})});const data=await response.json() as any;setBusy(false);setNotice(response.ok?`Verified ${channel.toLowerCase()} recovery queued to ${data.destination}. Passwords are never retrievable.`:data.error??"Recovery could not be started.")}
 const active=users.filter(u=>u.accessStatus==="ACTIVE").length,mfa=users.filter(u=>u.mfaStatus==="VERIFIED"||u.mfaStatus==="ENROLLED").length;
 const critical=findings.filter(f=>f.severity==="CRITICAL"||f.severity==="HIGH").length;
 const byDept=useMemo(()=>users.reduce((map,user)=>(map[user.department]=(map[user.department]||0)+1,map),{} as Record<string,number>),[users]);
 return <main className="uam"><header><div><a href="/">← AAIQ Home</a><p>HNE-compatible identity bridge</p><h1>AAIQ User & Access Management</h1><span>One place to assign users, departments, hierarchy, module access, MFA, recovery, and access reviews.</span></div><aside><b>Provider-secured sign-in</b><span>Passwords are reset—never retrieved</span></aside></header>{notice&&<div className="uam-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 <section className="uam-kpis"><article><strong>{users.length}</strong><span>Total identities</span></article><article><strong>{active}</strong><span>Active users</span></article><article><strong>{mfa}/{users.length}</strong><span>MFA coverage</span></article><article className={critical?"risk":""}><strong>{critical}</strong><span>High-risk findings</span></article></section>
 <nav>{[["directory","User directory"],["access","Tab & module access"],["security","MFA & recovery"],["advisor","AI access advisor"],["audit","Audit history"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id as typeof tab)}>{label}</button>)}</nav>
 {tab==="directory"&&<section className="uam-panel"><header><div><p>Identity registry</p><h2>Users and assignments</h2></div><span>{Object.entries(byDept).map(([name,count])=>`${name.replaceAll("_"," ")} ${count}`).join(" · ")}</span></header><div className="uam-table"><table><thead><tr><th>Employee</th><th>Department</th><th>Tier</th><th>MFA</th><th>Status</th><th>Access</th></tr></thead><tbody>{users.map(user=><tr key={user.email}><td><strong>{user.displayName}</strong><small>{user.email}</small></td><td>{user.department.replaceAll("_"," ")}</td><td>{user.roleTier}</td><td><span className={user.mfaStatus==="VERIFIED"?"good":"warn"}>{user.mfaStatus.replaceAll("_"," ")}</span></td><td>{user.accessStatus}</td><td><button onClick={()=>choose(user)}>Manage →</button></td></tr>)}</tbody></table></div></section>}
 {tab==="access"&&<section className="uam-access">{selected&&draft?<><article className="uam-panel profile-editor"><header><div><p>Selected identity</p><h2>{draft.displayName}</h2></div><button onClick={()=>{setSelected(null);setDraft(null)}}>Close</button></header><div className="identity-grid"><label>Department<select value={draft.department} onChange={e=>setDraft({...draft,department:e.target.value})}>{["FRONT_DESK","HOUSEKEEPING","MAINTENANCE","EXECUTIVE"].map(v=><option key={v}>{v}</option>)}</select></label><label>Role tier<select value={draft.roleTier} onChange={e=>setDraft({...draft,roleTier:e.target.value})}>{["ASSOCIATE","SUPERVISOR","MANAGER","CORPORATE"].map(v=><option key={v}>{v}</option>)}</select></label><label>Account state<select value={draft.accessStatus} onChange={e=>setDraft({...draft,accessStatus:e.target.value})}><option>ACTIVE</option><option>SUSPENDED</option></select></label><label className="toggle"><input type="checkbox" checked={Boolean(draft.mfaRequired)} onChange={e=>setDraft({...draft,mfaRequired:e.target.checked?1:0})}/>Require MFA</label></div></article><article className="uam-panel module-matrix"><header><div><p>Least-privilege assignment</p><h2>AAIQ module access</h2></div><span>{draft.grants.length} assigned</span></header><div>{modules.map(module=><label key={module.key}><input type="checkbox" checked={draft.grants.includes(module.key)} onChange={e=>setDraft({...draft,grants:e.target.checked?[...draft.grants,module.key]:draft.grants.filter(k=>k!==module.key)})}/><span><strong>{module.name}</strong><small>{module.key}</small></span></label>)}</div><button disabled={busy||role!=="admin"} onClick={()=>void save()}>{busy?"Saving…":"Save and enforce access"}</button></article></>:<div className="uam-panel uam-empty">Select “Manage” beside an employee in the User Directory.</div>}</section>}
 {tab==="security"&&<section className="uam-security"><article className="uam-panel"><header><div><p>Multi-factor authentication</p><h2>MFA security center</h2></div></header><div className="security-policy"><strong>Recommended enforcement</strong><p>Require MFA for every manager, corporate user, user administrator, report exporter, and anyone with recovery privileges.</p><b>{users.filter(u=>u.mfaRequired).length} users currently required</b></div>{users.map(user=><button key={user.email} onClick={()=>choose(user)}><span>{user.displayName}<small>{user.roleTier} · {user.department}</small></span><b>{user.mfaStatus.replaceAll("_"," ")}</b></button>)}</article><article className="uam-panel recovery-center"><header><div><p>Verified recovery only</p><h2>ID and credential recovery</h2></div></header><p>AAIQ can retrieve a user ID or start a credential reset after verified delivery. Existing passwords are never displayed or sent.</p><label>User<select value={selected?.email??users[0]?.email??""} onChange={e=>setSelected(users.find(u=>u.email===e.target.value)??null)}>{users.map(u=><option key={u.email} value={u.email}>{u.displayName} · {u.email}</option>)}</select></label><div><button disabled={busy} onClick={()=>void recover("RETRIEVE_ID","EMAIL")}>Email user ID</button><button disabled={busy} onClick={()=>void recover("RESET_CREDENTIAL","EMAIL")}>Email reset link</button><button disabled={busy} onClick={()=>void recover("RESET_CREDENTIAL","SMS")}>SMS reset link</button></div><small>Current authentication is managed by the connected identity provider. Recovery requests are audited and expire after 15 minutes.</small></article></section>}
 {tab==="advisor"&&<section className="uam-panel advisor"><header><div><p>Continuous least-privilege review</p><h2>AI access advisor</h2></div><span>{findings.length} recommendations</span></header>{findings.length?findings.map((finding,index)=><article key={`${finding.email}-${index}`} className={finding.severity.toLowerCase()}><b>{finding.severity}</b><div><strong>{finding.title}</strong><span>{finding.email}</span><p>{finding.recommendation}</p></div><button onClick={()=>{const user=users.find(u=>u.email===finding.email);if(user)choose(user)}}>Review user</button></article>):<div className="uam-empty">No access conflicts detected.</div>}</section>}
 {tab==="audit"&&<section className="uam-panel advisor"><header><div><p>Immutable governance trail</p><h2>Access and recovery audit</h2></div></header>{audit.map((item,index)=><article key={`${item.createdAt}-${index}`}><b>LOG</b><div><strong>{item.eventType.replaceAll("_"," ")}</strong><span>{item.actorEmail} → {item.targetEmail}</span><p>{new Date(item.createdAt).toLocaleString()}</p></div></article>)}</section>}</main>
}
