"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Program = Record<string, any> & { id:string; program_code:string; name:string; source_status:string; items:ProgramItem[] };
type Roster = { email:string; displayName:string; roleLabel:string; clockedIn:boolean; openLoad:number };
type Evidence = { evidence_type:string; file_name:string; review_status:string };
type ProgramItem = Record<string, any> & { id:string; item_code:string; instruction:string; response_type:string; required:number; critical:number };
type CaseRow = Record<string, any> & { id:string; state:string; target_label:string; program_name:string; items:ProgramItem[]; evidence:Evidence[]; responses:Record<string,any>[] };
type Center = { roleMode:"MANAGER"|"INSPECTOR"|"READ_ONLY"; property:Record<string,any>; programs:Program[]; cases:CaseRow[];
  roster:Roster[]; assets:Record<string,any>[]; exceptions:Record<string,any>[]; runs:Record<string,any>[]; policyVersion:string; limitations:Record<string,boolean> };

const OPEN = new Set(["UNASSIGNED","ASSIGNED","ACKNOWLEDGED","INSPECTING","FAILED_HOLD","REMEDIATION_REQUIRED","AWAITING_EVIDENCE","AWAITING_REVIEW","REWORK_REQUIRED"]);
const EVIDENCE_LABELS:Record<string,string>={OVERVIEW:"Overview",INSTRUMENT_READING:"Instrument reading",IDENTIFICATION_TAG:"Identification tag",CERTIFICATE:"Certificate / service record",DEFICIENCY:"Deficiency evidence"};

async function json(response:Response){const body=await response.json() as Record<string,any>;if(!response.ok)throw new Error(String(body.error||"Compliance request failed."));return body}
function format(value?:string){return value?new Date(value).toLocaleString():"Not recorded"}
function latestResponse(item:CaseRow,programItemId:string){return [...(item.responses||[])].find(row=>row.program_item_id===programItemId)}

export default function ComplianceInspectionClient({displayName}:{displayName:string}){
  const [data,setData]=useState<Center|null>(null),[busy,setBusy]=useState(""),[filter,setFilter]=useState("OPEN"),[tab,setTab]=useState<"QUEUE"|"PROGRAMS"|"RUNS">("QUEUE"),
    [message,setMessage]=useState<{kind:"success"|"error";text:string}|null>(null),[trace,setTrace]=useState<Record<string,any>|null>(null);
  const load=useCallback(async()=>{try{setData(await json(await fetch("/api/compliance/programs",{cache:"no-store"})) as Center)}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"Compliance Center could not load."})}},[]);
  useEffect(()=>{void load()},[load]);
  async function programAction(payload:Record<string,unknown>){setBusy(String(payload.action));setMessage(null);try{const result=await json(await fetch("/api/compliance/programs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}));setMessage({kind:"success",text:payload.action==="RUN_AUTOMATION"?`Automation checked approved programs, created ${result.casesCreated||0} due case(s), and opened ${result.exceptionsCreated||0} exception(s).`:"Compliance configuration saved with an audit record."});await load()}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"Compliance action failed."})}finally{setBusy("")}}
  async function caseAction(id:string,payload:Record<string,unknown>){setBusy(`${id}:${payload.action}`);setMessage(null);try{const result=await json(await fetch(`/api/compliance/cases/${id}/action`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}));setMessage({kind:"success",text:result.missingEvidence?`Inspection saved. Next: add ${result.missingEvidence.join(", ")}.`:"Compliance case advanced with property-scoped evidence and audit history."});await load()}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"Compliance action failed."})}finally{setBusy("")}}
  async function evidence(item:CaseRow,evidenceType:string,file?:File,programItemId?:string){if(!file)return;setBusy(`${item.id}:evidence`);setMessage(null);try{const form=new FormData();form.set("file",file);form.set("evidenceType",evidenceType);if(programItemId)form.set("programItemId",programItemId);await json(await fetch(`/api/compliance/cases/${item.id}/evidence`,{method:"POST",body:form}));setMessage({kind:"success",text:`${EVIDENCE_LABELS[evidenceType]||evidenceType} stored privately. Upload integrity is proven; visual/technical approval remains human-gated.`});await load()}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"Evidence upload failed."})}finally{setBusy("")}}
  async function openTrace(id:string){setBusy(`${id}:trace`);try{setTrace(await json(await fetch(`/api/compliance/cases/${id}/trace`,{cache:"no-store"})))}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"Trace could not load."})}finally{setBusy("")}}
  const filtered=useMemo(()=>(data?.cases||[]).filter(row=>filter==="ALL"||filter==="OPEN"&&OPEN.has(row.state)||filter==="DUE"&&OPEN.has(row.state)&&new Date(row.due_at)<=new Date()||filter==="HOLD"&&["FAILED_HOLD","REMEDIATION_REQUIRED","REWORK_REQUIRED"].includes(row.state)||filter==="REVIEW"&&row.state==="AWAITING_REVIEW"||filter==="CLOSED"&&["COMPLIANT","WAIVED","CANCELLED"].includes(row.state)),[data,filter]);
  if(!data)return <main className="cp-shell"><div className="cp-loading"><b>Loading governed Compliance records…</b><p>Checking the active property, rule sources, exact assets, assignments, evidence, remediation, and review history.</p></div></main>;
  const counts={OPEN:data.cases.filter(row=>OPEN.has(row.state)).length,DUE:data.cases.filter(row=>OPEN.has(row.state)&&new Date(row.due_at)<=new Date()).length,HOLD:data.cases.filter(row=>["FAILED_HOLD","REMEDIATION_REQUIRED","REWORK_REQUIRED"].includes(row.state)).length,REVIEW:data.cases.filter(row=>row.state==="AWAITING_REVIEW").length,CLOSED:data.cases.filter(row=>["COMPLIANT","WAIVED","CANCELLED"].includes(row.state)).length,ALL:data.cases.length};
  const approved=data.programs.filter(row=>row.source_status==="APPROVED").length;
  return <main className="cp-shell">
    <section className="cp-hero"><div><small>AAIQ DIGITAL COMPLIANCE · RULE-TO-REVIEWED-CLOSURE</small><h1>Know what is due. Prove what happened.</h1><p>AAIQ schedules only property-approved programs, targets registered assets, assigns eligible inspectors, contains failed checks, creates linked repairs, and preserves a drill-down trace. It never invents a code requirement or claims a physical inspection occurred.</p></div><aside><small>ACTIVE PROPERTY</small><b>{data.property.name}</b><span>{data.roleMode.toLowerCase()} workspace · {displayName}</span><small>{data.policyVersion}</small></aside></section>
    <section className="cp-boundary"><b>AUTONOMOUS</b><span>Due detection, exact target selection, eligible assignment, reminders, exceptions, linked remediation, reporting</span><b>HUMAN-GATED</b><span>Physical inspection, source approval, measurements, life-safety clearance, licensed sign-off, waivers</span></section>
    <section className="cp-controls"><div><small>LIVE CONTROL</small><h2>Compliance operations</h2><p>{approved}/{data.programs.length} programs have approved sources · {data.roster.length} eligible inspector(s)</p></div>{data.roleMode==="MANAGER"&&<><button onClick={()=>programAction({action:"PREPARE_BASELINE"})} disabled={!!busy}>Prepare governed baseline</button><button className="secondary" onClick={()=>programAction({action:"RUN_AUTOMATION"})} disabled={!!busy}>Run due-work automation</button></>}</section>
    {message&&<div className={`cp-message ${message.kind}`}>{message.text}<button onClick={()=>setMessage(null)}>×</button></div>}
    {data.exceptions.some(row=>row.status==="OPEN")&&<section className="cp-exception-summary"><b>{data.exceptions.filter(row=>row.status==="OPEN").length} governed exception(s) require attention</b><span>AAIQ has stopped the affected automation and preserved the reason. Open the matching program or case below to resolve the factual blocker.</span></section>}
    <nav className="cp-tabs"><button className={tab==="QUEUE"?"active":""} onClick={()=>setTab("QUEUE")}>Inspection queue</button><button className={tab==="PROGRAMS"?"active":""} onClick={()=>setTab("PROGRAMS")}>Programs & sources</button><button className={tab==="RUNS"?"active":""} onClick={()=>setTab("RUNS")}>Automation proof</button></nav>
    {tab==="QUEUE"&&<><section className="cp-kpis">{Object.entries(counts).map(([key,value])=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}><strong>{value}</strong><span>{key}</span></button>)}</section><section className="cp-queue">{filtered.length?filtered.map(item=><ComplianceCase key={item.id} item={item} data={data} busy={busy} act={caseAction} upload={evidence} trace={openTrace}/>):<div className="cp-empty"><h2>No source-backed cases in this view</h2><p>{data.programs.length?"Run due-work automation after approving program sources and registering the exact assets.":"Prepare the governed baseline first. This creates definitions only—not fake completed work."}</p></div>}</section></>}
    {tab==="PROGRAMS"&&<section className="cp-programs">{data.programs.length?data.programs.map(program=><ProgramCard key={program.id} program={program} canManage={data.roleMode==="MANAGER"} busy={busy} save={programAction}/>):<div className="cp-empty"><h2>No Compliance programs are configured</h2><p>A manager can prepare the standard hotel baseline. Every program remains configuration-required until its real property source is approved.</p></div>}</section>}
    {tab==="RUNS"&&<section className="cp-runs"><header><h2>Automation execution proof</h2><p>These are actual idempotent runs—not a percentage or decorative readiness status.</p></header>{data.runs.length?data.runs.map(run=><article key={run.id}><b>{run.run_key}</b><span>{format(run.completed_at)}</span><strong>{run.cases_created} case(s)</strong><small>{run.exceptions_created} exception(s) · {run.programs_prepared} definitions evaluated</small></article>):<div className="cp-empty"><p>No automation run has been recorded yet.</p></div>}</section>}
    {trace&&<TraceModal trace={trace} close={()=>setTrace(null)}/>} 
  </main>;
}

function ProgramCard({program,canManage,busy,save}:{program:Program;canManage:boolean;busy:string;save:(payload:Record<string,unknown>)=>Promise<void>}){
  const numericItems=(program.items||[]).filter(item=>item.response_type==="NUMBER");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),itemRanges=Object.fromEntries(numericItems.map(item=>[item.id,{minimum:form.get(`minimum:${item.id}`),maximum:form.get(`maximum:${item.id}`)}]));
    await save({action:"CONFIGURE_PROGRAM",programId:program.id,sourceTitle:form.get("sourceTitle"),jurisdiction:form.get("jurisdiction"),sourceReference:form.get("sourceReference"),effectiveDate:form.get("effectiveDate"),itemRanges})}
  const sourceIsUrl=/^https?:\/\//i.test(String(program.source_reference||""));
  return <article className={`cp-program source-${program.source_status.toLowerCase()}`}><header><div><small>{program.program_code} · {program.frequency}</small><h2>{program.name}</h2><p>{program.description}</p></div><b>{program.source_status.replaceAll("_"," ")}</b></header><dl><div><dt>Target</dt><dd>{String(program.target_kind).replaceAll("_"," ")}</dd></div><div><dt>Evidence</dt><dd>{(JSON.parse(program.required_evidence_json||"[]") as string[]).map(x=>EVIDENCE_LABELS[x]||x).join(", ")}</dd></div><div><dt>Next due</dt><dd>{format(program.next_due_at)}</dd></div><div><dt>Human sign-off</dt><dd>{program.licensed_signoff_required?"Qualified/licensed person required":"Independent property reviewer"}</dd></div></dl>
    {program.source_status==="APPROVED"?<section className="cp-source"><b>{program.source_title}</b><span>{program.jurisdiction} · effective {program.effective_date}</span>{sourceIsUrl?<a href={program.source_reference} target="_blank" rel="noreferrer">Open approved source ↗</a>:<span>Controlled reference: {program.source_reference}</span>}{numericItems.length>0&&<div className="cp-approved-ranges">{numericItems.map(item=><small key={item.id}><b>{item.item_code}</b>: {item.minimum_value??"no minimum"} to {item.maximum_value??"no maximum"} {item.measurement_unit||""}</small>)}</div>}</section>:canManage?<form className="cp-source-form" onSubmit={submit}><h3>Approve the real property rule source</h3><p>This is the only configuration step AAIQ cannot truthfully invent. Critical numeric checks also require the source-approved acceptable range.</p><div><label>Source / SOP title<input name="sourceTitle" required/></label><label>Jurisdiction / authority<input name="jurisdiction" required/></label><label>Source URL or controlled reference<input name="sourceReference" required/></label><label>Effective date<input type="date" name="effectiveDate" required/></label></div>{numericItems.length>0&&<fieldset className="cp-ranges"><legend>Approved measurement ranges</legend>{numericItems.map(item=><div key={item.id}><b>{item.item_code}{item.critical?" · required":" · optional"}</b><span>{item.measurement_unit||"configured unit"}</span><label>Minimum<input type="number" step="any" name={`minimum:${item.id}`} required={item.critical===1}/></label><label>Maximum<input type="number" step="any" name={`maximum:${item.id}`} required={item.critical===1}/></label></div>)}</fieldset>}<button disabled={!!busy}>Approve source & unlock scheduling</button></form>:<p className="cp-wait">A manager must approve the governing source before AAIQ creates due cases.</p>}</article>;
}

function ComplianceCase({item,data,busy,act,upload,trace}:{item:CaseRow;data:Center;busy:string;act:(id:string,payload:Record<string,unknown>)=>Promise<void>;upload:(item:CaseRow,type:string,file?:File,itemId?:string)=>Promise<void>;trace:(id:string)=>Promise<void>}){
  const required=JSON.parse(item.required_evidence_json||"[]") as string[],present=new Set((item.evidence||[]).map(row=>row.evidence_type));
  return <article className={`cp-case state-${item.state.toLowerCase()}`}><header><div><small>{item.program_code} · {item.state.replaceAll("_"," ")}</small><h2>{item.program_name}</h2><p>{item.target_label}</p></div><span>{new Date(item.due_at)<=new Date()?"DUE / OVERDUE":`Due ${format(item.due_at)}`}</span></header>
    <section className="cp-proof"><div><small>GOVERNING SOURCE</small><b>{item.source_title||"Configuration required"}</b><span>{item.jurisdiction||"No jurisdiction approved"}</span></div><div><small>ASSIGNED INSPECTOR</small><b>{item.assigned_to_email||"Unassigned"}</b><span>{item.assignment_reason}</span></div></section>
    {data.roleMode==="MANAGER"&&<form className="cp-reassign" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(item.id,{action:"REASSIGN",assignedToEmail:form.get("assignedToEmail")})}}><select name="assignedToEmail" defaultValue={item.assigned_to_email||""}><option value="">Choose eligible property inspector</option>{data.roster.map(person=><option key={person.email} value={person.email}>{person.displayName} · {person.clockedIn?"clocked in":"not clocked in"} · {person.openLoad} open</option>)}</select><button disabled={busy.startsWith(item.id)}>Assign</button></form>}
    {["FAILED_HOLD","REMEDIATION_REQUIRED"].includes(item.state)&&<section className="cp-hold"><b>{item.state==="FAILED_HOLD"?"CRITICAL HOLD — NO WAIVER":"REMEDIATION REQUIRED"}</b><span>A linked Maintenance case must be independently returned to service before this inspection can be repeated.</span><a href="/maintenance">Open linked Maintenance workflow →</a></section>}
    {["INSPECTING","AWAITING_EVIDENCE"].includes(item.state)&&<Checklist item={item} busy={busy} act={act}/>} 
    {!["COMPLIANT","WAIVED","CANCELLED"].includes(item.state)&&<EvidencePanel item={item} required={required} present={present} busy={busy} upload={upload}/>} 
    {item.state==="AWAITING_REVIEW"&&<ReviewPanel item={item} manager={data.roleMode==="MANAGER"} act={act}/>} 
    {["FAILED_HOLD","REMEDIATION_REQUIRED"].includes(item.state)&&data.roleMode==="MANAGER"&&<RemediationPanel item={item} act={act}/>} 
    <footer><div>{item.state==="ASSIGNED"&&<button onClick={()=>act(item.id,{action:"ACKNOWLEDGE"})}>Acknowledge assignment</button>}{item.state==="ACKNOWLEDGED"&&<button onClick={()=>act(item.id,{action:"START_INSPECTION"})}>Start physical inspection</button>}{["INSPECTING","AWAITING_EVIDENCE"].includes(item.state)&&<button onClick={()=>act(item.id,{action:"SUBMIT_REVIEW"})}>Validate & submit for review</button>}{item.state==="REWORK_REQUIRED"&&<button onClick={()=>act(item.id,{action:"START_REWORK"})}>Start governed reinspection</button>}</div><button className="trace" onClick={()=>trace(item.id)} disabled={busy.startsWith(item.id)}>Open full trace</button></footer>
  </article>;
}

function Checklist({item,busy,act}:{item:CaseRow;busy:string;act:(id:string,payload:Record<string,unknown>)=>Promise<void>}){
  return <section className="cp-checklist"><header><div><small>MEASURED HUMAN INSPECTION</small><b>{item.items.filter(row=>latestResponse(item,row.id)).length}/{item.items.length} current responses</b></div><span>AAIQ validates; a person observes</span></header>{item.items.map(programItem=><ResponseRow key={programItem.id} parent={item} item={programItem} previous={latestResponse(item,programItem.id)} busy={busy} act={act}/>)}</section>;
}
function ResponseRow({parent,item,previous,busy,act}:{parent:CaseRow;item:ProgramItem;previous?:Record<string,any>;busy:string;act:(id:string,payload:Record<string,unknown>)=>Promise<void>}){
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(parent.id,{action:"RECORD_RESPONSE",programItemId:item.id,...Object.fromEntries(form.entries())})}
  return <form className={previous?`answered result-${String(previous.result).toLowerCase()}`:""} onSubmit={submit}><div><b>{item.item_code}{item.critical?" · CRITICAL":""}</b><p>{item.instruction}</p>{previous&&<small>Latest: {previous.result}{previous.value_text?` · ${previous.value_text} ${previous.measurement_unit||""}`:""}</small>}</div><label>Result<select name="result" defaultValue={previous?.result||"PASS"}><option>PASS</option><option>FAIL</option><option value="NOT_APPLICABLE">NOT APPLICABLE</option></select></label>{item.response_type==="NUMBER"&&<label>Measurement<input type="number" step="any" name="numberValue" defaultValue={previous?.value_text||""} required/></label>}{item.response_type==="DATE"&&<label>Date<input type="date" name="dateValue" defaultValue={previous?.value_text||""} required/></label>}{item.response_type==="TEXT"&&<label>Observed value<input name="textValue" defaultValue={previous?.value_text||""} required/></label>}<label className="note">Factual note<textarea name="note" defaultValue={previous?.note||""} placeholder="Required for Fail or Not applicable"/></label><button disabled={busy.startsWith(parent.id)}>Save measured result</button></form>;
}

function EvidencePanel({item,required,present,busy,upload}:{item:CaseRow;required:string[];present:Set<string>;busy:string;upload:(item:CaseRow,type:string,file?:File,itemId?:string)=>Promise<void>}){
  return <section className="cp-evidence"><header><div><small>PRIVATE EVIDENCE GATE</small><b>{required.filter(type=>present.has(type)).length}/{required.length} required evidence types</b></div><span>Integrity checked · technical review pending</span></header><div>{required.map(type=><label key={type} className={present.has(type)?"present":"missing"}><b>{present.has(type)?"✓ ":"+ "}{EVIDENCE_LABELS[type]||type}</b><small>{present.has(type)?"Stored privately":"Required before review"}</small><input type="file" accept="image/*,application/pdf" disabled={busy.startsWith(item.id)} onChange={event=>void upload(item,type,event.target.files?.[0])}/></label>)}</div></section>;
}

function RemediationPanel({item,act}:{item:CaseRow;act:(id:string,payload:Record<string,unknown>)=>Promise<void>}){
  return <div className="cp-remediation"><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(item.id,{action:"RESUME_AFTER_REMEDIATION",note:form.get("note")})}}><h3>After Maintenance independently closes the repair</h3><label>Verification note<textarea name="note" required/></label><button>Verify repair state & require reinspection</button></form>{item.state==="REMEDIATION_REQUIRED"&&<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(item.id,{action:"WAIVE",note:form.get("note"),waiverExpiresAt:form.get("waiverExpiresAt")})}}><h3>Time-limited management waiver</h3><p>Non-critical deficiency only. A waiver closes the case but remains visible and expires.</p><label>Management reason<textarea name="note" required/></label><label>Expiration<input type="date" name="waiverExpiresAt" required/></label><button className="waiver">Approve audited waiver</button></form>}</div>;
}

function ReviewPanel({item,manager,act}:{item:CaseRow;manager:boolean;act:(id:string,payload:Record<string,unknown>)=>Promise<void>}){
  if(!manager)return <section className="cp-review"><h3>Independent review is waiting</h3><p>A property manager who did not record inspection results must make the decision.</p></section>;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const keys=["sourceVerified","targetVerified","responsesVerified","evidenceVerified","exceptionsResolved"];await act(item.id,{action:"REVIEW",decision:form.get("decision"),note:form.get("note"),qualifiedPerson:form.get("qualifiedPerson"),credentialReference:form.get("credentialReference"),checklist:Object.fromEntries(keys.map(key=>[key,form.get(key)==="on"]))})}
  return <form className="cp-review" onSubmit={submit}><h3>Independent closure decision</h3><p>The reviewer attests that the rule source, exact asset, measured records, evidence, and exceptions were independently checked.</p><div className="checks">{[["sourceVerified","Approved source"],["targetVerified","Exact target"],["responsesVerified","Recorded results"],["evidenceVerified","Private evidence"],["exceptionsResolved","Exceptions resolved"]].map(([key,label])=><label key={key}><input type="checkbox" name={key} required/> {label}</label>)}</div><div className="form-grid"><label>Decision<select name="decision"><option value="COMPLIANT">Compliant</option><option value="REWORK_REQUIRED">Rework required</option><option value="FAILED_HOLD">Failed hold</option></select></label>{item.licensed_signoff_required===1&&<><label>Qualified person<input name="qualifiedPerson" required/></label><label>Credential / certificate reference<input name="credentialReference" required/></label></>}</div><label>Independent reviewer note<textarea name="note" required/></label><button>Save independent decision</button></form>;
}

function TraceModal({trace,close}:{trace:Record<string,any>;close:()=>void}){
  const rows=[...(trace.events||[]).map((row:any)=>({at:row.created_at,title:row.event_type,detail:row.detail_json})),...(trace.responses||[]).map((row:any)=>({at:row.created_at,title:`${row.item_code} · ${row.result}`,detail:`${row.value_text||""} ${row.measurement_unit||""} ${row.note||""}`})),...(trace.reviews||[]).map((row:any)=>({at:row.created_at,title:`Independent review · ${row.decision}`,detail:row.reviewer_note}))].sort((a,b)=>String(a.at).localeCompare(String(b.at)));
  return <div className="cp-modal"><section><button className="close" onClick={close}>×</button><small>IMMUTABLE COMPLIANCE TRACE</small><h2>{trace.case?.program_name} · {trace.case?.target_label}</h2><p>Approved rule → exact asset → due instance → assignment → measured response → remediation → evidence → independent decision.</p><ol>{rows.map((row,index)=><li key={`${row.at}-${index}`}><span>{format(row.at)}</span><div><b>{row.title}</b><p>{row.detail}</p></div></li>)}</ol></section></div>;
}
