-- AAIQ-owned video intelligence foundation. No HNE schema or repository dependency.
CREATE TABLE IF NOT EXISTS video_audits(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,correlation_id TEXT NOT NULL,audit_type TEXT NOT NULL,zone_type TEXT NOT NULL,location_label TEXT NOT NULL,status TEXT NOT NULL,source_type TEXT NOT NULL,object_key TEXT,file_name TEXT,content_type TEXT,size_bytes INTEGER,privacy_status TEXT NOT NULL,analysis_mode TEXT NOT NULL,model_version TEXT,confidence REAL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,completed_at TEXT);
CREATE TABLE IF NOT EXISTS video_findings(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,audit_id TEXT NOT NULL,category TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,severity TEXT NOT NULL,provisional INTEGER NOT NULL DEFAULT 1,confidence REAL NOT NULL,evidence_timestamp_ms INTEGER,status TEXT NOT NULL,human_decision TEXT,human_note TEXT,reviewed_by TEXT,reviewed_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS video_camera_registry(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,name TEXT NOT NULL,zone_type TEXT NOT NULL,location_label TEXT NOT NULL,edge_node_name TEXT,status TEXT NOT NULL,stream_vault_reference TEXT NOT NULL,retention_days INTEGER NOT NULL,privacy_masking INTEGER NOT NULL,audio_disabled INTEGER NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS video_model_registry(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,capability TEXT NOT NULL,provider TEXT NOT NULL,model_name TEXT NOT NULL,version TEXT NOT NULL,status TEXT NOT NULL,risk_class TEXT NOT NULL,evaluation_status TEXT NOT NULL,approved_by TEXT,approved_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS express_checkin_sessions(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,correlation_id TEXT NOT NULL,reservation_reference TEXT NOT NULL,guest_display_name TEXT NOT NULL,status TEXT NOT NULL,consent_status TEXT NOT NULL,identity_method TEXT NOT NULL,payment_status TEXT NOT NULL,restriction_status TEXT NOT NULL,room_readiness_status TEXT NOT NULL,pms_status TEXT NOT NULL,key_status TEXT NOT NULL,manual_reason TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS video_provider_adapters(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,adapter_type TEXT NOT NULL,display_name TEXT NOT NULL,vault_reference TEXT,status TEXT NOT NULL,capabilities_json TEXT NOT NULL,external_system TEXT,external_entity_id TEXT,external_sync_status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS video_audits_scope_idx ON video_audits(organization_id,property_id,created_at);
CREATE INDEX IF NOT EXISTS video_findings_review_idx ON video_findings(organization_id,property_id,status,created_at);
CREATE INDEX IF NOT EXISTS express_checkin_scope_idx ON express_checkin_sessions(organization_id,property_id,created_at);
