"use client";
import{useEffect,useMemo,useState}from"react";
import"./digital-employee-command-center.css";

const STAGES=["PERCEIVE","REASON","ACT","VERIFY","REPORT"];
const LABELS:Record<string,string>={PERCEIVE:"Collect current information",REASON:"Apply policy and decide",ACT:"Execute authorized action",VERIFY:"Confirm the intended effect",REPORT:"Document, report and learn"};
function words(value:unknown){return String(value||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,x=>x.toUpperCase())}
function stateLabel(state:string){return words(state)}
function actionLabel(item:any){if(item.shiftState==="OFF_SHIFT")return"Start Shift";if(item.shiftState==="IDLE")return"Assign Duties";if(["BLOCKED","AWAITING_APPROVAL"].includes(item.shiftState))return"Review";if(item.shiftState==="HANDED_TO_HUMAN")return"View Handoff";return"View Live"}

export default function DigitalEmployeeCommandCenter({center,busy,onAction}:{center:any;busy:boolean;onAction:(body:Record<string,unknown>)=>Promise<void>}){
 const roster=center?.roster||[];const [selectedRole,setSelectedRole]=useState("");const [intervention,setIntervention]=useState("PAUSE");const [reason,setReason]=useState("");const [redirect,setRedirect]=useState("");const [targetType,setTargetType]=useState("OPERATIONS_QUEUE");const [targetId,setTargetId]=useState("General Operations Queue");
 useEffect(()=>{if(!selectedRole&&roster.length)setSelectedRole(roster[0].role_key)},[roster,selectedRole]);
 const selected=roster.find((x:any)=>x.role_key===selectedRole)||roster[0];const work=selected?.currentWork||center?.controls?.find((x:any)=>x.role_key===selected?.role_key&&!["COMPLETED","FAILED"].includes(x.state));const events=useMemo(()=>center?.events?.filter((x:any)=>x.work_queue_id===work?.work_queue_id)||[],[center?.events,work?.work_queue_id]);const latest=events[0];const roleTasks=center?.tasks?.filter((x:any)=>x.role_key===selected?.role_key)||[];const confidence=center?.confidence?.filter((x:any)=>x.role_key===selected?.role_key)||[];const proposals=center?.proposals?.filter((x:any)=>x.role_key===selected?.role_key)||[];const corrections=center?.corrections?.filter((x:any)=>x.role_key===selected?.role_key)||[];
 async function primary(item:any){setSelectedRole(item.role_key);if(item.shiftState==="OFF_SHIFT"||item.shiftState==="IDLE")await onAction({action:item.shiftState==="OFF_SHIFT"?"START_DIGITAL_EMPLOYEE_SHIFT":"ASSIGN_DIGITAL_EMPLOYEE_DUTIES",roleKey:item.role_key});else document.querySelector(".de-live-meter")?.scrollIntoView({behavior:"smooth",block:"start"});}
 async function applyIntervention(){if(!work)return;await onAction({action:"INTERVENE_DIGITAL_EMPLOYEE",workQueueId:work.work_queue_id,interventionType:intervention,reason,redirect,targetType,targetId});setReason("");setRedirect("");}
 const stageIndex=Math.max(0,STAGES.indexOf(work?.lifecycle_stage||"PERCEIVE"));
 return <section className="de-command-center" aria-label="Digital Employee Command Center">
  <header className="de-command-header"><div><h2>Digital Employee Command Center</h2><p>One canonical Operations queue · live reasoning · safe human control · continuous governed learning</p></div><dl><div><dt>Shift health</dt><dd>{roster.filter((x:any)=>x.shiftState!=="OFF_SHIFT").length} active</dd></div><div><dt>Awaiting approval</dt><dd>{roster.filter((x:any)=>x.shiftState==="AWAITING_APPROVAL").length}</dd></div><div><dt>Verified today</dt><dd>{center?.controls?.filter((x:any)=>x.state==="COMPLETED").length||0}</dd></div></dl></header>
  <div className="de-status-line"><span/>All visible state comes from persisted shift, canonical queue, policy and audit records. No separate task system is used.</div>
  <div className="de-command-layout">
   <aside className="de-roster"><header><div><strong>Digital Employees</strong><small>{roster.length} Role Parity assignments</small></div><span>Live</span></header><div>{roster.map((item:any,index:number)=><article key={item.role_key} className={selected?.role_key===item.role_key?"selected":""}>
    <button className="de-person" onClick={()=>setSelectedRole(item.role_key)}><i className={`de-avatar avatar-${index}`} aria-hidden="true"><span>{item.avatar}</span></i><span><b>{item.personaName}</b><small>{item.role_name}</small><em className={`state-${String(item.shiftState).toLowerCase()}`}>{stateLabel(item.shiftState)} · {item.shiftLabel}</em></span></button>
    <p>{item.currentWork?.task_name||"Ready for authorized duties"}</p><footer><span>{item.dutiesCompleted||0}/{item.dutiesTotal||0} duties</span><span>{item.confidence==null?"Not trained":`${Math.round(item.confidence*100)}% confidence`}</span></footer><button className="de-primary" disabled={busy} onClick={()=>void primary(item)}>{actionLabel(item)}</button>
   </article>)}</div></aside>
   <main className="de-live-meter">
    <header><div><h3>{selected?.personaName||"Select an employee"} <span>· {selected?.role_name}</span></h3><p>{selected?`${stateLabel(selected.shiftState)} · ${selected.shiftLabel}`:"No roster assignment selected"}</p></div>{work&&<button disabled={busy||work.state!=="WORKING"} onClick={()=>void onAction({action:"ADVANCE_DIGITAL_EMPLOYEE_STEP",workQueueId:work.work_queue_id})}>{work.lifecycle_stage==="REPORT"?"Verify & complete":"Continue safe step"}</button>}</header>
    {work?<><nav className="de-stages" aria-label="Execution lifecycle">{STAGES.map((stage,index)=><div key={stage} className={index<stageIndex?"done":index===stageIndex?"active":""}><b>{index+1}</b><strong>{words(stage)}</strong><small>{LABELS[stage]}</small></div>)}</nav>
     <section className="de-current-step"><small>Current step</small><h4>{work.current_step_text}</h4><p>{work.reason_text}</p><div className="de-progress"><span><b>Task progress</b><em>Step {work.step_number} of {work.step_total}</em><i><u style={{width:`${Math.min(100,Number(work.step_number)/Number(work.step_total)*100)}%`}}/></i></span><span><b>Queue progress</b><em>{selected.dutiesCompleted} of {selected.dutiesTotal} duties</em><i><u style={{width:`${Math.min(100,Number(selected.dutiesCompleted)/Math.max(1,Number(selected.dutiesTotal))*100)}%`}}/></i></span></div></section>
     <div className="de-reason-boundary"><section><small>Reasoning from the real policy step</small><p>{latest?.reason_text||work.reason_text}</p>{work.policy_reference&&<a href="/aaiq-document-vault">Policy: {work.policy_reference}</a>}</section><aside className={work.boundary_text?"visible":""}><strong>{work.boundary_text?"Advance boundary alert":"Boundary check passed"}</strong><p>{work.boundary_text||"No policy, confidence, physical or legally reserved boundary blocks the next safe step."}</p>{work.approval_case_id&&<a href="#approvals">Open specific approval</a>}</aside></div>
     <section className="de-sources"><small>Data sources touched this step</small><div>{(latest?.dataSources||[]).map((source:any,index:number)=><a key={index} href={source.href||"#"}><b>{source.label}</b><span>{source.type}</span></a>)}{!latest?.dataSources?.length&&<span>No source event recorded yet.</span>}</div></section>
     <section className="de-controls"><button disabled={busy||work.state==="PAUSED"} onClick={()=>void onAction({action:"INTERVENE_DIGITAL_EMPLOYEE",workQueueId:work.work_queue_id,interventionType:"PAUSE",reason:"Paused by a human at the current safe checkpoint."})}>Ⅱ Pause</button><button disabled={busy} onClick={()=>{setIntervention("TAKE_OVER");setReason("Human requested takeover with complete context.")}}>♙ Take Over</button><button disabled={busy} onClick={()=>setIntervention("EDIT_REDIRECT")}>✎ Edit / Redirect</button><button disabled={busy} onClick={()=>setIntervention("REASSIGN")}>⇄ Reassign</button>{work.state==="PAUSED"&&<button disabled={busy} onClick={()=>void onAction({action:"INTERVENE_DIGITAL_EMPLOYEE",workQueueId:work.work_queue_id,interventionType:"RESUME",reason:"Resume from preserved safe checkpoint."})}>▶ Resume</button>}</section>
     {!["PAUSE","RESUME"].includes(intervention)&&<section className="de-intervention-editor"><header><strong>{words(intervention)}</strong><small>Full state is transferred automatically; external effects retain the same idempotency key.</small></header><label>Reason (optional)<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why are you intervening?"/></label>{intervention==="EDIT_REDIRECT"&&<label>New instruction<textarea value={redirect} onChange={e=>setRedirect(e.target.value)} placeholder="Change a parameter or decision; downstream steps will respect it."/></label>}{intervention==="REASSIGN"&&<><label>Target<select value={targetType} onChange={e=>setTargetType(e.target.value)}><option value="OPERATIONS_QUEUE">General Operations queue</option><option value="HUMAN">Specific physical employee</option><option value="DIGITAL_EMPLOYEE">Different Digital Employee</option></select></label><label>Assignee<input value={targetId} onChange={e=>setTargetId(e.target.value)}/></label></>}<button disabled={busy} onClick={()=>void applyIntervention()}>Confirm {words(intervention)}</button></section>}
    </>:<div className="de-empty"><strong>{selected?.shiftState==="OFF_SHIFT"?"Off shift":"No active duty"}</strong><p>Start the shift to pull the first authorized Role Parity duty from the canonical Operations queue immediately.</p><button disabled={busy||!selected} onClick={()=>selected&&void primary(selected)}>Start Shift</button></div>}
   </main>
   <aside className="de-queue"><header><div><strong>Shift Queue</strong><small>{selected?.personaName}&apos;s duties</small></div><span>{selected?.dutiesCompleted||0} of {selected?.dutiesTotal||roleTasks.length}</span></header>{roleTasks.map((task:any,index:number)=>{const current=work?.task_key===task.task_key;return <article key={task.id} className={current?"active":""}><b>{index+1}</b><div><strong>{task.task_name}</strong><small>{task.category}</small></div><em>{current?stateLabel(work.state):index<(selected?.dutiesCompleted||0)?"Completed":"Queued"}</em></article>})}{!roleTasks.length&&<p>No Role Parity duty is configured.</p>}</aside>
  </div>
  <div className="de-learning-grid"><section className="de-timeline"><header><strong>Audited execution timeline</strong><span>{events.length} events</span></header>{events.slice(0,6).map((event:any)=><article key={event.id}><i/><time>{new Date(event.occurred_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</time><div><b>{event.plain_language_step}</b><small>{event.lifecycle_stage} · {event.actor_type.replaceAll("_"," ")}</small></div></article>)}{!events.length&&<p>No execution event yet.</p>}</section>
   <section><header><strong>Correction / learning signals</strong><span>{corrections.length}</span></header>{corrections.slice(0,3).map((item:any)=><article key={item.id}><b>{words(item.signal_type)}</b><p>{item.signal_summary}</p><small>{item.status} · behavior never changes without approval</small></article>)}{!corrections.length&&<p>No correction pattern needs review.</p>}</section>
   <section><header><strong>Task confidence</strong><span>Outcome derived</span></header>{confidence.slice(0,5).map((item:any)=><article key={item.id}><div><b>{words(item.task_key)}</b><small>{item.auto_escalate?"Auto-escalates below threshold":"Eligible within policy"}</small></div><em>{Math.round(Number(item.confidence_score)*100)}%</em></article>)}{!confidence.length&&<p>Confidence appears after evaluation and verified outcomes.</p>}</section>
   <section><header><strong>Proposed playbook review</strong><span>{proposals.filter((x:any)=>x.status==="PENDING_APPROVAL").length} pending</span></header>{proposals.slice(0,2).map((item:any)=><article key={item.id}><b>{words(item.task_key)}</b><p>{item.proposedChange?.recommendation}</p><small>{item.status}</small>{item.status==="PENDING_APPROVAL"&&<div><button disabled={busy||center.role!=="admin"} onClick={()=>void onAction({action:"DECIDE_DIGITAL_EMPLOYEE_PLAYBOOK",id:item.id,decision:"APPROVED"})}>Approve new version</button><button disabled={busy||center.role!=="admin"} onClick={()=>void onAction({action:"DECIDE_DIGITAL_EMPLOYEE_PLAYBOOK",id:item.id,decision:"REJECTED"})}>Keep human exception</button></div>}</article>)}{!proposals.length&&<p>Corrections can propose a version; only a human can make it live.</p>}</section>
  </div>
 </section>
}
