"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
type Reminder={id:string;title:string;scheduledAt:string;note:string;sourceType:string;sourceLabel:string;status:string;confidence:number};
type Candidate={id:string;actionType:string;urgency:string;suggestedOwner:string;confidence:number;reasoningSummary:string;decision:string;createdAt:string;sourceEventId:string;source:string;sourceAccount:string;sender:string;subject:string;receivedAt:string};
type Rule={id:string;name:string;description:string;triggerSource:string;triggerCondition:string;actionType:string;targetDepartment:string;minimumConfidence:number;approvalMode:string;urgency:string;enabled:number};
type Policy={id:string;name:string;department:string;roleLevel:string;deliveryTime:string;timezone:string;channelsJson:string;includeSectionsJson:string;hierarchyRollup:number;enabled:number};
type Briefing={id:string;recipientEmail:string;recipientName:string;department:string;roleLevel:string;briefingDate:string;title:string;summary:string;sectionsJson:string;deliveryStatus:string;generatedAt:string};
type BriefingPreference={timingMode:string;shiftOffsetMinutes:number;fixedTime:string|null;timezone:string;summaryOnly:number};
const dayKey=(value:string|Date)=>new Date(value).toISOString().slice(0,10);
const localInput=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,16);
export default function ActionCalendarCenter(){
  const [reminders,setReminders]=useState<Reminder[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]);
  const [rules,setRules]=useState<Rule[]>([]),[policies,setPolicies]=useState<Policy[]>([]),[briefings,setBriefings]=useState<Briefing[]>([]),[accessRole,setAccessRole]=useState("staff");
  const [preference,setPreference]=useState<BriefingPreference>({timingMode:"SHIFT_OFFSET",shiftOffsetMinutes:15,fixedTime:"07:15",timezone:"America/Chicago",summaryOnly:0});
  const [mode,setMode]=useState<"command"|"calendar"|"notifications"|"rules"|"briefings">("command");
  const [selectedDay,setSelectedDay]=useState(dayKey(new Date())),[title,setTitle]=useState(""),[when,setWhen]=useState(localInput(new Date(Date.now()+60*60_000)));
  const [note,setNote]=useState(""),[filter,setFilter]=useState("ALL"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [ruleForm,setRuleForm]=useState({name:"",description:"",triggerSource:"ANY_MESSAGE",triggerCondition:"",actionType:"CREATE_TASK",targetDepartment:"FRONT_DESK",minimumConfidence:90,approvalMode:"REQUIRE_APPROVAL",urgency:"MEDIUM"});
  const [policyForm,setPolicyForm]=useState({name:"",department:"FRONT_DESK",roleLevel:"ASSOCIATE",deliveryTime:"07:00",channels:["IN_APP"],sections:["SHIFT","PRIORITIES","PERFORMANCE","AI_FOCUS"],hierarchyRollup:false});
  const [openedBriefing,setOpenedBriefing]=useState<Briefing|null>(null);
  const load=useCallback(async()=>{const [r,c,a]=await Promise.all([fetch("/api/reminders",{cache:"no-store"}),fetch("/api/v1/notifications/candidates",{cache:"no-store"}),fetch("/api/v1/automation-center",{cache:"no-store"})]);
    const rd=await r.json() as {reminders?:Reminder[]};const cd=await c.json() as {candidates?:Candidate[]};const ad=await a.json() as {role?:string;rules?:Rule[];policies?:Policy[];briefings?:Briefing[];preference?:BriefingPreference};
    setReminders(rd.reminders??[]);setCandidates(cd.candidates??[]);setRules(ad.rules??[]);setPolicies(ad.policies??[]);setBriefings(ad.briefings??[]);setAccessRole(ad.role??"staff");if(ad.preference)setPreference(ad.preference)},[]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),20_000);return()=>clearInterval(timer)},[load]);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/reminders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,scheduledAt:new Date(when).toISOString(),note,sourceType:"manual",sourceLabel:"Action Center"})});
    setBusy(false);if(response.ok){setTitle("");setNote("");setMessage("Action scheduled and added to the calendar.");void load()}else setMessage("The action could not be scheduled.")}
  async function status(id:string,next:string){await fetch(`/api/reminders/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:next})});void load()}
  async function saveRule(event:FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/v1/automation-center",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"rule",...ruleForm})});const data=await response.json() as {error?:string};setBusy(false);setMessage(response.ok?"AI rule saved and activated.":data.error??"Rule could not be saved.");if(response.ok){setRuleForm({...ruleForm,name:"",description:"",triggerCondition:""});void load()}}
  async function toggleRule(rule:Rule){await fetch(`/api/v1/automation-center/rules/${rule.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:!rule.enabled})});void load()}
  async function savePolicy(event:FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/v1/automation-center",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"policy",...policyForm,timezone:"America/Chicago"})});const data=await response.json() as {error?:string};setBusy(false);setMessage(response.ok?"Daily briefing policy saved.":data.error??"Policy could not be saved.");if(response.ok){setPolicyForm({...policyForm,name:""});void load()}}
  async function generateBriefings(){setBusy(true);const response=await fetch("/api/v1/automation-center",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"generate"})});const data=await response.json() as {generated?:number;error?:string};setBusy(false);setMessage(response.ok?`${data.generated??0} employee briefings generated from current operations.`:data.error??"Briefings could not be generated.");void load()}
  async function savePreference(event:FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/v1/automation-center",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"preference",...preference,summaryOnly:Boolean(preference.summaryOnly)})});const data=await response.json() as {error?:string};setBusy(false);setMessage(response.ok?"Your briefing time and format preference is saved.":data.error??"Preference could not be saved.");void load()}
  const open=reminders.filter(item=>!["done","dismissed"].includes(item.status)),today=open.filter(item=>dayKey(item.scheduledAt)===dayKey(new Date()));
  const overdue=open.filter(item=>new Date(item.scheduledAt)<new Date()),review=candidates.filter(item=>item.decision==="PENDING_APPROVAL");
  const days=useMemo(()=>Array.from({length:14},(_,index)=>{const date=new Date();date.setDate(date.getDate()+index-3);return date}),[]);
  const visible=reminders.filter(item=>dayKey(item.scheduledAt)===selectedDay&& (filter==="ALL"||item.status===filter.toLowerCase()));
  return <main className="action-center">
    <header className="action-center-header"><div><a href="/">← AAI Q Home</a><p>Unified communication and execution</p><h1>Action, Notification & Calendar Center</h1><span>One workspace for what needs attention, where it came from, who owns it, and when it must be completed.</span></div><aside><strong>{open.length}</strong><span>open actions</span><b>{review.length} need approval</b></aside></header>
    {message&&<div className="action-message">{message}<button onClick={()=>setMessage("")}>×</button></div>}
    <nav className="action-tabs">{[["command","My command center"],["calendar","Calendar & agenda"],["notifications","Notification inbox"],["rules","Custom AI rules"],["briefings","Daily briefings"]].map(([id,label])=><button key={id} className={mode===id?"active":""} onClick={()=>setMode(id as typeof mode)}>{label}</button>)}</nav>
    <section className="action-kpis"><button onClick={()=>setMode("command")}><strong>{today.length}</strong><span>Due today</span><small>Scheduled actions</small></button><button onClick={()=>setMode("command")}><strong>{overdue.length}</strong><span>Overdue</span><small>Needs recovery</small></button><button onClick={()=>setMode("notifications")}><strong>{review.length}</strong><span>Approval queue</span><small>AI found in messages</small></button><button onClick={()=>setMode("notifications")}><strong>{candidates.filter(item=>item.urgency==="CRITICAL"||item.urgency==="HIGH").length}</strong><span>High priority</span><small>Across connected sources</small></button></section>
    {mode==="command"&&<section className="action-two-column"><article className="action-panel"><header><p>Priority stack</p><h2>What needs attention now</h2></header><div className="action-list">{open.sort((a,b)=>+new Date(a.scheduledAt)-+new Date(b.scheduledAt)).slice(0,20).map(item=><section key={item.id} className={new Date(item.scheduledAt)<new Date()?"overdue":""}><time>{new Date(item.scheduledAt).toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time><div><strong>{item.title}</strong><span>{item.note||"No additional instructions."}</span><small>{item.sourceLabel} · {item.confidence}% confidence</small></div><button onClick={()=>void status(item.id,"done")}>Complete</button><button className="quiet" onClick={()=>void status(item.id,"dismissed")}>Dismiss</button></section>)}</div></article>
      <article className="action-panel quick-action"><header><p>Quick schedule</p><h2>Create an action</h2></header><form onSubmit={create}><label>What needs to happen?<input required value={title} onChange={event=>setTitle(event.target.value)} placeholder="Call vendor about delayed linen delivery"/></label><label>When?<input required type="datetime-local" value={when} onChange={event=>setWhen(event.target.value)}/></label><label>Instructions<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Add context, owner, room, or follow-up details."/></label><button disabled={busy}>{busy?"Scheduling…":"Schedule action"}</button></form><div className="automation-summary"><strong>AAI Q automation</strong><span>Connected messages are deduplicated, classified, and routed by risk. Sensitive actions always wait for approval.</span></div></article></section>}
    {mode==="calendar"&&<section className="action-panel calendar-command"><header><div><p>Two-week operating horizon</p><h2>Calendar and agenda</h2></div><select value={filter} onChange={event=>setFilter(event.target.value)}><option>ALL</option><option>SCHEDULED</option><option>SUGGESTED</option><option>DONE</option></select></header><div className="agenda-days">{days.map(date=>{const key=dayKey(date),count=reminders.filter(item=>dayKey(item.scheduledAt)===key).length;return <button key={key} className={selectedDay===key?"active":""} onClick={()=>setSelectedDay(key)}><span>{date.toLocaleDateString([],{weekday:"short"})}</span><strong>{date.getDate()}</strong><small>{count} item{count===1?"":"s"}</small></button>})}</div><div className="day-agenda">{visible.length?visible.map(item=><article key={item.id}><time>{new Date(item.scheduledAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</time><i/><div><strong>{item.title}</strong><span>{item.note||item.sourceLabel}</span></div><b>{item.status}</b></article>):<div className="action-empty">Nothing scheduled for this day.</div>}</div></section>}
    {mode==="notifications"&&<section className="action-panel notification-command"><header><div><p>Connected-source intelligence</p><h2>Notification and approval inbox</h2></div><span>Original message protected by owner/admin access</span></header><div>{candidates.length?candidates.map(item=><article key={item.id} className={`urgency-${item.urgency.toLowerCase()}`}><div className="notification-source"><b>{item.source}</b><span>{item.sourceAccount}</span><small>{new Date(item.receivedAt).toLocaleString()}</small></div><div><strong>{item.subject||item.actionType.replace(/_/g," ")}</strong><p>{item.reasoningSummary}</p><span>Suggested owner: {item.suggestedOwner} · {item.confidence}% confidence</span></div><aside><b>{item.urgency}</b><span>{item.decision.replace(/_/g," ")}</span><a href={`/api/v1/notifications/sources/${item.sourceEventId}`} target="_blank">View protected source</a></aside></article>):<div className="action-empty">No message-derived actions yet. Scan the connected property Gmail account to populate this queue.</div>}</div></section>}
    {mode==="rules"&&<section className="automation-workspace"><article className="action-panel"><header><div><p>Rule registry</p><h2>How AAI Q is allowed to act</h2></div><span>{rules.filter(rule=>rule.enabled).length} active</span></header><div className="rule-list">{rules.length?rules.map(rule=><section key={rule.id}><div className={`rule-state ${rule.enabled?"on":"off"}`}>{rule.enabled?"ACTIVE":"PAUSED"}</div><div><strong>{rule.name}</strong><p>{rule.triggerSource.replaceAll("_"," ")}: {rule.triggerCondition}</p><span>{rule.actionType.replaceAll("_"," ")} → {rule.targetDepartment.replaceAll("_"," ")} · {rule.minimumConfidence}% confidence · {rule.approvalMode.replaceAll("_"," ")}</span></div>{accessRole==="admin"&&<button onClick={()=>void toggleRule(rule)}>{rule.enabled?"Pause":"Activate"}</button>}</section>):<div className="action-empty">No custom AI rules yet. Use the builder to define exactly what the system may do.</div>}</div></article>
      <article className="action-panel rule-builder"><header><p>Manager control</p><h2>Build a custom AI rule</h2></header>{accessRole==="admin"?<form onSubmit={saveRule}><label>Rule name<input required value={ruleForm.name} onChange={e=>setRuleForm({...ruleForm,name:e.target.value})} placeholder="Urgent room complaint recovery"/></label><label>When this source arrives<select value={ruleForm.triggerSource} onChange={e=>setRuleForm({...ruleForm,triggerSource:e.target.value})}>{["ANY_MESSAGE","GMAIL","SMS","TASK","REPORT_EVENT","CALENDAR"].map(v=><option key={v}>{v}</option>)}</select></label><label>And it matches<input required value={ruleForm.triggerCondition} onChange={e=>setRuleForm({...ruleForm,triggerCondition:e.target.value})} placeholder="mentions dirty room or guest is angry"/></label><div className="form-pair"><label>Then<select value={ruleForm.actionType} onChange={e=>setRuleForm({...ruleForm,actionType:e.target.value})}>{["CREATE_REMINDER","CREATE_TASK","NOTIFY_ROLE","REQUEST_APPROVAL","ESCALATE"].map(v=><option key={v}>{v}</option>)}</select></label><label>Route to<select value={ruleForm.targetDepartment} onChange={e=>setRuleForm({...ruleForm,targetDepartment:e.target.value})}>{["FRONT_DESK","HOUSEKEEPING","MAINTENANCE","EXECUTIVE"].map(v=><option key={v}>{v}</option>)}</select></label></div><div className="form-pair"><label>Minimum confidence<input type="number" min="50" max="100" value={ruleForm.minimumConfidence} onChange={e=>setRuleForm({...ruleForm,minimumConfidence:Number(e.target.value)})}/></label><label>Decision control<select value={ruleForm.approvalMode} onChange={e=>setRuleForm({...ruleForm,approvalMode:e.target.value})}><option>REQUIRE_APPROVAL</option><option>AUTO_EXECUTE</option></select></label></div><label>Purpose<textarea value={ruleForm.description} onChange={e=>setRuleForm({...ruleForm,description:e.target.value})} placeholder="Explain the intended outcome and exception boundary."/></label><button disabled={busy}>{busy?"Saving…":"Save and activate rule"}</button><small>Financial, HR, safety, refunds, and guest-compensation actions should remain approval-required.</small></form>:<div className="action-empty">Only managers can create or change AI operating rules.</div>}</article></section>}
    {mode==="briefings"&&<section className="briefing-workspace"><article className="action-panel briefing-list"><header><div><p>Role-level intelligence</p><h2>Employee daily briefings</h2></div>{accessRole==="admin"&&<button disabled={busy} onClick={()=>void generateBriefings()}>{busy?"Generating…":"Generate today now"}</button>}</header><div className="briefing-filter-note">Each employee sees only their briefing. Supervisors receive department performance; managers receive department and lower-level roll-ups.</div><form className="employee-briefing-preference" onSubmit={savePreference}><div><strong>My briefing preference</strong><span>Default delivery is 15 minutes after your scheduled shift begins.</span></div><label><select value={preference.timingMode} onChange={e=>setPreference({...preference,timingMode:e.target.value})}><option value="SHIFT_OFFSET">After shift starts</option><option value="FIXED_TIME">At a fixed time</option></select></label>{preference.timingMode==="SHIFT_OFFSET"?<label><input type="number" min="0" max="180" value={preference.shiftOffsetMinutes} onChange={e=>setPreference({...preference,shiftOffsetMinutes:Number(e.target.value)})}/><span>minutes after start</span></label>:<label><input type="time" value={preference.fixedTime??"07:15"} onChange={e=>setPreference({...preference,fixedTime:e.target.value})}/></label>}<label className="summary-switch"><input type="checkbox" checked={Boolean(preference.summaryOnly)} onChange={e=>setPreference({...preference,summaryOnly:e.target.checked?1:0})}/>Summary only</label><button disabled={busy}>Save</button></form><div>{briefings.length?briefings.map(item=><button key={item.id} className="briefing-row" onClick={()=>setOpenedBriefing(item)}><time>{new Date(item.generatedAt).toLocaleDateString([],{month:"short",day:"numeric"})}</time><div><strong>{item.recipientName}</strong><span>{item.department.replaceAll("_"," ")} · {item.roleLevel}</span><p>{item.summary}</p></div><b>{item.deliveryStatus}</b></button>):<div className="action-empty">No briefing has been generated yet. Managers can create today’s role-specific set now.</div>}</div></article>
      {accessRole==="admin"&&<article className="action-panel briefing-policy"><header><p>Briefing automation</p><h2>Create a delivery policy</h2></header><form onSubmit={savePolicy}><label>Policy name<input required value={policyForm.name} onChange={e=>setPolicyForm({...policyForm,name:e.target.value})} placeholder="Front Desk AM shift briefing"/></label><div className="form-pair"><label>Department<select value={policyForm.department} onChange={e=>setPolicyForm({...policyForm,department:e.target.value})}>{["FRONT_DESK","HOUSEKEEPING","MAINTENANCE","EXECUTIVE"].map(v=><option key={v}>{v}</option>)}</select></label><label>Role level<select value={policyForm.roleLevel} onChange={e=>setPolicyForm({...policyForm,roleLevel:e.target.value})}>{["ASSOCIATE","SUPERVISOR","MANAGER","CORPORATE"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Fallback delivery time<input type="time" value={policyForm.deliveryTime} onChange={e=>setPolicyForm({...policyForm,deliveryTime:e.target.value})}/><small>Used only when no employee preference or scheduled shift exists.</small></label><fieldset><legend>Delivery channels</legend>{["IN_APP","EMAIL","SMS"].map(channel=><label key={channel}><input type="checkbox" checked={policyForm.channels.includes(channel)} onChange={e=>setPolicyForm({...policyForm,channels:e.target.checked?[...policyForm.channels,channel]:policyForm.channels.filter(v=>v!==channel)})}/>{channel.replace("_"," ")}</label>)}</fieldset><label className="checkline"><input type="checkbox" checked={policyForm.hierarchyRollup} onChange={e=>setPolicyForm({...policyForm,hierarchyRollup:e.target.checked})}/>Include lower-level summaries for managers</label><button disabled={busy}>Save briefing policy</button></form><div className="policy-stack">{policies.map(policy=><span key={policy.id}><b>{policy.department.replaceAll("_"," ")}</b> {policy.roleLevel} · {policy.deliveryTime} fallback · {JSON.parse(policy.channelsJson).join(" + ")}</span>)}</div></article>}
      {openedBriefing&&<div className="briefing-drawer" role="dialog"><button className="drawer-close" onClick={()=>setOpenedBriefing(null)}>×</button><p>{openedBriefing.briefingDate} · {openedBriefing.department.replaceAll("_"," ")}</p><h2>{openedBriefing.title}</h2><strong>{openedBriefing.summary}</strong>{(JSON.parse(openedBriefing.sectionsJson) as {title:string;items:string[]}[]).map(section=><section key={section.title}><h3>{section.title}</h3>{section.items.map(item=><div key={item}>• {item}</div>)}</section>)}</div>}</section>}
  </main>
}
