"use client";
import { useEffect,useMemo,useState } from "react";

type Row=Record<string,any>;
type Data={role:string;orders:Row[];templates:Row[];attachments:Row[];steps:Row[];imports:Row[];evidenceReviews:Row[];evidenceRequirements:Record<string,string[]>};
const steps=[0,25,50,75,100];
const areaLabels:Record<string,string>={ENTRY:"Entry & door",BEDS:"Beds & linens",BATHROOM:"Bathroom",VANITY:"Vanity & amenities",FLOOR:"Floor & corners",FINAL_WIDE:"Final wide view",BEFORE:"Before condition",REPAIR_DETAIL:"Repair detail",AFTER:"After condition",SAFETY_CHECK:"Safety check"};
const employeeBlueprints={
 HOUSEKEEPING:{name:"Digital Housekeeping Supervisor",mission:"Turn room-status information into prioritized assignments, monitor completion, verify required room views, and route physical exceptions without re-entry.",automatic:["Read prior-night room-status exports and prevent duplicate assignments","Prioritize checkout, dirty-room, and readiness work","Track accepted, working, final-check, and verified states","Require entry, beds, bathroom, vanity, floor, and final-wide evidence","Create a linked maintenance ticket when housekeeping finds a defect"],asks:["Prepare today’s room-cleaning queue","Which rooms are waiting for evidence?","Show rooms likely to miss check-in time","Create a maintenance ticket for room 214’s leaking faucet","Summarize completed and blocked rooms for the supervisor"],flow:["Source report","Room queue","Assignment","Physical cleaning","Photo evidence","Supervisor verification"]},
 MAINTENANCE:{name:"Digital Maintenance & Engineering Supervisor",mission:"Receive defects, triage risk, route work, guide repairs, preserve asset history, and prevent completion without evidence.",automatic:["Receive linked defects from housekeeping and operational reports","Prioritize safety, guest-impact, and out-of-order conditions","Assign work to the lowest-load available queue","Track guided repair progress and required before/after evidence","Keep incomplete or deficient work out of Verified status"],asks:["Show critical and overdue work orders","Prioritize today’s maintenance workload","What equipment has repeat failures?","Prepare preventive maintenance due this week","Show repairs waiting for supervisor approval"],flow:["Issue intake","Risk triage","Assignment","Physical repair","Before/after evidence","Manager verification"]},
 COMPLIANCE:{name:"Digital Compliance Coordinator",mission:"Convert governed inspection templates and due dates into auditable assignments, collect required proof, and escalate unsafe or legally reserved decisions.",automatic:["Monitor active inspection and preventive-maintenance templates","Generate assignments for due property assets","Provide ordered safety and inspection steps","Capture readings, documents, photographs, and exception evidence","Escalate failed life-safety checks while preserving the audit trail"],asks:["Generate all inspections due in the next 48 hours","Show overdue compliance assignments","Which assets are missing inspection evidence?","Prepare the weekly compliance exception report","Show items requiring a licensed inspector or manager sign-off"],flow:["Rules & due dates","Asset targeting","Guided inspection","Evidence","Exception remediation","Auditable close"]},
} as const;

export default function PropertyOperationsClient({displayName,initialDepartment="HOUSEKEEPING",focused=false}:{displayName:string;initialDepartment?:"HOUSEKEEPING"|"MAINTENANCE"|"COMPLIANCE";focused?:boolean}){
  const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState<string>(initialDepartment),[notice,setNotice]=useState(""),[issueFor,setIssueFor]=useState<Row|null>(null);
  async function load(){const r=await fetch("/api/operations/workflows",{cache:"no-store"});setData(await r.json())}
  useEffect(()=>{void load()},[]);
  useEffect(()=>{if(!data)return;const requested=new URLSearchParams(window.location.search).get("workOrder");if(!requested)return;const order=data.orders.find(item=>item.id===requested);if(!order)return;setTab(order.work_type==="COMPLIANCE"?"COMPLIANCE":order.department);window.setTimeout(()=>document.getElementById(`work-order-${requested}`)?.scrollIntoView({behavior:"smooth",block:"start"}),50)},[data]);
  async function action(payload:Record<string,unknown>){setNotice("Saving…");const r=await fetch("/api/operations/workflows",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const x=await r.json() as {error?:string;created?:number;assignedTo?:string;status?:string};setNotice(x.error??(x.created!==undefined?`${x.created} due compliance assignment${x.created===1?"":"s"} generated.`:x.assignedTo?`Maintenance ticket routed to ${x.assignedTo}.`:x.status==="AWAITING_EVIDENCE_REVIEW"?"All required views are present. Submitted for visual evidence review.":"Work progress saved."));if(r.ok){setIssueFor(null);await load()}}
  async function upload(orderId:string,file:File|undefined,evidenceArea="FINAL_WIDE",evidenceStage="AFTER"){if(!file)return;setNotice(`Uploading and checking ${areaLabels[evidenceArea]??evidenceArea}…`);const form=new FormData();form.set("workOrderId",orderId);form.set("file",file);form.set("evidenceArea",evidenceArea);form.set("evidenceStage",evidenceStage);const r=await fetch("/api/operations/workflows",{method:"POST",body:form});const x=await r.json() as {error?:string};setNotice(x.error??"Evidence attached and entered into the AAIQ review queue.");if(r.ok)await load()}
  async function importNightReport(file:File|undefined){if(!file)return;setNotice("Reading previous-night room report and building department queues…");const form=new FormData();form.set("action","night_room_report");form.set("file",file);const r=await fetch("/api/operations/workflows",{method:"POST",body:form});const x=await r.json() as {error?:string;roomsRead?:number;assignmentsCreated?:number};setNotice(x.error??`${x.roomsRead} room rows read; ${x.assignmentsCreated} new assignments created automatically.`);if(r.ok)await load()}
  const orders=useMemo(()=>data?.orders.filter(x=>tab==="COMPLIANCE"?x.work_type==="COMPLIANCE":x.department===tab&&x.work_type!=="COMPLIANCE")??[],[data,tab]);
  if(!data)return <main className="po-shell"><p>Loading property operations…</p></main>;
  const blueprint=employeeBlueprints[initialDepartment];
  return <main className={`po-shell po-${initialDepartment.toLowerCase()}`}>
    <header><a href="/">← AAI Q</a><div><p>{focused?`AAIQ ${initialDepartment[0]+initialDepartment.slice(1).toLowerCase()}`:"Property Operations"}</p><h1>{focused?(initialDepartment==="HOUSEKEEPING"?"Housekeeping operations":initialDepartment==="MAINTENANCE"?"Maintenance operations":"Compliance center"):"Housekeeping, maintenance & compliance"}</h1><span>Assignment-to-verification workflows for {displayName}</span></div><a className="po-intel" href="/property-intelligence">Open analytics →</a></header>
    {focused&&<section className="digital-employee-blueprint"><header><div><small>AAIQ DIGITAL EMPLOYEE</small><h2>{blueprint.name}</h2><p>{blueprint.mission}</p></div><span>Autonomy: governed</span></header><div className="employee-capabilities"><article><h3>What happens automatically</h3>{blueprint.automatic.map(item=><p key={item}>✓ {item}</p>)}</article><article><h3>What you can ask</h3>{blueprint.asks.map(item=><p key={item}>“{item}”</p>)}</article></div><ol>{blueprint.flow.map((item,index)=><li key={item}><i>{index+1}</i><span>{item}</span></li>)}</ol><footer><b>Human boundary</b><span>AAIQ coordinates, prioritizes, documents, verifies, and escalates. Staff still perform cleaning, repairs, physical inspections, life-safety response, and legally required sign-off.</span></footer></section>}
    <section className="night-report-automation"><div><small>Front desk automation</small><h2>Upload the previous-night room report</h2><p>Upload the room-status CSV or text export. AAI Q reads dirty, checkout, out-of-order and maintenance exceptions, prevents duplicate open jobs, and builds the correct department queues automatically.</p></div><label className={data.role==="admin"?"":"disabled"}>{data.role==="admin"?"Upload & automate":"Manager access required"}<input disabled={data.role!=="admin"} type="file" accept=".csv,.txt,text/csv,text/plain" onChange={e=>void importNightReport(e.target.files?.[0])}/></label>{data.imports[0]&&<aside><strong>Last import</strong><span>{data.imports[0].file_name}</span><b>{data.imports[0].rooms_read} rooms · {data.imports[0].assignments_created} assignments</b></aside>}</section>
    {!focused&&<nav className="po-tabs">{[["HOUSEKEEPING","Housekeeping"],["MAINTENANCE","Maintenance"],["COMPLIANCE","Compliance center"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}<b>{id==="COMPLIANCE"?data.orders.filter(x=>x.work_type==="COMPLIANCE").length:data.orders.filter(x=>x.department===id&&x.work_type!=="COMPLIANCE").length}</b></button>)}</nav>}
    {notice&&<div className="po-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    {tab==="COMPLIANCE"&&<section className="compliance-banner"><div><small>Automated preventive maintenance</small><h2>Required-template assignment center</h2><p>Generate due work orders, capture required evidence, and preserve completion history. Templates are configurable operating controls—not a substitute for local code review.</p></div><button disabled={data.role!=="admin"} onClick={()=>void action({action:"generate_compliance"})}>Generate due assignments</button></section>}
    <section className="po-summary"><article><strong>{orders.filter(x=>!["COMPLETE","VERIFIED"].includes(x.status)).length}</strong><span>Open assignments</span></article><article><strong>{orders.filter(x=>x.priority==="CRITICAL").length}</strong><span>Critical</span></article><article><strong>{orders.filter(x=>x.status==="AWAITING_EVIDENCE_REVIEW").length}</strong><span>Awaiting review</span></article><article><strong>{data.evidenceReviews.filter(x=>x.review_status==="REWORK_REQUIRED").length}</strong><span>Deficiencies / retakes</span></article></section>
    <section className="po-orders">{orders.length?orders.map(order=><article id={`work-order-${order.id}`} key={order.id} className={`work-card priority-${String(order.priority).toLowerCase()}`}>
      <div className="work-head"><div><small>{order.work_type.replaceAll("_"," ")} · {order.priority}</small><h2>{order.title}</h2><p>{order.description}</p></div><span>{order.status.replaceAll("_"," ")}</span></div>
      <div className="work-meta"><span>📍 {order.room_number?`Room ${order.room_number}`:"Property-wide"}</span><span>👤 {order.assigned_to||"Department queue"}</span><span>⏱ Due {new Date(order.due_at).toLocaleString()}</span></div>
      <div className="progress-heading"><strong>Work progress</strong><b>{order.progress}%</b></div><div className="progress-track"><i style={{width:`${order.progress}%`}}/></div>
      <div className="progress-actions">{steps.map(step=><button key={step} className={Number(order.progress)===step?"active":""} onClick={()=>void action({action:"progress",id:order.id,progress:step})}>{step===0?"Assigned":step===25?"Accepted":step===50?"Working":step===75?"Final checks":"Complete"}</button>)}</div>
      {data.steps.some(step=>step.work_order_id===order.id)&&<div className="guided-steps"><header><div><small>Guided execution</small><strong>Complete each step in order</strong></div><b>{data.steps.filter(s=>s.work_order_id===order.id&&Number(s.completed)===1).length}/{data.steps.filter(s=>s.work_order_id===order.id).length}</b></header>{data.steps.filter(s=>s.work_order_id===order.id).map(step=><label key={step.id} className={Number(step.completed)===1?"done":""}><input type="checkbox" checked={Number(step.completed)===1} onChange={e=>void action({action:"toggle_step",stepId:step.id,completed:e.target.checked})}/><span><b>Step {step.step_number}</b>{step.instruction}{step.safety_note&&<em>Safety: {step.safety_note}</em>}</span></label>)}</div>}
      <div className="evidence-intelligence"><header><div><small>AAIQ completion verification</small><strong>Required photo coverage</strong></div><b>{data.evidenceRequirements[order.id].filter(area=>data.evidenceReviews.some(review=>review.work_order_id===order.id&&review.evidence_area===area)).length}/{data.evidenceRequirements[order.id].length}</b></header><div>{data.evidenceRequirements[order.id].map(area=>{const review=data.evidenceReviews.find(item=>item.work_order_id===order.id&&item.evidence_area===area);return <label key={area} className={review?String(review.review_status).toLowerCase():"missing"}><span>{review?"✓":"+"} {areaLabels[area]??area}</span><small>{review?String(review.review_status).replaceAll("_"," "):"Photo required"}</small><input type="file" accept="image/*" capture="environment" onChange={e=>void upload(order.id,e.target.files?.[0],area,area==="BEFORE"?"BEFORE":"AFTER")}/></label>})}</div><p>AAIQ checks required coverage and file integrity. A configured vision provider or an authorized manager must inspect and approve visible work before the assignment is verified.</p></div>
      <div className="evidence-zone"><div><strong>Supporting files</strong><small>Attach warranty, invoice, manual, reading, or PDF (15MB max).</small></div><label className="file-button">Upload file<input type="file" accept="image/*,application/pdf,text/plain" onChange={e=>void upload(order.id,e.target.files?.[0])}/></label></div>
      <div className="attachment-list">{data.attachments.filter(a=>a.work_order_id===order.id).map(a=><a key={a.id} target="_blank" href={`/api/operations/workflows/attachments/${a.id}`}>📎 {a.file_name}<small>{Math.ceil(Number(a.size_bytes)/1024)} KB</small></a>)}</div>
      <div className="review-findings">{data.evidenceReviews.filter(review=>review.work_order_id===order.id).map(review=>{const deficiencies=JSON.parse(review.deficiencies_json||"[]") as string[];return <article key={review.id} className={String(review.review_status).toLowerCase()}><div><b>{areaLabels[review.evidence_area]??review.evidence_area}</b><span>{String(review.review_status).replaceAll("_"," ")}{review.quality_score?` · quality ${review.quality_score}%`:""}</span>{deficiencies.map(item=><p key={item}>⚠ {item}</p>)}</div>{data.role==="admin"&&!["MANAGER_APPROVED","PASS"].includes(review.review_status)&&<aside><button onClick={()=>void action({action:"review_evidence",reviewId:review.id,decision:"APPROVE",note:"Manager visually verified completion."})}>Approve</button><button onClick={()=>void action({action:"review_evidence",reviewId:review.id,decision:"REWORK",note:"Correct deficiency and upload a replacement photo."})}>Require rework</button></aside>}</article>})}</div>
      {tab==="HOUSEKEEPING"&&<button className="issue-button" onClick={()=>setIssueFor(order)}>Found an issue? Create maintenance ticket</button>}
    </article>):<div className="po-empty">No assignments in this queue.</div>}</section>
    {tab==="COMPLIANCE"&&<section className="template-grid">{data.templates.map(t=><article key={t.id}><small>{t.code} · {t.frequency}</small><h3>{t.name}</h3><p>{t.description}</p><b>Evidence: {t.required_evidence}</b><span>Next due {new Date(t.next_due_at).toLocaleDateString()}</span></article>)}</section>}
    {issueFor&&<div className="po-modal" role="dialog" aria-modal="true"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:"maintenance_issue",parentId:issueFor.id,room:issueFor.room_number,title:f.get("title"),description:f.get("description"),priority:f.get("priority")})}}><button type="button" className="close" onClick={()=>setIssueFor(null)}>×</button><small>Linked to {issueFor.title}</small><h2>Create maintenance ticket</h2><label>Issue title<input name="title" required placeholder="Example: Bathroom faucet leaking"/></label><label>Description<textarea name="description" required placeholder="Describe what you found and any immediate safety concern."/></label><label>Priority<select name="priority" defaultValue="HIGH"><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><button className="submit">Route to maintenance</button></form></div>}
  </main>
}
