"use client";
import{useEffect,useMemo,useState}from"react";
type Row=Record<string,any>;
export default function TeamOperationsCommandCenter({displayName}:{displayName:string}){
 const[workflow,setWorkflow]=useState<any>(null),[operations,setOperations]=useState<any>(null),[view,setView]=useState("BOARD");
 useEffect(()=>{void Promise.all([fetch("/api/operations/workflows",{cache:"no-store"}).then(r=>r.json()),fetch("/api/operations/front-desk",{cache:"no-store"}).then(r=>r.json())]).then(([w,o])=>{setWorkflow(w);setOperations(o)})},[]);
 const orders=useMemo<Row[]>(()=>workflow?.orders??[],[workflow]),open=orders.filter(order=>!["COMPLETE","VERIFIED","CLOSED"].includes(order.status));
 const departments=[
  {name:"Housekeeping",href:"/housekeeping",description:"Room turns, checklist evidence, AI review and room-ready verification",orders:open.filter(x=>x.department==="HOUSEKEEPING"&&x.work_type!=="COMPLIANCE")},
  {name:"Maintenance",href:"/maintenance",description:"Guest-impact repairs, assets, parts, safety and return-to-service",orders:open.filter(x=>x.department==="MAINTENANCE"&&x.work_type!=="COMPLIANCE")},
  {name:"Compliance",href:"/compliance-center",description:"Preventive maintenance, inspections, PMI evidence and overdue controls",orders:open.filter(x=>x.work_type==="COMPLIANCE")},
 ];
 if(!workflow||!operations)return <main className="team-command"><p>Loading the active property command center…</p></main>;
 return <main className="team-command"><header><div><small>AAIQ TEAM OPERATIONS</small><h1>Manager command center</h1><p>One view of assignments, SLA exposure, verification, handoffs and department capacity for {displayName}.</p></div><aside><span>{operations.property?.code}</span><strong>{operations.property?.name}</strong><small>Fresh {new Date().toLocaleTimeString()}</small></aside></header>
 <section className="team-kpis"><article><span>Open work</span><strong>{open.length}</strong><small>Across assigned departments</small></article><article><span>Critical</span><strong>{open.filter(x=>x.priority==="CRITICAL").length}</strong><small>Immediate manager attention</small></article><article><span>Awaiting verification</span><strong>{open.filter(x=>/REVIEW|VERIFICATION/.test(x.status)).length}</strong><small>Evidence or supervisor decision</small></article><article><span>Rework</span><strong>{(workflow.evidenceReviews??[]).filter((x:Row)=>x.review_status==="REWORK_REQUIRED").length}</strong><small>Returned with corrective guidance</small></article></section>
 <section className="department-command-grid">{departments.map(department=><article key={department.name}><header><div><small>DEPARTMENT APP</small><h2>{department.name}</h2></div><strong>{department.orders.length}</strong></header><p>{department.description}</p><div><span>{department.orders.filter((x:Row)=>x.status==="IN_PROGRESS").length} in progress</span><span>{department.orders.filter((x:Row)=>x.priority==="CRITICAL").length} critical</span></div><a href={department.href}>Open AAIQ {department.name} →</a></article>)}</section>
 <section className="team-board"><header><div><small>LIVE ASSIGNMENT BOARD</small><h2>Work by execution state</h2></div><nav><button className={view==="BOARD"?"active":""} onClick={()=>setView("BOARD")}>Board</button><button className={view==="AGING"?"active":""} onClick={()=>setView("AGING")}>Aging & SLA</button></nav></header>
 <div className="team-lanes">{["ASSIGNED","IN_PROGRESS","AWAITING_EVIDENCE_REVIEW","REWORK_REQUIRED"].map(status=><section key={status}><h3>{status.replaceAll("_"," ")} <b>{open.filter(x=>x.status===status).length}</b></h3>{open.filter(x=>x.status===status).map(order=><a href={order.department==="HOUSEKEEPING"?"/housekeeping":order.work_type==="COMPLIANCE"?"/compliance-center":"/maintenance"} key={order.id}><small>{order.department} · {order.priority}</small><strong>{order.title}</strong><span>{order.room_number?`Room ${order.room_number}`:"Property-wide"} · {order.assigned_to||"Unassigned"}</span><em>{view==="AGING"&&order.due_at?`Due ${new Date(order.due_at).toLocaleString()}`:`${order.progress||0}% complete`}</em></a>)}</section>)}</div></section>
 <footer className="team-actions"><a href="/digital-front-desk">Open front desk intake</a><a href="/reports">Drill into team reports</a><a href="/action-center">Review automation exceptions</a></footer></main>
}
