"use client";import{useEffect,useMemo,useState}from"react";type Row=Record<string,any>;
export default function ReviewCenterClient(){const[data,setData]=useState<any>(null),[selected,setSelected]=useState<Row|null>(null),[filter,setFilter]=useState("ALL"),[notice,setNotice]=useState(""),[mode,setMode]=useState("queue");
async function load(){const r=await fetch("/api/v1/review-center",{cache:"no-store"});setData(await r.json())}useEffect(()=>{void load()},[]);
async function intake(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/v1/review-center",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))}),x=await r.json()as any;setNotice(x.error??(x.duplicate?"Duplicate ignored.":"Review classified, drafted and routed."));if(r.ok){e.currentTarget.reset();await load()}}
async function save(form:HTMLFormElement,action:string){if(!selected)return;const f=new FormData(form),r=await fetch("/api/v1/review-center",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({reviewId:selected.id,responseText:f.get("responseText"),action})}),x=await r.json()as any;setNotice(x.error??(action==="APPROVE"?"Response approved for posting.":"Draft saved."));if(r.ok)await load()}
async function updateCase(id:string,status:string){const r=await fetch("/api/v1/review-center",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"UPDATE_RECOVERY",caseId:id,status,ownerEmail:"Management queue"})}),x=await r.json()as any;setNotice(x.error??`Recovery moved to ${status.replaceAll("_"," ")}.`);if(r.ok)await load()}
const reviews=useMemo(()=>data?.reviews.filter((r:Row)=>filter==="ALL"||r.sentiment===filter)??[],[data,filter]);if(!data)return <main className="review-shell">Loading review intelligence…</main>;const draft=(id:string)=>data.drafts.find((d:Row)=>d.review_id===id),recovery=(id:string)=>data.cases.find((c:Row)=>c.review_id===id),advocacy=(id:string)=>data.advocacy?.find((c:Row)=>c.review_id===id);
return <main className="review-shell"><header><a href="/">← AAIQ Home</a><div><p>Guest experience intelligence</p><h1>AAIQ Review Intelligence</h1><span>Intercept, classify, recover and respond across every review source.</span></div><aside><b>{data.reviews.length}</b><span>centralized reviews</span></aside></header>{notice&&<div className="review-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
<section className="review-kpis"><article><strong>{data.reviews.filter((r:Row)=>r.sentiment==="POSITIVE").length}</strong><span>Positive</span></article><article><strong>{data.reviews.filter((r:Row)=>r.sentiment==="NEGATIVE").length}</strong><span>Negative</span></article><article><strong>{data.cases.filter((r:Row)=>r.status!=="RESOLVED").length}</strong><span>Open recovery</span></article><article><strong>{data.drafts.filter((d:Row)=>d.status==="PENDING_APPROVAL").length}</strong><span>Responses to approve</span></article></section>
<section className="review-policy"><b>AAIQ routing rule</b><span>Below 3 → management recovery</span><span>4–5 → public review options</span><span>Every response → approval + audit</span></section><nav className="review-mode">{["queue","analytics","recovery","connections"].map(x=><button className={mode===x?"active":""} onClick={()=>setMode(x)} key={x}>{x}</button>)}</nav>
{mode==="analytics"&&<section className="review-analytics">{[...new Set(data.reviews.map((r:Row)=>r.source))].map(source=>{const rows=data.reviews.filter((r:Row)=>r.source===source),rated=rows.filter((r:Row)=>r.rating);return <article key={String(source)}><b>{String(source).replaceAll("_"," ")}</b><strong>{rated.length?(rated.reduce((s:number,r:Row)=>s+Number(r.rating),0)/rated.length).toFixed(2):"—"}</strong><span>average · {rows.length} reviews</span><small>{rows.filter((r:Row)=>["NEGATIVE","CRITICAL"].includes(r.sentiment)).length} recovery cases</small></article>})}</section>}
{mode==="recovery"&&<section className="review-cases">{data.cases.map((c:Row)=><article key={c.id}><b>{c.priority}</b><div><strong>{c.department} recovery</strong><p>{c.summary}</p><small>{c.owner_email||"Unassigned"} · {c.status}</small></div><select value={c.status} onChange={e=>void updateCase(c.id,e.target.value)}><option>OPEN</option><option>IN_PROGRESS</option><option>GUEST_CONTACTED</option><option>RESOLVED</option></select></article>)}</section>}
{mode==="connections"&&<section className="review-connections"><div><h2>Review source connections</h2><p>Credentials are encrypted in the Growth Factory vault. Sources become live only after authorization and property mapping pass.</p><a href="/aaiq-website-factory">Open secure vault →</a></div>{["GOOGLE_BUSINESS","TRIPADVISOR","FACEBOOK","BOOKING_COM","EXPEDIA","WYNDHAM"].map(x=><article key={x}><b>{x.replaceAll("_"," ")}</b><span>{data.sources.find((s:Row)=>s.source===x)?.connection_status??"NOT CONNECTED"}</span></article>)}</section>}
{mode==="queue"&&<section className="review-layout"><aside className="review-intake"><small>REVIEW INTERCEPTOR</small><h2>Add or test source event</h2><form onSubmit={intake}><label>Source<select name="source"><option>GOOGLE</option><option>WYNDHAM</option><option>BOOKING_COM</option><option>EXPEDIA</option><option>TRIPADVISOR</option><option>POST_STAY_SURVEY</option></select></label><label>Account<input name="sourceAccount" defaultValue="Wyndham Garden Salina"/></label><label>External ID<input name="externalId"/></label><div><label>Guest<input name="guestName"/></label><label>Rating<input name="rating" type="number" min="1" max="5" step=".1"/></label></div><label>Title<input name="reviewTitle"/></label><label>Review<textarea name="reviewText" required/></label><button>Intercept review</button></form></aside><section className="review-queue"><nav>{["ALL","POSITIVE","NEUTRAL","NEGATIVE","CRITICAL"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</nav>{reviews.map((r:Row)=><button key={r.id} className={`review-row ${r.sentiment.toLowerCase()}`} onClick={()=>setSelected(r)}><span><b>{r.source}</b><small>{new Date(r.received_at).toLocaleDateString()}</small></span><strong>{r.rating?`${r.rating.toFixed(1)} ★`:"No rating"} · {r.guest_name}</strong><p>{r.review_text}</p><em>{r.sentiment} · {JSON.parse(r.themes_json).join(" · ")}</em>{recovery(r.id)&&<i>Recovery: {recovery(r.id).priority}</i>}</button>)}</section></section>}
{selected&&<div className="review-modal"><form onSubmit={e=>{e.preventDefault();void save(e.currentTarget,"SAVE")}}><button type="button" className="review-close" onClick={()=>setSelected(null)}>×</button><small>{selected.source} · {selected.sentiment}</small><h2>{selected.guest_name}</h2><blockquote>{selected.review_text}</blockquote>{recovery(selected.id)&&<p className="review-guard"><b>Management recovery required.</b></p>}{advocacy(selected.id)&&<div className="review-advocacy"><b>Advocacy options</b><a href={advocacy(selected.id).google_url}>Google</a><a href={advocacy(selected.id).tripadvisor_url}>Tripadvisor</a><a href={advocacy(selected.id).facebook_url}>Facebook</a></div>}<label>AAIQ response draft<textarea name="responseText" defaultValue={draft(selected.id)?.response_text}/></label><p className="review-guard">AI never posts automatically. Verify facts and approve.</p><footer><button>Save draft</button><button type="button" onClick={e=>{if(e.currentTarget.form)void save(e.currentTarget.form,"APPROVE")}}>Approve</button></footer></form></div>}</main>}
