"use client";
import { useEffect, useState } from "react";
import InventoryCountWorkspace from "./inventory-count-workspace";

type Data={role:string;propertyId:string;inventory:Array<Record<string,any>>;orders:Array<Record<string,any>>;access:Array<Record<string,any>>;velocity:Array<Record<string,any>>;transactions:Array<Record<string,any>>;requisitions:Array<Record<string,any>>;vendors:Array<Record<string,any>>;locations:Array<Record<string,any>>;purchaseOrders:Array<Record<string,any>>;poLines:Array<Record<string,any>>;countSessions:Array<Record<string,any>>};
export default function PropertyIntelligenceClient(){
  const [data,setData]=useState<Data|null>(null),[notice,setNotice]=useState(""),[confirmation,setConfirmation]=useState("TEST-WGS-104"),[room,setRoom]=useState("104"),[facility,setFacility]=useState("POOL"),[housekeeper,setHousekeeper]=useState("Test Housekeeper"),[minutes,setMinutes]=useState("28"),[inventoryTab,setInventoryTab]=useState("dashboard");
  async function load(){const r=await fetch("/api/operations/intelligence",{cache:"no-store"});setData(await r.json())}
  useEffect(()=>{void load()},[]);
  async function action(body:Record<string,unknown>){const r=await fetch("/api/operations/intelligence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json() as {error?:string;decision?:string};setNotice(x.error??(x.decision?`Access ${x.decision.toLowerCase()}.`:"Inventory workflow updated."));await load()}
  if(!data)return <main className="pi-shell">Loading property intelligence…</main>;
  const max=Math.max(1,...data.velocity.map(v=>Number(v.rooms)));
  return <main className="pi-shell">
    <header><a href="/">← AAI Q</a><p>AAIQ Inventory & Procurement</p><h1>Stock control, purchasing and immutable movement ledger.</h1><span>Active property scoped · approval controlled · report ready</span></header>
    {notice&&<div className="pi-notice">{notice}</div>}
    <details className="related-intelligence"><summary>Related operational intelligence <span>Amenity access and cleaning velocity have moved out of the inventory workspace.</span></summary><section className="pi-grid">
      <article className="pi-card"><div className="pi-title"><div><small>Smart amenity access</small><h2>Gym & pool IoT controller</h2></div><b>LIVE TEST</b></div><p>Validates the reservation profile, assigned room and facility entitlement before recording an unlock decision.</p>
        <div className="pi-form"><label>Confirmation<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><label>Room<input value={room} onChange={e=>setRoom(e.target.value)}/></label><label>Facility<select value={facility} onChange={e=>setFacility(e.target.value)}><option>POOL</option><option>GYM</option></select></label><button onClick={()=>void action({action:"verify_access",confirmation,room,facility})}>Verify & unlock</button></div>
        <div className="pi-events">{data.access.slice(0,5).map(x=><div key={x.id}><strong>{x.facility} · Room {x.room_number}</strong><span className={x.decision==="GRANTED"?"ok":"bad"}>{x.decision}</span><small>{x.reason}</small></div>)}</div>
      </article>
      <article className="pi-card"><div className="pi-title"><div><small>Housekeeping analytics</small><h2>Cleaning velocity</h2></div><b>{data.velocity.length} staff</b></div>
        {data.velocity.length?<div className="velocity-chart">{data.velocity.map(v=><div key={v.housekeeper}><label><strong>{v.housekeeper}</strong><span>{v.average_minutes} min avg · {v.rooms} rooms</span></label><i style={{width:`${Math.max(12,Number(v.rooms)/max*100)}%`}}/><small>Fastest {v.fastest_minutes}m · Slowest {v.slowest_minutes}m</small></div>)}</div>:<div className="pi-empty">No completed housekeeping timing records yet. Charts populate from real start and completion events.</div>}<div className="pi-form"><label>Housekeeper<input value={housekeeper} onChange={e=>setHousekeeper(e.target.value)}/></label><label>Room<input value={room} onChange={e=>setRoom(e.target.value)}/></label><label>Minutes<input type="number" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><button disabled={data.role!=="admin"} onClick={()=>void action({action:"record_cleaning",housekeeper,room,minutes} as Record<string,string>)}>Record test completion</button></div>
      </article>
    </section></details>
    <section className="pi-card"><div className="pi-title"><div><small>AAIQ Inventory & Procurement</small><h2>Department counts, item master, stock, requisitions, purchase orders and receiving</h2></div><b>794 preserved items · Property scoped · Audited</b></div><div className="inventory-tabs">{["dashboard","count & tally","stock","item master","requisitions","purchase orders","receiving","issues","ledger","vendors","help"].map(x=><button className={inventoryTab===x?"active":""} onClick={()=>setInventoryTab(x)} key={x}>{x}</button>)}</div>
    {["dashboard","count & tally","help"].includes(inventoryTab)&&<InventoryCountWorkspace mode={inventoryTab as "dashboard"|"count & tally"|"help"} role={data.role} sessions={data.countSessions as any} onAction={action}/>}
    {inventoryTab==="stock"&&<><div className="inventory-grid">{data.inventory.map(i=>{const risk=Number(i.quantity)<=Math.ceil(Number(i.reorder_threshold)*1.2);return <article key={i.sku} className={risk?"risk":""}><span>{i.category}</span><h3>{i.name}</h3><strong>{i.quantity}</strong><small>Threshold {i.reorder_threshold} · Target {i.target_quantity}</small><button disabled={!risk||data.role!=="admin"} onClick={()=>void action({action:"draft_order",sku:i.sku})}>{risk?"Draft supplier order":"Stock healthy"}</button></article>})}</div><div className="inventory-workbench"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:"count_adjust",sku:f.get("sku"),countedQuantity:Number(f.get("count")),reason:f.get("reason")})}}><b>Mobile cycle count / adjustment</b><select name="sku">{data.inventory.map(i=><option key={i.sku}>{i.sku}</option>)}</select><input name="count" type="number" min="0" placeholder="Counted quantity"/><input name="reason" placeholder="Count reason"/><button>Post count</button></form></div></>}
    {inventoryTab==="requisitions"&&<div className="inventory-workbench"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:"create_requisition",sku:f.get("sku"),quantity:Number(f.get("quantity")),department:f.get("department"),reason:f.get("reason")})}}><b>Create department requisition</b><select name="department"><option>HOUSEKEEPING</option><option>MAINTENANCE</option><option>FRONT_DESK</option><option>FOOD_BEVERAGE</option></select><select name="sku">{data.inventory.map(i=><option key={i.sku}>{i.sku}</option>)}</select><input name="quantity" type="number" min="1" placeholder="Quantity"/><input name="reason" placeholder="Operational need"/><button>Send for approval</button></form><section>{data.requisitions.map(r=><article key={r.id}><b>{r.department} · {r.sku}</b><span>{r.quantity} units · {r.status}</span>{r.status==="PENDING_APPROVAL"&&data.role==="admin"&&<button onClick={()=>void action({action:"approve_requisition",id:r.id})}>Approve</button>}</article>)}</section></div>}
    {inventoryTab==="item master"&&<div className="inventory-workbench inventory-master"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:"create_item",sku:f.get("sku"),name:f.get("name"),category:f.get("category"),locationId:f.get("locationId"),openingQuantity:Number(f.get("openingQuantity")),reorderThreshold:Number(f.get("reorderThreshold")),targetQuantity:Number(f.get("targetQuantity")),unitCostCents:Number(f.get("unitCostCents")),baseUnit:f.get("baseUnit"),purchaseUnit:f.get("purchaseUnit"),issueUnit:f.get("issueUnit"),packSize:Number(f.get("packSize")),barcode:f.get("barcode"),preferredVendorId:f.get("preferredVendorId"),leadTimeDays:Number(f.get("leadTimeDays")),description:f.get("description")})}}><b>Create governed inventory item</b><input name="sku" required placeholder="SKU / item code"/><input name="name" required placeholder="Official item name"/><select name="category"><option>LINEN</option><option>CHEMICAL</option><option>AMENITY</option><option>MAINTENANCE_PART</option><option>FOOD_BEVERAGE</option><option>OFFICE</option><option>SAFETY</option></select><select name="locationId">{data.locations.map(l=><option key={l.id} value={l.id}>{l.code} · {l.name}</option>)}</select><input name="openingQuantity" type="number" min="0" placeholder="Opening quantity"/><input name="reorderThreshold" type="number" min="0" placeholder="Reorder point"/><input name="targetQuantity" type="number" min="0" placeholder="Par / target"/><input name="unitCostCents" type="number" min="0" placeholder="Unit cost in cents"/><input name="baseUnit" defaultValue="EACH" placeholder="Base unit"/><input name="purchaseUnit" defaultValue="CASE" placeholder="Purchase unit"/><input name="issueUnit" defaultValue="EACH" placeholder="Issue unit"/><input name="packSize" type="number" min="1" defaultValue="1" placeholder="Pack size"/><input name="barcode" placeholder="Barcode / QR value"/><select name="preferredVendorId"><option value="">No preferred vendor</option>{data.vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><input name="leadTimeDays" type="number" min="0" defaultValue="5"/><input name="description" placeholder="Description and specifications"/><button disabled={data.role!=="admin"}>{data.role==="admin"?"Create item and opening ledger":"Administrator access required"}</button></form><section className="inventory-item-table">{data.inventory.map(item=><article key={item.sku}><b>{item.sku} · {item.name}</b><span>{item.category} · {item.base_unit}/{item.issue_unit} · pack {item.pack_size}</span><small>On hand {item.quantity} · committed {item.committed_quantity||0} · on order {item.on_order_quantity||0} · par {item.par_quantity||item.target_quantity}</small></article>)}</section></div>}
    {inventoryTab==="purchase orders"&&<div className="inventory-workbench"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:"create_purchase_order",vendorId:f.get("vendorId"),sku:f.get("sku"),quantity:Number(f.get("quantity"))})}}><b>Create approval-controlled purchase order</b><select name="vendorId" required>{data.vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select name="sku" required>{data.inventory.map(i=><option key={i.sku}>{i.sku} · {i.name}</option>)}</select><input name="quantity" type="number" min="1" placeholder="Order quantity"/><button disabled={data.role!=="admin"}>Create draft PO</button></form><section>{data.purchaseOrders.map(po=><article key={po.id}><b>{po.po_number} · {po.vendor_name||"Vendor"}</b><span>${(Number(po.total_cents)/100).toFixed(2)} · {po.status}</span>{po.status==="DRAFT_APPROVAL_REQUIRED"&&data.role==="admin"&&<button onClick={()=>void action({action:"approve_purchase_order",id:po.id})}>Approve PO</button>}</article>)}</section></div>}
    {inventoryTab==="receiving"&&<div className="inventory-workbench"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:"receive_purchase_order",id:f.get("id"),quantity:Number(f.get("quantity"))})}}><b>Receive against approved purchase order</b><select name="id" required>{data.purchaseOrders.filter(po=>["APPROVED","PARTIALLY_RECEIVED"].includes(po.status)).map(po=><option key={po.id} value={po.id}>{po.po_number} · {po.vendor_name}</option>)}</select><input name="quantity" type="number" min="1" placeholder="Quantity received now"/><input name="packingSlip" placeholder="Packing slip reference"/><button disabled={data.role!=="admin"}>Post partial / full receipt</button></form><section><p>Receiving updates the PO line, on-order quantity, stock balance, and immutable transaction ledger together.</p></section></div>}
    {inventoryTab==="issues"&&<div className="inventory-workbench"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:"issue_stock",sku:f.get("sku"),quantity:Number(f.get("quantity")),reason:f.get("reason"),referenceId:f.get("referenceId")})}}><b>Issue inventory to department, room or task</b><select name="sku">{data.inventory.map(i=><option key={i.sku}>{i.sku} · available {i.quantity}</option>)}</select><input name="quantity" type="number" min="1" placeholder="Issue quantity"/><input name="referenceId" placeholder="Room, task or department reference"/><input name="reason" placeholder="Housekeeping delivery, maintenance repair…"/><button disabled={data.role!=="admin"}>Issue and post ledger movement</button></form></div>}
    {inventoryTab==="ledger"&&<div className="inventory-ledger">{data.transactions.map(t=><article key={t.id}><b>{t.transaction_type} · {t.sku}</b><span>{t.quantity>0?"+":""}{t.quantity} · balance {t.balance_after}</span><small>{t.reason} · {new Date(t.created_at).toLocaleString()}</small></article>)}</div>}
    {inventoryTab==="vendors"&&<div className="inventory-ledger">{data.vendors.map(v=><article key={v.id}><b>{v.name}</b><span>{v.lead_time_days} day lead · minimum ${(v.minimum_order_cents/100).toFixed(2)}</span><small>{v.contact_email} · {v.status}</small></article>)}</div>}
    <div className="pi-orders">{data.orders.map(o=><div key={o.id}><strong>{o.sku}</strong><span>{o.quantity} units · ${(o.total_cost_cents/100).toFixed(2)}</span><b>{o.status}</b></div>)}</div></section>
  </main>
}
