"use client";
import {useEffect,useMemo,useState} from "react";
import "./online-presence.css";
import "./property-mapping.css";

type Integration={provider_key:string;display_name:string;status:string;last_health_status:string|null;last_health_at:string|null;last_health_message:string|null};
type Center={role?:string;property?:{id:string;name:string;code:string};integrations?:Integration[];channels?:Array<{key:string;name:string;status:string;category:string}>;mapping?:{external_property_id:string;external_property_name:string;status:string}|null;externalProperties?:Array<{id:string;name:string}>;activity?:Array<{id:string;event_type:string;entity_type:string;entity_id:string;author_type:string;author_id:string;checksum:string;occurred_at:string}>};
const commandCenter="https://hotel-presence-command-center.mukeshmp.chatgpt.site";
const modules=[
 {key:"META_CAPI",name:"Social & advertising",scope:"Facebook, Instagram, approved publishing and conversion evidence",owner:"Shared Integration Registry"},
 {key:"GOOGLE_BUSINESS",name:"Listings & rankings",scope:"Google Business Profile, reviews, local visibility and competitor monitoring",owner:"Online Presence module"},
 {key:"UNIFI",name:"Network Center",scope:"Gateways, access points, guest WiFi, diagnostics and safe recovery",owner:"Technology federation"},
 {key:"GDMS",name:"Phone Center",scope:"Grandstream inventory, registration, templates and phone troubleshooting",owner:"Technology federation"},
 {key:"LOREX",name:"Camera Center",scope:"Recorder inventory, camera health and privacy-protected incident workflows",owner:"Technology federation"},
 {key:"GUEST_SUPPORT",name:"Guest Support",scope:"Guest questions, service recovery, conversations, handoffs and approved autonomous answers",owner:"AAIQ Digital Front Desk and Master Inbox"},
];
const functions=[
 {name:"Dashboard",detail:"Property-wide marketing and technology readiness",href:"LOCAL_DASHBOARD",owner:"AAIQ Online Presence"},
 {name:"Launch Center",detail:"Canonical sample configuration, safeguards and UAT",href:"/aaiq-pilot-launch",owner:"AAIQ Sample Launch Center"},
 {name:"Autopilot",detail:"Governed digital employees, automation limits and evaluations",href:"/aaiq-agent-studio",owner:"AAIQ Digital Employees"},
 {name:"Approvals",detail:"Human decisions for consequential and public actions",href:"/action-center",owner:"AAIQ Action Center"},
 {name:"Content Studio",detail:"Create, schedule and approve marketing content",href:"/aaiq-website-factory",owner:"AAIQ Website & Growth Factory"},
 {name:"Channels",detail:"Connect social, listings, reviews, OTA and messaging providers",href:"/aaiq-integration-center",owner:"AAIQ Governed Integrations"},
 {name:"Network Center",detail:"UniFi gateways, access points, guest WiFi and diagnostics",href:commandCenter,owner:"Federated Version 20 workspace",external:true},
 {name:"Phone Center",detail:"Grandstream GDMS inventory, registration and troubleshooting",href:commandCenter,owner:"Federated Version 20 workspace",external:true},
 {name:"Camera Center",detail:"Lorex recorder and camera health with privacy controls",href:commandCenter,owner:"Federated Version 20 workspace",external:true},
 {name:"Guest Support",detail:"Guest questions, conversations, service recovery and handoffs",href:"/digital-front-desk",owner:"AAIQ Digital Front Desk"},
 {name:"Apps",detail:"All installed AAIQ operational applications",href:"/",owner:"AAIQ application shell"},
 {name:"Activity",detail:"Property-scoped integration and command audit evidence",href:"LOCAL_ACTIVITY",owner:"AAIQ Audit Core"},
 {name:"Settings",detail:"Credentials, endpoints, provider controls and property access",href:"/aaiq-integration-center",owner:"AAIQ Governed Integrations"},
 {name:"Help",detail:"Detailed beginner guidance for every Command Center function",href:"LOCAL_HELP",owner:"AAIQ contextual help"},
] as const;
const commandHelp=[
 ["Dashboard","Use Dashboard to see the active property, verified live-capability count, mapping status, last health evidence, and the protected merge sequence. Start here at the beginning of each shift; a yellow or pending state means setup or evidence is still required, not that the provider is connected."],
 ["Launch Center","Start with the fully prepared canonical sample property. Verify its seeded staff, rooms, assets, reports, connectors and digital employees, execute role tests, then clone the proven sample into an editable real property. AAIQ asks only for facts and credentials it cannot safely invent."],
 ["Autopilot","Autopilot is implemented through AAIQ Digital Employees. Configure a role, authorized sources, tools, confidence threshold, approval boundary, schedule, escalation recipient, and manual fallback; then run evaluations before allowing any real action."],
 ["Approvals","Approvals routes consequential proposals to a human. Review the property, source evidence, requested action, financial or operational risk reason, affected guest or system, and rollback path. Approve only the exact action shown; rejection must preserve the original record and audit receipt."],
 ["Content Studio","Create social posts, short videos, ads, events, blogs, offers, and synchronized profile updates in Website & Growth Factory. Content remains a draft until its required approval is recorded; scheduling does not bypass channel authorization or public-response policy."],
 ["Channels","Connect providers only in Governed Integrations. Choose the active property, enter the official HTTPS endpoint, save credentials in the encrypted server form, run a health check, verify the returned account/property identity, and keep the truthful state Configuration Required until evidence passes."],
 ["Network Center","Network Center currently preserves the Version 20 UniFi workspace while AAIQ owns property identity, tasks, approvals and audit. Start read-only: verify gateway, controller/site, access points, WAN health and guest-network isolation; configuration pushes remain approval-controlled."],
 ["Phone Center","Phone Center currently preserves the Version 20 Grandstream GDMS workspace. Verify account and site, device inventory, model/firmware, registration, extension mapping and alert health before enabling templates or remote changes; retain a rollback configuration and on-site contact."],
 ["Camera Center","Camera Center currently preserves the Version 20 Lorex workspace. Confirm recorder model, property ownership, camera names, time synchronization, health and retention; do not expose guest video or enable surveillance actions without approved policy, signage, access restrictions and incident purpose."],
 ["Guest Support","Guest Support uses Digital Front Desk and Master Inbox. Configure approved property facts, consent and quiet hours, escalation contacts, service-recovery limits and unsupported-question handling; begin in suggested-answer mode before enabling routine autonomous replies."],
 ["Apps","Use AAIQ Apps in the top bar to open focused workspaces by Operations, People, Growth and Management. Every app shares the active property, user identity, tasks, reporting and audit services, so do not create separate hotel records inside an app."],
 ["Activity","Activity shows property-scoped integration, federation, social, connector, pilot and Command Center audit events. Use the timestamp, actor, entity and checksum to investigate a change; never edit an audit receipt to make a failed action look successful."],
 ["Settings","Provider endpoints and secrets belong in Governed Integrations; property, role and MFA settings belong in User & Access; hotel identity belongs in Property & Assets. This separation prevents duplicated credentials and accidental cross-property configuration."],
 ["Help","Open this guide whenever a status, disabled control or next step is unclear. Follow the related workspace link, complete prerequisites in order, record evidence without secrets, and stop immediately for property-isolation, payment, consent, access-control or surveillance problems."],
] as const;

export default function OnlinePresenceClient(){
 const[data,setData]=useState<Center|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[externalId,setExternalId]=useState(""),[message,setMessage]=useState(""),[view,setView]=useState<"DASHBOARD"|"FUNCTIONS"|"ACTIVITY"|"HELP">("DASHBOARD"),[helpTopic,setHelpTopic]=useState("Dashboard");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/v1/online-presence",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Shared integration status is unavailable");setData(d);setExternalId(d.mapping?.external_property_id||"")}catch(e){setError(e instanceof Error?e.message:"Shared integration status is unavailable")}finally{setLoading(false)}}
 async function saveMapping(){setLoading(true);setMessage("");const r=await fetch("/api/v1/online-presence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"MAP_PROPERTY",externalPropertyId:externalId})}),d=await r.json();setLoading(false);if(!r.ok){setMessage(d.error||"Property mapping was not saved.");return}setData(current=>({...current,...d}));setMessage("Property mapping saved as unverified. Signed read-only verification is the next step.")}
 useEffect(()=>{void load()},[]);
 const integrations=new Map((data?.integrations??[]).map(x=>[x.provider_key,x]));
 const channels=new Map((data?.channels??[]).map(x=>[x.key,x]));
 const rows=useMemo(()=>modules.map(m=>{const record=integrations.get(m.key),channel=channels.get(m.key);const status=m.key==="GUEST_SUPPORT"?"ACTIVE":record?.status||channel?.status||"FEDERATION_PENDING";return{...m,status,health:record?.last_health_status,lastHealthAt:record?.last_health_at}}),[data]);
 const connected=rows.filter(x=>x.status==="CONNECTED"||x.status==="ACTIVE").length;
 return <main className="op-tech"><header><div><small>AAIQ RELEASE 97 × COMMAND CENTER VERSION 20</small><h1>AAIQ Online Presence & Technology</h1><p>One property context for marketing, rankings, networks, phones, cameras and autonomous guest support—without copying credentials, tasks or hotel records.</p></div><div><strong>{data?.property?.name??"Loading property context…"}</strong><span>{data?.property?.code??"AAIQ FEDERATION"}</span></div></header>
 <nav className="command-tabs" aria-label="Online Presence Command Center"><button className={view==="DASHBOARD"?"active":""} onClick={()=>setView("DASHBOARD")}>Dashboard</button><button className={view==="FUNCTIONS"?"active":""} onClick={()=>setView("FUNCTIONS")}>All functions</button><button className={view==="ACTIVITY"?"active":""} onClick={()=>setView("ACTIVITY")}>Activity</button><button className={view==="HELP"?"active":""} onClick={()=>setView("HELP")}>Detailed help</button></nav>
 {view==="DASHBOARD"&&<>
 <section className="baseline-notice"><b>Protected baselines</b><span>AAIQ Release 90 and Command Center Version 20 remain operational. This module adds a reversible federation layer; it does not delete, overwrite or restart either system.</span></section>
 {error&&<section className="op-error" role="alert"><span><b>Shared status could not load</b>{error}. No records were changed.</span><button onClick={()=>void load()}>Try again</button></section>}
 <section className="op-hero"><div className="op-score"><strong>{connected}/{rows.length}</strong><span>live capabilities verified in AAIQ</span></div><div><small>MERGE POSITION</small><h2>{connected?"Federation is partially operational":"Safe federation foundation is ready"}</h2><p>Connection states are intentionally conservative. Existing Command Center setup is not marked Connected in AAIQ until property mapping, signed health exchange and audit reconciliation are verified.</p></div><a href={commandCenter} target="_blank" rel="noreferrer">Open Command Center Version 20 ↗</a></section>
 <section className="property-mapping"><div><small>STEP 2 · CANONICAL PROPERTY MAPPING</small><h2>Link records without copying the hotel</h2><p>AAIQ remains authoritative. Choose the matching Command Center hotel for the active AAIQ property. This saves identifiers only—no credentials, tasks, guests or hotel records are duplicated.</p></div><div className="mapping-form"><label><span>Active AAIQ property</span><strong>{data?.property?.name??"Loading…"}</strong><small>{data?.property?.code??"Property context required"}</small></label><label><span>Matching Command Center hotel</span><select value={externalId} onChange={e=>setExternalId(e.target.value)} disabled={data?.role!=="admin"}><option value="">Choose the exact hotel</option>{(data?.externalProperties??[]).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><button onClick={()=>void saveMapping()} disabled={loading||!externalId||data?.role!=="admin"}>{loading?"Saving…":data?.mapping?"Update mapping":"Save mapping"}</button><em className={data?.mapping?"mapped":"pending"}>{data?.mapping?`${data.mapping.external_property_name} · ${data.mapping.status.replaceAll("_"," ")}`:data?.role==="admin"?"Mapping required":"Administrator action required"}</em></div>{message&&<p className="mapping-message">{message}</p>}</section>
 <section className="op-grid">{rows.map(row=><article key={row.key}><header><i>{row.name.slice(0,1)}</i><b className={`op-status ${row.status.toLowerCase()}`}>{row.status.replaceAll("_"," ")}</b></header><h3>{row.name}</h3><p>{row.scope}</p><dl><div><dt>System owner</dt><dd>{row.owner}</dd></div><div><dt>Last AAIQ health proof</dt><dd>{row.lastHealthAt?new Date(row.lastHealthAt).toLocaleString():row.key==="GUEST_SUPPORT"?"Native AAIQ workflow":"Not received"}</dd></div></dl><a href={row.key==="UNIFI"||row.key==="GDMS"||row.key==="LOREX"?commandCenter:row.key==="GUEST_SUPPORT"?"/digital-front-desk":"/aaiq-integration-center"}>{row.key==="UNIFI"||row.key==="GDMS"||row.key==="LOREX"?"Continue existing setup ↗":row.key==="GUEST_SUPPORT"?"Open Guest Support →":"Open governed setup →"}</a></article>)}</section>
 <section className="merge-plan"><header><div><small>NO-LOSS INTEGRATION SEQUENCE</small><h2>Complete merge path</h2></div><button onClick={()=>void load()} disabled={loading}>{loading?"Checking…":"Refresh shared status"}</button></header>{[
  ["1","Inventory and freeze duplicates","Complete","AAIQ and Command Center baselines identified; no retirement or deletion authorized."],
  ["2","Canonical property mapping",data?.mapping?"Complete":"Next",data?.mapping?`${data.property?.name} is linked to ${data.mapping.external_property_name}; signed verification remains separate.`:"Map AAIQ property IDs to Command Center hotel records without copying the hotels."],
  ["3","Signed read-only health exchange","Planned","Receive connector status and timestamps through a narrow authenticated service contract."],
  ["4","Shared task and approval routing","Planned","Send detected exceptions into AAIQ calendar, assignments, approvals and audit history."],
  ["5","Credential ownership migration","Protected","Move each provider credential once, only after its replacement connection is verified."],
  ["6","Side-by-side certification","Protected","Compare results before any duplicate screen or data path is retired."],
 ].map(([n,title,status,detail])=><article key={n}><b>{n}</b><div><strong>{title}</strong><span>{detail}</span></div><em className={status.toLowerCase()}>{status}</em></article>)}</section>
 <section className="ownership-contract"><div><small>COMMON CORE</small><h2>One owner for every shared responsibility</h2><p>This prevents double work while keeping focused workspaces easy to use.</p></div>{[
  ["Properties, users and roles","AAIQ authoritative"],["Tasks, reminders and calendar","AAIQ Unified Work Engine"],["Approvals, notifications and audit","AAIQ governed core"],["Provider credentials","One shared encrypted vault"],["Online presence user experience","This AAIQ module"],["Network, phone and camera operations","Federated technology workspaces"],
 ].map(([domain,owner])=><span key={domain}><b>{domain}</b><small>{owner}</small></span>)}</section></>}
 {view==="FUNCTIONS"&&<section className="command-directory"><header><small>COMPLETE VERSION 20 CAPABILITY MAP</small><h2>Every Command Center function</h2><p>Each function has one canonical owner. Opening it continues the existing AAIQ workflow instead of creating a duplicate screen or data store.</p></header><div>{functions.map(item=>item.href.startsWith("LOCAL_")?<button key={item.name} onClick={()=>setView(item.href==="LOCAL_ACTIVITY"?"ACTIVITY":item.href==="LOCAL_HELP"?"HELP":"DASHBOARD")}><i>{item.name.slice(0,1)}</i><span><b>{item.name}</b><small>{item.detail}</small><em>{item.owner}</em></span></button>:<a href={item.href} target={item.external?"_blank":undefined} rel={item.external?"noreferrer":undefined} key={item.name}><i>{item.name.slice(0,1)}</i><span><b>{item.name}</b><small>{item.detail}</small><em>{item.owner}{item.external?" · preserved Version 20":""}</em></span></a>)}</div></section>}
 {view==="ACTIVITY"&&<section className="command-activity"><header><small>LIVE PROPERTY-SCOPED EVIDENCE</small><h2>Command Center activity</h2><p>Integration, federation, social, connector and pilot changes for {data?.property?.name}. Every record is append-only and checksum protected.</p></header>{data?.activity?.length?data.activity.map(item=><article key={item.id}><span><b>{item.event_type.replaceAll("_"," ")}</b><small>{item.entity_type} · {item.entity_id}</small><em>{item.author_type}: {item.author_id}</em></span><span><time>{new Date(item.occurred_at).toLocaleString()}</time><code>{item.checksum.slice(0,12)}…</code></span></article>):<p className="command-empty">No Command Center activity has been recorded for this property yet. Complete a mapping, connection health check, pilot task, or approved content action to create evidence.</p>}</section>}
 {view==="HELP"&&<section className="command-help"><aside><small>AAIQ COMMAND CENTER HANDBOOK</small><h2>Detailed help</h2><p>Select any Version 20 function to learn its purpose, exact operating path, safety boundary, and what must be verified before pilot use.</p>{commandHelp.map(([title])=><button className={helpTopic===title?"active":""} onClick={()=>setHelpTopic(title)} key={title}>{title}</button>)}</aside><article>{commandHelp.filter(([title])=>title===helpTopic).map(([title,body])=><div key={title}><small>BEGINNER GUIDE · NO PRIOR TRAINING REQUIRED</small><h2>{title}</h2><section><i>1</i><div><b>What this function does</b><p>{functions.find(x=>x.name===title)?.detail||"Guided Command Center capability."}</p></div></section><section><i>2</i><div><b>How to use it safely</b><p>{body}</p></div></section><section><i>3</i><div><b>What success looks like</b><p>The active property is correct, the status is evidence-backed, the responsible user and next step are visible, sensitive actions remain approval-controlled, and the audit record can be traced to its source.</p></div></section><button onClick={()=>setView("FUNCTIONS")}>Open complete function directory</button></div>)}</article></section>}
 </main>
}
