import {env} from "cloudflare:workers";
import {activeStaffContext} from "./staff";
import {recordSystemAudit} from "./platform-controls";
import {authorizedPropertyScope} from "./property-scope";
const SYSTEM_KEY="HOTEL_COMMAND_CENTER",BASE_URL="https://hotel-presence-command-center.mukeshmp.chatgpt.site";
const EXTERNAL_PROPERTIES=[{id:"wyndham-garden-salina",name:"Wyndham Garden Salina"},{id:"days-inn-salina-south",name:"Days Inn Salina South"}];
function db():D1Database{if(!env.DB)throw new Error("AAIQ federation storage is unavailable.");return env.DB}
async function ensure(){db()}
async function property(context:any){return(await authorizedPropertyScope(context.email))?.property||null}
export async function federationCenter(email:string){const context=await activeStaffContext(email);if(!context)return null;await ensure();const active=await property(context);if(!active)return null;const now=new Date().toISOString();await db().prepare(`INSERT OR IGNORE INTO external_system_federations(id,organization_id,system_key,display_name,base_url,status,trust_mode,created_by,created_at,updated_at) VALUES(?,?,?,'Hotel Presence Command Center',?,'MAPPING_REQUIRED','SIGNED_READ_ONLY_PENDING',?,?,?)`).bind(crypto.randomUUID(),context.organizationId,SYSTEM_KEY,BASE_URL,email,now,now).run();const[system,mapping,activity]=await Promise.all([db().prepare("SELECT * FROM external_system_federations WHERE organization_id=? AND system_key=?").bind(context.organizationId,SYSTEM_KEY).first(),db().prepare("SELECT * FROM property_federation_mappings WHERE organization_id=? AND property_id=? AND system_key=?").bind(context.organizationId,active.id,SYSTEM_KEY).first(),db().prepare(`SELECT id,event_type,entity_type,entity_id,author_type,author_id,checksum,occurred_at FROM system_audit_trail WHERE organization_id=? AND (property_id=? OR property_id=?) AND (event_type LIKE '%INTEGRATION%' OR event_type LIKE '%FEDERATION%' OR event_type LIKE '%SOCIAL%' OR event_type LIKE '%PILOT%' OR event_type LIKE '%CONNECTOR%' OR event_type LIKE '%COMMAND_CENTER%') ORDER BY occurred_at DESC LIMIT 100`).bind(context.organizationId,active.id,context.organizationId).all()]);return{role:context.role,property:active,system,mapping,externalProperties:EXTERNAL_PROPERTIES,activity:activity.results}}
export async function saveFederationMapping(email:string,input:any){const context=await activeStaffContext(email);if(!context||context.role!=="admin")return null;await ensure();const active=await property(context);if(!active)return null;const external=EXTERNAL_PROPERTIES.find(x=>x.id===String(input.externalPropertyId||""));if(!external)throw new Error("Choose a recognized Command Center hotel.");const conflict=await db().prepare("SELECT property_id FROM property_federation_mappings WHERE organization_id=? AND system_key=? AND external_property_id=? AND property_id<>?").bind(context.organizationId,SYSTEM_KEY,external.id,active.id).first();if(conflict)throw new Error("That Command Center hotel is already mapped to another AAIQ property.");const now=new Date().toISOString();await db().prepare(`INSERT INTO property_federation_mappings(id,organization_id,property_id,system_key,external_property_id,external_property_name,status,verified_by,verified_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,'MAPPED_UNVERIFIED',NULL,NULL,?,?,?) ON CONFLICT(organization_id,property_id,system_key) DO UPDATE SET external_property_id=excluded.external_property_id,external_property_name=excluded.external_property_name,status='MAPPED_UNVERIFIED',verified_by=NULL,verified_at=NULL,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),context.organizationId,active.id,SYSTEM_KEY,external.id,external.name,email,now,now).run();await db().prepare("UPDATE external_system_federations SET status='MAPPED_UNVERIFIED',updated_at=? WHERE organization_id=? AND system_key=?").bind(now,context.organizationId,SYSTEM_KEY).run();await recordSystemAudit({organizationId:context.organizationId,propertyId:active.id,eventType:"COMMAND_CENTER_PROPERTY_MAPPED",entityType:"PROPERTY_FEDERATION_MAPPING",entityId:external.id,authorType:"USER",authorId:email,correlationId:crypto.randomUUID(),delta:{aaiqPropertyId:active.id,externalPropertyId:external.id,status:"MAPPED_UNVERIFIED",credentialsCopied:false}});return federationCenter(email)}
