/* eslint-disable @typescript-eslint/no-explicit-any */
import{env}from"cloudflare:workers";import{activeStaffContext}from"./staff";import{authorizedPropertyScope}from"./property-scope";
function database():D1Database{if(!env.DB)throw new Error("Customer intelligence storage unavailable.");return env.DB}
async function ensure(){database();}
async function property(context:any){return(await authorizedPropertyScope(context.email))?.property||null}
async function seed(context:any,p:any){const count=await database().prepare("SELECT COUNT(*) count FROM cdp_customer_profiles WHERE organization_id=? AND property_id=?").bind(context.organizationId,p.id).first<{count:number}>();if(Number(count?.count))return;const now=new Date().toISOString(),c1=crypto.randomUUID(),c2=crypto.randomUUID(),c3=crypto.randomUUID();await database().batch([
 database().prepare("INSERT INTO cdp_customer_profiles VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(c1,context.organizationId,p.id,"SAMPLE-GUEST-001","sha256:sample-high-value",null,1280,286,2,3,JSON.stringify(["High-Net-Worth","Luxury-Wellness"]),1,1,0,now,now),
 database().prepare("INSERT INTO cdp_customer_profiles VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(c2,context.organizationId,p.id,"SAMPLE-GUEST-002","sha256:sample-corporate",null,780,68,4,1,JSON.stringify(["Corporate-Traveler"]),1,1,0,now,now),
 database().prepare("INSERT INTO cdp_customer_profiles VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(c3,context.organizationId,p.id,"SAMPLE-GUEST-003",null,null,0,42,0,1,JSON.stringify([]),0,0,0,now,now),
 ...[["WEBSITE_TRACKER","CLICKSTREAM","Website intent","CONNECTED"],["PMS","TRANSACTION","PMS folios","CONFIGURATION_REQUIRED"],["RESTAURANT_POS","TRANSACTION","Restaurant POS","CONFIGURATION_REQUIRED"],["WIFI","IDENTITY","Guest Wi-Fi","CONFIGURATION_REQUIRED"],["META_CAPI","ACTIVATION","Meta Conversions API","CONFIGURATION_REQUIRED"],["GOOGLE_CUSTOMER_MATCH","ACTIVATION","Google Customer Match","CONFIGURATION_REQUIRED"],["SENDGRID","DELIVERY","SendGrid loyalty email","CONFIGURATION_REQUIRED"],["POSTIZ","PUBLISHING","Postiz organic publishing","CONNECTED"]].map(row=>database().prepare("INSERT OR IGNORE INTO cdp_source_registry VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.organizationId,p.id,...row,null,null,now,now)),
 database().prepare("INSERT INTO cdp_tracking_events VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.organizationId,p.id,"sample-event-001","Searched_Wine_Pairing","anon_sample_001",c1,"WEBSITE",JSON.stringify({search_term:"wine pairing",page_url:"/restaurant"}),now,now),
 database().prepare("INSERT INTO cdp_tracking_events VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.organizationId,p.id,"sample-event-002","Viewed_Luxury_Suite","anon_sample_001",c1,"WEBSITE",JSON.stringify({room_type:"Luxury Suite",page_url:"/rooms/luxury-suite"}),now,now)
 ,database().prepare("INSERT OR IGNORE INTO cdp_geo_audiences VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.organizationId,p.id,"Salina local hospitality market","CITY_ZIP","Salina","KS",JSON.stringify(["67401","67402"]),null,"Consented local hotel and restaurant offers","DRAFT",context.email,now,now)
]);}
function tags(rows:any[]){return rows.flatMap(row=>{try{return JSON.parse(row.cohort_tags_json)}catch{return[]}}).reduce((a:any,t:string)=>(a[t]=(a[t]||0)+1,a),{})}
export async function customerIntelligenceCenter(email:string){const c=await activeStaffContext(email);if(!c)return null;await ensure();const p=await property(c);if(!p)return null;await seed(c,p);const [sources,profiles,events,transactions,activations,audits,geoAudiences]=await Promise.all([
 database().prepare("SELECT * FROM cdp_source_registry WHERE organization_id=? AND property_id=? ORDER BY label").bind(c.organizationId,p.id).all(),
 database().prepare("SELECT * FROM cdp_customer_profiles WHERE organization_id=? AND property_id=? ORDER BY total_restaurant_spend+total_hotel_spend DESC LIMIT 100").bind(c.organizationId,p.id).all(),
 database().prepare("SELECT * FROM cdp_tracking_events WHERE organization_id=? AND property_id=? ORDER BY occurred_at DESC LIMIT 100").bind(c.organizationId,p.id).all(),
 database().prepare("SELECT * FROM cdp_transactions WHERE organization_id=? AND property_id=? ORDER BY business_date DESC LIMIT 100").bind(c.organizationId,p.id).all(),
 database().prepare("SELECT a.*,p.customer_ref,json_extract(a.payload_json,'$.geoAudienceName') geo_audience_name FROM cdp_activation_requests a JOIN cdp_customer_profiles p ON p.id=a.customer_id WHERE a.organization_id=? AND a.property_id=? ORDER BY a.created_at DESC LIMIT 100").bind(c.organizationId,p.id).all(),
 database().prepare("SELECT * FROM cdp_audit_events WHERE organization_id=? AND property_id=? ORDER BY created_at DESC LIMIT 50").bind(c.organizationId,p.id).all(),
 database().prepare("SELECT * FROM cdp_geo_audiences WHERE organization_id=? AND property_id=? ORDER BY name").bind(c.organizationId,p.id).all()
]);const ps=profiles.results as any[],tx=transactions.results as any[];return{role:c.role,property:p,sources:sources.results,profiles:ps,events:events.results,transactions:tx,activations:activations.results,audits:audits.results,geoAudiences:geoAudiences.results,summary:{knownCustomers:ps.length,consentedCustomers:ps.filter(x=>x.marketing_consent&&!x.suppressed).length,attributedRevenue:tx.reduce((n,x)=>n+Number(x.amount_spent),0),pendingApprovals:(activations.results as any[]).filter(x=>x.status==="NEEDS_REVIEW").length,cohorts:tags(ps),freshness:new Date().toISOString()}}}
const cleanProperties=(input:any)=>{const allowed=["page_url","page_title","search_term","room_type","menu_category","campaign","referrer","currency","value","business_date","nights"];const result:any={};for(const key of allowed)if(input?.[key]!==undefined)result[key]=String(input[key]).slice(0,500);return result}
export async function customerIntelligenceAction(email:string,input:any){const c=await activeStaffContext(email);if(!c)return null;await ensure();const p=await property(c);if(!p)return null;const now=new Date().toISOString(),action=String(input.action||"");let id=crypto.randomUUID(),status="SUCCEEDED",detail:any={action};
 if(action==="TRACK_EVENT"){const anonymous=String(input.anonymousId||"").trim();if(anonymous.length<8)throw new Error("Anonymous ID must contain at least 8 characters.");const name=String(input.eventName||"").trim();if(!/^[A-Za-z][A-Za-z0-9_]{1,119}$/.test(name))throw new Error("Enter a valid event name.");await database().prepare("INSERT INTO cdp_tracking_events VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,c.organizationId,p.id,String(input.idempotencyKey||crypto.randomUUID()),name,anonymous,input.customerId||null,String(input.source||"WEBSITE"),JSON.stringify(cleanProperties(input.properties)),input.occurredAt||now,now).run();detail={eventName:name,source:input.source||"WEBSITE"}}
 else if(action==="INGEST_TRANSACTION"){const profile=await database().prepare("SELECT * FROM cdp_customer_profiles WHERE id=? AND organization_id=? AND property_id=?").bind(input.customerId,c.organizationId,p.id).first<any>();if(!profile)throw new Error("Select a customer in the active property.");const amount=Number(input.amountSpent);if(!Number.isFinite(amount)||amount<=0)throw new Error("Amount must be greater than zero.");id=crypto.randomUUID();await database().prepare("INSERT INTO cdp_transactions VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,c.organizationId,p.id,String(input.externalTransactionId||crypto.randomUUID()),profile.id,amount,String(input.department),JSON.stringify(input.items||[]),input.businessDate||now,String(input.source||"MANUAL"),now).run();let hotel=Number(profile.total_hotel_spend),restaurant=Number(profile.total_restaurant_spend),hn=Number(profile.hotel_nights),rv=Number(profile.restaurant_visits);if(input.department==="hotel"){hotel+=amount;hn++}else{restaurant+=amount;rv++}const cohort=[];if(amount>500&&input.department==="hotel"||amount>150&&input.department==="restaurant")cohort.push("High-Net-Worth");if(hn>=2)cohort.push("Corporate-Traveler");const existing=JSON.parse(profile.cohort_tags_json||"[]");await database().prepare("UPDATE cdp_customer_profiles SET total_hotel_spend=?,total_restaurant_spend=?,hotel_nights=?,restaurant_visits=?,cohort_tags_json=?,updated_at=? WHERE id=?").bind(hotel,restaurant,hn,rv,JSON.stringify([...new Set([...existing,...cohort])]),now,profile.id).run();detail={amount,department:input.department,customerRef:profile.customer_ref}}
 else if(action==="CREATE_GEO_AUDIENCE"){const name=String(input.name||"").trim(),geoType=String(input.geoType||"");if(name.length<4)throw new Error("Enter a descriptive audience name.");if(!["CITY_ZIP","RADIUS"].includes(geoType))throw new Error("Select a supported geographic targeting type.");const radius=Number(input.radiusMiles||0);if(geoType==="RADIUS"&&(!Number.isFinite(radius)||radius<1||radius>100))throw new Error("Radius must be between 1 and 100 miles.");const postalCodes=String(input.postalCodes||"").split(",").map((x:string)=>x.trim()).filter((x:string)=>/^\d{5}$/.test(x)).slice(0,25);status="DRAFT";await database().prepare("INSERT INTO cdp_geo_audiences VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,c.organizationId,p.id,name,geoType,String(input.city||"").slice(0,100),String(input.state||"").toUpperCase().slice(0,2),JSON.stringify(postalCodes),geoType==="RADIUS"?radius:null,"Consented property marketing audience",status,email,now,now).run();detail={name,geoType,city:input.city,state:input.state,postalCodeCount:postalCodes.length,radiusMiles:geoType==="RADIUS"?radius:null}}
 else if(action==="REQUEST_ACTIVATION"){const profile=await database().prepare("SELECT * FROM cdp_customer_profiles WHERE id=? AND organization_id=? AND property_id=?").bind(input.customerId,c.organizationId,p.id).first<any>();if(!profile)throw new Error("Select a customer in the active property.");if(!profile.marketing_consent||profile.suppressed)throw new Error("Marketing consent is required and the customer must not be suppressed.");const geo=await database().prepare("SELECT * FROM cdp_geo_audiences WHERE id=? AND organization_id=? AND property_id=?").bind(input.geoAudienceId,c.organizationId,p.id).first<any>();if(!geo)throw new Error("Select a geographic audience in the active property.");status="NEEDS_REVIEW";await database().prepare("INSERT INTO cdp_activation_requests VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,c.organizationId,p.id,profile.id,String(input.channel),String(input.activationAction||"ADD_TO_AUDIENCE"),JSON.stringify({cohort:input.cohort,offer:input.offer,geoAudienceId:geo.id,geoAudienceName:geo.name,dryRun:true}),status,"HIGH",null,null,null,null,email,now,now).run();detail={channel:input.channel,customerRef:profile.customer_ref,geoAudience:geo.name,dryRun:true}}
 else if(action==="APPROVE_ACTIVATION"){if(c.role!=="admin")throw new Error("Administrator approval is required.");const request=await database().prepare("SELECT * FROM cdp_activation_requests WHERE id=? AND organization_id=? AND property_id=?").bind(input.id,c.organizationId,p.id).first<any>();if(!request)throw new Error("Activation request not found.");const reason=String(input.reason||"").trim();if(reason.length<8)throw new Error("Enter an approval reason.");id=request.id;status="APPROVED_DRY_RUN";await database().prepare("UPDATE cdp_activation_requests SET status=?,approval_reason=?,approved_by=?,approved_at=?,updated_at=? WHERE id=?").bind(status,reason,email,now,now,id).run();detail={channel:request.channel,execution:"DRY_RUN",reason}}
 else throw new Error("Unsupported customer-intelligence action.");
 await database().prepare("INSERT INTO cdp_audit_events VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),c.organizationId,p.id,email,`CDP_${action}`,"customer_intelligence",id,JSON.stringify(detail),now).run();return{id,status}}
