import { env } from "cloudflare:workers";
import { activeStaffContext } from "./staff";
import { recordSystemAudit } from "./platform-controls";
import { authorizedPropertyScope } from "./property-scope";

const TOPICS = [
  ["weather","Weather","NATIONAL_WEATHER_SERVICE",60,180,"LIVE"],
  ["local_events","Local events","PROVIDER_CONFIGURATION_REQUIRED",360,1440,"CONFIGURATION_REQUIRED"],
  ["labor_market","Regional labor market","FRED_BLS_CONFIGURATION_REQUIRED",1440,10080,"CONFIGURATION_REQUIRED"],
  ["economic_index","Regional economic indicators","FRED_CONFIGURATION_REQUIRED",1440,10080,"CONFIGURATION_REQUIRED"],
  ["road_closures","Road closures","KDOT_PROVIDER_CONFIGURATION_REQUIRED",60,180,"CONFIGURATION_REQUIRED"],
] as const;

const AUTHORITY = [
  ["front-desk","ANSWER_PROPERTY_QUESTIONS","Answer verified property, amenity and policy questions.","AUTONOMOUS",1,["weather","local_events"]],
  ["front-desk","PREPARE_GUEST_RESPONSE","Prepare a guest response using authorized stay context.","AUTONOMOUS",1,["weather","local_events"]],
  ["front-desk","ISSUE_REFUND","Prepare refund evidence; a human authorizes the financial action.","PROPOSE_ONLY",0,[]],
  ["front-desk","EMERGENCY_RESPONSE","Route an emergency to a trained human and emergency services.","HUMAN_REQUIRED",0,[]],
  ["housekeeping-coordinator","PREPARE_ROOM_ASSIGNMENTS","Prepare room-turn assignments from verified occupancy and staffing.","AUTONOMOUS",1,[]],
  ["housekeeping-coordinator","INSPECT_PHYSICAL_ROOM","Prepare inspection guidance; a person performs or confirms physical inspection.","HUMAN_REQUIRED",0,[]],
  ["maintenance-dispatcher","TRIAGE_WORK_ORDER","Classify and route a non-emergency work request.","AUTONOMOUS",1,["weather"]],
  ["maintenance-dispatcher","LIFE_SAFETY_SHUTDOWN","Escalate a life-safety condition; a qualified human controls shutdown/return-to-service.","HUMAN_REQUIRED",0,[]],
  ["compliance-inspector","PREPARE_COMPLIANCE_EVIDENCE","Prepare due-item evidence and exception summaries.","AUTONOMOUS",1,[]],
  ["compliance-inspector","LEGAL_SIGN_OFF","Prepare the record but never provide legal/regulatory sign-off.","HUMAN_REQUIRED",0,[]],
  ["inventory-planner","PROPOSE_PURCHASE_ORDER","Prepare a purchase recommendation from verified counts and par levels.","PROPOSE_ONLY",1,[]],
  ["procurement-analyst","APPROVE_VENDOR_COMMITMENT","Prepare comparison evidence; a human approves the commitment.","PROPOSE_ONLY",0,[]],
  ["review-manager","PREPARE_SERVICE_RECOVERY","Create a private service-recovery task from guest feedback.","AUTONOMOUS",1,[]],
  ["review-manager","PUBLISH_PUBLIC_RESPONSE","Draft a public response; publishing remains approved.","PROPOSE_ONLY",0,[]],
  ["social-media-manager","PREPARE_CAMPAIGN","Prepare cited organic/paid campaign recommendations.","AUTONOMOUS",1,["weather","local_events","economic_index"]],
  ["social-media-manager","PUBLIC_PUBLISHING_OR_AD_SPEND","Prepare a publish/spend request; never execute without approval and credentials.","PROPOSE_ONLY",0,[]],
  ["revenue-analyst","PROPOSE_RATE","Prepare a governed rate recommendation from fresh authorized signals.","PROPOSE_ONLY",1,["weather","local_events","economic_index"]],
  ["tax-preparation","PREPARE_TAX_WORKPAPER","Prepare cited tax workpapers for review.","AUTONOMOUS",1,[]],
  ["tax-preparation","FILE_TAX_RETURN","A named human signs and files the return.","HUMAN_REQUIRED",0,[]],
  ["executive-briefing","PREPARE_EXECUTIVE_BRIEFING","Aggregate authorized cross-department facts and exceptions.","AUTONOMOUS",1,["weather","local_events","labor_market","economic_index"]],
  ["assistant-general-manager","PREPARE_SHIFT_AUDIT","Prepare shift handoff and exception audit.","AUTONOMOUS",1,[]],
  ["website-manager","PREPARE_WEBSITE_CHANGE","Prepare verified content and preview changes.","AUTONOMOUS",1,["local_events"]],
  ["website-manager","PUBLIC_WEBSITE_PUBLISH","Publish only after approval and connector verification.","PROPOSE_ONLY",0,[]],
] as const;

function db(){if(!env.DB)throw new Error("Digital Employee authority storage is unavailable.");return env.DB;}

async function property(c:{organizationId:string;email:string},requested?:string|null){return (await authorizedPropertyScope(c.email,requested))?.property||null;}

async function seed(c:{organizationId:string}){const now=new Date().toISOString();for(const[t,n,s,r,f,status]of TOPICS)await db().prepare(`INSERT INTO external_signal_topics(id,organization_id,topic_key,display_name,source_connector,refresh_cadence_minutes,freshness_limit_minutes,status,last_published_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NULL,?,?) ON CONFLICT(organization_id,topic_key) DO UPDATE SET display_name=excluded.display_name,source_connector=excluded.source_connector,refresh_cadence_minutes=excluded.refresh_cadence_minutes,freshness_limit_minutes=excluded.freshness_limit_minutes,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),c.organizationId,t,n,s,r,f,status,now,now).run();for(const[role,key,description,level,reversible,topics]of AUTHORITY)await db().prepare(`INSERT INTO digital_employee_authority_definitions(id,organization_id,role_key,capability_key,description,autonomy_level,reversible,required_signal_topics_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?, 'ACTIVE',?,?) ON CONFLICT(organization_id,role_key,capability_key) DO UPDATE SET description=excluded.description,required_signal_topics_json=excluded.required_signal_topics_json,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),c.organizationId,role,key,description,level,reversible,JSON.stringify(topics),now,now).run();}

export async function digitalEmployeeAuthorityCenter(email:string,requested?:string|null){const c=await activeStaffContext(email);if(!c)return null;const p=await property(c,requested);if(!p)return null;await seed(c);const now=new Date();const[definitions,topics,subscriptions,events,actions]=await Promise.all([db().prepare(`SELECT * FROM digital_employee_authority_definitions WHERE organization_id=? AND status!='RETIRED' ORDER BY role_key,capability_key`).bind(c.organizationId).all(),db().prepare(`SELECT * FROM external_signal_topics WHERE organization_id=? ORDER BY display_name`).bind(c.organizationId).all(),db().prepare(`SELECT s.*,t.topic_key,t.display_name FROM external_signal_subscriptions s JOIN external_signal_topics t ON t.id=s.topic_id WHERE s.organization_id=? ORDER BY s.role_key,t.display_name`).bind(c.organizationId).all(),db().prepare(`SELECT e.*,t.topic_key,t.display_name,t.freshness_limit_minutes FROM external_signal_events e JOIN external_signal_topics t ON t.id=e.topic_id WHERE e.organization_id=? AND e.property_id=? ORDER BY e.published_at DESC LIMIT 100`).bind(c.organizationId,p.id).all(),db().prepare(`SELECT a.*,d.capability_key,d.description FROM digital_employee_authority_actions a JOIN digital_employee_authority_definitions d ON d.id=a.authority_definition_id WHERE a.organization_id=? AND a.property_id=? ORDER BY a.created_at DESC LIMIT 100`).bind(c.organizationId,p.id).all()]);const topicRows=(topics.results as any[]).map(t=>{const latest=(events.results as any[]).find(e=>e.topic_id===t.id);const age=latest?Math.max(0,(now.getTime()-new Date(latest.published_at).getTime())/60000):null;return{...t,freshness:age===null?"UNAVAILABLE":age<=t.freshness_limit_minutes?"FRESH":"STALE",ageMinutes:age===null?null:Math.round(age)}});return{role:c.role,property:p,definitions:definitions.results,topics:topicRows,subscriptions:subscriptions.results,events:events.results,actions:actions.results,safety:{irreversibleAutonomousImpossible:true,missingSignalsNeverInvented:true,publicFinancialEmploymentActionsApprovalGated:true}};}

export async function saveAuthorityDefinition(email:string,input:Record<string,unknown>){const c=await activeStaffContext(email);if(!c||c.role!=="admin")return null;await seed(c);const id=String(input.id||"");const level=String(input.autonomyLevel||"").toUpperCase();const row=await db().prepare(`SELECT * FROM digital_employee_authority_definitions WHERE id=? AND organization_id=?`).bind(id,c.organizationId).first<any>();if(!row)throw new Error("Authority definition was not found.");if(!row.reversible&&level==="AUTONOMOUS")throw new Error("Irreversible actions can never be autonomous.");if(!["AUTONOMOUS","PROPOSE_ONLY","HUMAN_REQUIRED"].includes(level))throw new Error("Choose a valid autonomy level.");const now=new Date().toISOString();await db().prepare(`UPDATE digital_employee_authority_definitions SET autonomy_level=?,updated_at=? WHERE id=? AND organization_id=?`).bind(level,now,id,c.organizationId).run();await recordSystemAudit({organizationId:c.organizationId,eventType:"DIGITAL_EMPLOYEE_AUTHORITY_CHANGED",entityType:"AUTHORITY_DEFINITION",entityId:id,authorType:"USER",authorId:c.email,correlationId:crypto.randomUUID(),before:{autonomyLevel:row.autonomy_level},after:{autonomyLevel:level},delta:{roleKey:row.role_key,capabilityKey:row.capability_key}});return{id,autonomyLevel:level};}

export async function subscribeSignal(email:string,input:Record<string,unknown>){const c=await activeStaffContext(email);if(!c||c.role!=="admin")return null;await seed(c);const roleKey=String(input.roleKey||"").trim(),topicKey=String(input.topicKey||"").trim();const topic=await db().prepare(`SELECT id FROM external_signal_topics WHERE organization_id=? AND topic_key=?`).bind(c.organizationId,topicKey).first<any>();if(!roleKey||!topic)throw new Error("Choose a role and signal topic.");const now=new Date().toISOString(),active=input.active===false?0:1,id=crypto.randomUUID();await db().prepare(`INSERT INTO external_signal_subscriptions(id,organization_id,role_key,topic_id,active,subscribed_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(organization_id,role_key,topic_id) DO UPDATE SET active=excluded.active,subscribed_by=excluded.subscribed_by,updated_at=excluded.updated_at`).bind(id,c.organizationId,roleKey,topic.id,active,c.email,now,now).run();await recordSystemAudit({organizationId:c.organizationId,eventType:"EXTERNAL_SIGNAL_SUBSCRIPTION_CHANGED",entityType:"SIGNAL_SUBSCRIPTION",entityId:id,authorType:"USER",authorId:c.email,correlationId:id,delta:{roleKey,topicKey,active:Boolean(active)}});return{roleKey,topicKey,active:Boolean(active)};}

export async function publishSyntheticSignal(email:string,input:Record<string,unknown>){const c=await activeStaffContext(email);if(!c||c.role!=="admin")return null;const p=await property(c);if(!p)return null;await seed(c);const topicKey=String(input.topicKey||"").trim(),summary=String(input.summary||"").trim().slice(0,500);const topic=await db().prepare(`SELECT id FROM external_signal_topics WHERE organization_id=? AND topic_key=?`).bind(c.organizationId,topicKey).first<any>();if(!topic||!summary)throw new Error("Topic and a clearly labeled UAT summary are required.");const now=new Date().toISOString(),id=crypto.randomUUID();await db().prepare(`INSERT INTO external_signal_events(id,organization_id,property_id,topic_id,effective_at,expires_at,payload_json,source_reference,confidence,synthetic,published_at) VALUES(?,?,?,?,?,NULL,?,'AAIQ_SYNTHETIC_UAT',1,1,?)`).bind(id,c.organizationId,p.id,topic.id,now,JSON.stringify({summary,label:"SYNTHETIC UAT — NOT LIVE"}),now).run();await db().prepare(`UPDATE external_signal_topics SET last_published_at=?,updated_at=? WHERE id=?`).bind(now,now,topic.id).run();await recordSystemAudit({organizationId:c.organizationId,propertyId:p.id,eventType:"SYNTHETIC_SIGNAL_PUBLISHED",entityType:"EXTERNAL_SIGNAL_EVENT",entityId:id,authorType:"USER",authorId:c.email,correlationId:id,delta:{topicKey,synthetic:true,summary}});return{id,topicKey,synthetic:true};}
