import{env}from"cloudflare:workers";import{activeStaffContext}from"./staff";import{authorizedPropertyScope}from"./property-scope";
function db():D1Database{if(!env.DB)throw new Error("Growth platform storage unavailable.");return env.DB}
async function ensure(){db();}
const providers=["GOOGLE_BUSINESS","TRIPADVISOR","FACEBOOK","INSTAGRAM","BOOKING_COM","EXPEDIA","WYNDHAM","GOOGLE_ADS","META_ADS","OPERA_OHIP"];
export async function growthCenter(email:string){const c=await activeStaffContext(email);if(!c)return null;await ensure();const property=(await authorizedPropertyScope(email))?.property||null;const [vault,content,segments,updates,events,internal]=await Promise.all([
 property?db().prepare("SELECT id,provider,account_label,credential_type,scopes_json,status,last_sync_at,last_error,created_at,updated_at FROM integration_credential_vault WHERE organization_id=? AND property_id=? ORDER BY provider").bind(c.organizationId,property.id).all():Promise.resolve({results:[]}),
 property?db().prepare("SELECT * FROM marketing_content_items WHERE organization_id=? AND property_id=? ORDER BY created_at DESC LIMIT 100").bind(c.organizationId,property.id).all():Promise.resolve({results:[]}),
 property?db().prepare("SELECT * FROM audience_segments WHERE organization_id=? AND property_id=? ORDER BY created_at DESC LIMIT 100").bind(c.organizationId,property.id).all():Promise.resolve({results:[]}),
 property?db().prepare("SELECT * FROM platform_profile_updates WHERE organization_id=? AND property_id=? ORDER BY created_at DESC LIMIT 100").bind(c.organizationId,property.id).all():Promise.resolve({results:[]}),
 property?db().prepare("SELECT event_type,source,COUNT(*) count,MAX(occurred_at) latest FROM guest_behavior_events WHERE organization_id=? AND property_id=? AND consent_status='GRANTED' GROUP BY event_type,source").bind(c.organizationId,property.id).all():Promise.resolve({results:[]}),
 property?db().prepare(`SELECT fact_type,SUM(numeric_value) value,MAX(unit) unit,COUNT(*) records FROM report_facts WHERE organization_id=? AND property_id=? AND occurred_at>=datetime('now','-30 days') GROUP BY fact_type`).bind(c.organizationId,property.id).all():Promise.resolve({results:[]})
]);let weather:any=null;try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),3500);const points=await fetch("https://api.weather.gov/points/38.8403,-97.6114",{headers:{"user-agent":"AAIQ Enterprise pilot contact@mukeshmp.com","accept":"application/geo+json"},signal:controller.signal});const point=await points.json()as any;if(point?.properties?.forecast){const forecast=await fetch(point.properties.forecast,{headers:{"user-agent":"AAIQ Enterprise pilot contact@mukeshmp.com","accept":"application/geo+json"},signal:controller.signal}),body=await forecast.json()as any;weather=(body?.properties?.periods||[]).slice(0,6).map((x:any)=>({name:x.name,temperature:x.temperature,unit:x.temperatureUnit,wind:x.windSpeed,summary:x.shortForecast,source:"National Weather Service",updated:body.properties.updated}))}clearTimeout(timer)}catch{/* external intelligence is explicitly degradable */}const internalRows=internal.results as any[],critical=Number(internalRows.find(x=>x.fact_type==="operational-task")?.value||0);const recommendations=[weather?.some((x:any)=>/storm|rain|snow|ice/i.test(x.summary))?"Weather demand signal: prepare flexible arrival messaging and review covered-arrival operations.":"No material weather disruption appears in the current NWS outlook.",critical>10?"Operational workload is elevated; avoid promotions that add service complexity until urgent work falls.":"Operational workload can support normal direct-booking and local-demand campaigns."];return{role:c.role,property,providers,vault:vault.results,content:content.results,segments:segments.results,updates:updates.results,behavior:events.results,marketIntelligence:{internal:internalRows,weather:weather||[],recommendations,sources:[{name:"AAIQ canonical report facts",status:"LIVE",scope:"Active property · trailing 30 days"},{name:"National Weather Service",status:weather?"LIVE":"TEMPORARILY_UNAVAILABLE",scope:"Salina forecast"},{name:"FRED regional economy",status:"CREDENTIAL_REQUIRED",scope:"API key required"},{name:"EIA commercial energy",status:"CREDENTIAL_REQUIRED",scope:"API key required"}]}};}
export async function saveVaultCredential(email:string,input:any,encrypted:string){const c=await activeStaffContext(email);if(!c||c.role!=="admin")return null;await ensure();const property=(await authorizedPropertyScope(email))?.property;if(!property)return null;const provider=String(input.provider||"").toUpperCase();if(!providers.includes(provider))throw new Error("Select a supported provider.");const label=String(input.accountLabel||"Primary account").slice(0,120),now=new Date().toISOString(),id=crypto.randomUUID();
 await db().batch([db().prepare(`INSERT INTO integration_credential_vault(id,organization_id,provider,account_label,credential_type,encrypted_secret,scopes_json,status,last_sync_at,last_error,created_by,created_at,updated_at,property_id) VALUES (?,?,?,?,?,?,?,'CREDENTIALS_SAVED',NULL,NULL,?,?,?,?) ON CONFLICT(organization_id,provider,account_label) DO UPDATE SET property_id=excluded.property_id,credential_type=excluded.credential_type,encrypted_secret=excluded.encrypted_secret,scopes_json=excluded.scopes_json,status='CREDENTIALS_SAVED',last_error=NULL,updated_at=excluded.updated_at`).bind(id,c.organizationId,provider,label,String(input.credentialType||"API_KEY"),encrypted,JSON.stringify(input.scopes||[]),email,now,now,property.id),
 db().prepare("INSERT INTO growth_platform_audit(id,organization_id,actor_email,event_type,entity_type,entity_id,detail_json,created_at,property_id) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),c.organizationId,email,"CREDENTIAL_ROTATED","integration",id,JSON.stringify({provider,label}),now,property.id)]);return{provider,label,status:"CREDENTIALS_SAVED"};}
export async function createGrowthRecord(email:string,input:any){const c=await activeStaffContext(email);if(!c||c.role!=="admin")return null;await ensure();const property=(await authorizedPropertyScope(email))?.property;if(!property)return null;const now=new Date().toISOString(),id=crypto.randomUUID(),kind=String(input.kind);
 if(kind==="CONTENT")await db().prepare(`INSERT INTO marketing_content_items(id,organization_id,title,content_type,body,media_url,channels_json,status,scheduled_at,approval_required,approved_by,created_by,created_at,updated_at,property_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,c.organizationId,String(input.title).slice(0,160),String(input.contentType||"POST"),String(input.body||"").slice(0,10000),input.mediaUrl||null,JSON.stringify(input.channels||[]),"DRAFT",input.scheduledAt||null,1,null,email,now,now,property.id).run();
 else if(kind==="SEGMENT")await db().prepare(`INSERT INTO audience_segments(id,organization_id,name,rule_json,channel,offer_title,offer_url,status,created_by,created_at,property_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(id,c.organizationId,String(input.name).slice(0,160),JSON.stringify(input.rule||{}),String(input.channel||"SMS"),String(input.offerTitle||"").slice(0,180),String(input.offerUrl||"").slice(0,1000),"DRAFT",email,now,property.id).run();
 else if(kind==="PROFILE_UPDATE")await db().prepare(`INSERT INTO platform_profile_updates(id,organization_id,title,description,photo_url,platforms_json,status,approved_by,created_by,created_at,property_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(id,c.organizationId,String(input.title||"Property profile update").slice(0,160),String(input.description||"").slice(0,5000),input.photoUrl||null,JSON.stringify(input.platforms||[]),"PENDING_APPROVAL",null,email,now,property.id).run();
 else throw new Error("Unsupported growth action.");
 await db().prepare("INSERT INTO growth_platform_audit(id,organization_id,actor_email,event_type,entity_type,entity_id,detail_json,created_at,property_id) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),c.organizationId,email,`${kind}_CREATED`,kind.toLowerCase(),id,JSON.stringify({approvalRequired:true}),now,property.id).run();return{id,status:kind==="PROFILE_UPDATE"?"PENDING_APPROVAL":"DRAFT"};}
export async function updateVaultConnection(email:string,id:string,action:string,secretValid=false){const c=await activeStaffContext(email);if(!c||c.role!=="admin")return null;await ensure();const property=(await authorizedPropertyScope(email))?.property;if(!property)return null;const now=new Date().toISOString(),status=action==="DISABLE"?"DISABLED":action==="VALIDATE"&&secretValid?"CONFIG_VALIDATED":"CREDENTIALS_SAVED";await db().batch([db().prepare("UPDATE integration_credential_vault SET status=?,last_error=?,updated_at=? WHERE id=? AND organization_id=? AND property_id=?").bind(status,action==="VALIDATE"&&!secretValid?"Encrypted credential could not be validated.":null,now,id,c.organizationId,property.id),db().prepare("INSERT INTO growth_platform_audit(id,organization_id,actor_email,event_type,entity_type,entity_id,detail_json,created_at,property_id) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),c.organizationId,email,`CREDENTIAL_${action}`,"integration",id,JSON.stringify({status}),now,property.id)]);return{id,status};}
export async function encryptedVaultSecret(email:string,id:string){const c=await activeStaffContext(email);if(!c||c.role!=="admin")return null;await ensure();const property=(await authorizedPropertyScope(email))?.property;if(!property)return null;return db().prepare("SELECT encrypted_secret FROM integration_credential_vault WHERE id=? AND organization_id=? AND property_id=?").bind(id,c.organizationId,property.id).first<{encrypted_secret:string}>();}
