/* eslint-disable @typescript-eslint/no-explicit-any */
import { env } from "cloudflare:workers";
import { activeStaffContext } from "./staff";
import { recordSystemAudit } from "./platform-controls";
import { authorizedPropertyScope } from "./property-scope";

function db():D1Database { if(!env.DB)throw new Error("Workforce Lifecycle storage is unavailable.");return env.DB; }
const clean=(value:any,max=1000)=>String(value??"").trim().slice(0,max);
async function property(context:any){return (await authorizedPropertyScope(context.email))?.property||null;}

const templates=[
  ["FRONT_DESK","Front Desk",["AAIQ_DIGITAL_FRONT_DESK:OPERATE","AAIQ_COMMUNICATION_CENTER:RESPOND","AAIQ_TIME_MANAGEMENT:SELF"],["UNIFORM","KEY_OR_BADGE"]],
  ["HOUSEKEEPING","Housekeeping",["AAIQ_HOUSEKEEPING:OPERATE","AAIQ_VIDEO_INTELLIGENCE:CAPTURE","AAIQ_TIME_MANAGEMENT:SELF"],["UNIFORM","KEY_OR_BADGE"]],
  ["MAINTENANCE","Maintenance",["AAIQ_MAINTENANCE:OPERATE","AAIQ_ASSET_REGISTRY:UPDATE","AAIQ_TIME_MANAGEMENT:SELF"],["UNIFORM","KEY_OR_BADGE","TOOL_KIT"]],
  ["MANAGER","Property Manager",["AAIQ_REPORTING:READ","AAIQ_ACTION_CENTER:APPROVE","AAIQ_USER_MANAGEMENT:MANAGE"],["KEY_OR_BADGE","PHONE_OR_TABLET"]],
] as const;
const targets=[["CAREER_SITE","AAIQ Careers / Google JobPosting"],["FACEBOOK","Facebook Page"],["INSTAGRAM","Instagram Business"],["LINKEDIN","LinkedIn Jobs"],["INDEED","Indeed"]] as const;

async function seed(context:any,p:any){const now=new Date().toISOString();for(const [code,name,access,custody] of templates)await db().prepare(`INSERT OR IGNORE INTO workforce_role_templates VALUES(?,?,?,?,?,?,1,?,?)`).bind(crypto.randomUUID(),context.organizationId,code,name,JSON.stringify(access),JSON.stringify(custody),now,now).run();for(const [key,name] of targets)await db().prepare(`INSERT OR IGNORE INTO workforce_publishing_targets VALUES(?,?,?,?,?,'CREDENTIALS_REQUIRED',1,NULL)`).bind(crypto.randomUUID(),context.organizationId,p.id,key,name).run();}

export async function workforceLifecycleCenter(email:string){const context=await activeStaffContext(email);if(!context)return null;const p=await property(context);if(!p)return null;await seed(context,p);const [templatesResult,requisitions,onboarding,locker,custody,separations,actions,targetsResult,publications,employees]=await Promise.all([
  db().prepare("SELECT * FROM workforce_role_templates WHERE organization_id=? ORDER BY display_name").bind(context.organizationId).all(),
  db().prepare("SELECT * FROM workforce_job_requisitions WHERE organization_id=? AND property_id=? ORDER BY created_at DESC").bind(context.organizationId,p.id).all(),
  db().prepare("SELECT * FROM workforce_onboarding_cases WHERE organization_id=? AND property_id=? ORDER BY created_at DESC").bind(context.organizationId,p.id).all(),
  db().prepare("SELECT * FROM workforce_access_locker WHERE organization_id=? AND property_id=? ORDER BY employee_email,resource_type,resource_name").bind(context.organizationId,p.id).all(),
  db().prepare("SELECT * FROM workforce_property_custody WHERE organization_id=? AND property_id=? ORDER BY issued_at DESC").bind(context.organizationId,p.id).all(),
  db().prepare("SELECT * FROM workforce_separation_cases WHERE organization_id=? AND property_id=? ORDER BY created_at DESC").bind(context.organizationId,p.id).all(),
  db().prepare("SELECT * FROM workforce_employee_actions WHERE organization_id=? AND property_id=? ORDER BY created_at DESC").bind(context.organizationId,p.id).all(),
  db().prepare("SELECT * FROM workforce_publishing_targets WHERE organization_id=? AND property_id=? ORDER BY display_name").bind(context.organizationId,p.id).all(),
  db().prepare("SELECT d.* FROM workforce_job_publication_drafts d JOIN workforce_job_requisitions r ON r.id=d.requisition_id WHERE r.organization_id=? AND r.property_id=? ORDER BY d.created_at DESC").bind(context.organizationId,p.id).all(),
  db().prepare(`SELECT DISTINCT m.user_email,m.display_name,m.role,m.status FROM staff_members m JOIN property_assignments a ON a.organization_id=m.organization_id AND lower(a.user_email)=lower(m.user_email) WHERE m.organization_id=? AND a.property_id=? ORDER BY m.display_name`).bind(context.organizationId,p.id).all(),
]);return{role:context.role,property:p,templates:templatesResult.results,requisitions:requisitions.results,onboarding:onboarding.results,locker:locker.results,custody:custody.results,separations:separations.results,actions:actions.results,targets:targetsResult.results,publications:publications.results,employees:employees.results};}

export async function workforceLifecycleAction(email:string,input:any){const context=await activeStaffContext(email);if(!context)return null;const p=await property(context);if(!p)return null;const action=clean(input.action,60),now=new Date().toISOString();
 if(action==="CREATE_REQUISITION"){const title=clean(input.title,140),department=clean(input.department,80).toUpperCase();if(title.length<3)throw new Error("Enter a job title.");const description=clean(input.description,5000)||`${title} at ${p.name}. The role supports ${department.toLowerCase().replaceAll('_',' ')} operations, guest service, safety, accurate records, teamwork, and AAIQ-assisted workflows. Candidates must follow property policies, protect guest information, and complete role training.`;const id=crypto.randomUUID();await db().prepare("INSERT INTO workforce_job_requisitions VALUES(?,?,?,?,?,?,'DRAFT','PENDING',?,?,?)").bind(id,context.organizationId,p.id,title,department,description,email,now,now).run();for(const target of targets)await db().prepare("INSERT INTO workforce_job_publication_drafts VALUES(?,?,?,?, 'DRAFT','PENDING',NULL,NULL,?,?)").bind(crypto.randomUUID(),id,target[0],JSON.stringify({title,description,property:p.name,address:p.address,approvalRequired:true}),now,now).run();await audit(context,p,"WORKFORCE_REQUISITION_PREPARED","JOB_REQUISITION",id,{title,department,publicationDrafts:targets.length,externalPosts:0});return{id,status:"PENDING_APPROVAL",externalPosts:0};}
 if(action==="START_ONBOARDING"){const employee=clean(input.employeeEmail,240).toLowerCase(),roleCode=clean(input.roleCode,80).toUpperCase();if(!/^\S+@\S+\.\S+$/.test(employee))throw new Error("Enter a valid employee email.");const template=await db().prepare("SELECT * FROM workforce_role_templates WHERE organization_id=? AND role_code=?").bind(context.organizationId,roleCode).first<any>();if(!template)throw new Error("Select a role template.");const id=crypto.randomUUID();await db().prepare("INSERT INTO workforce_onboarding_cases VALUES(?,?,?,?,?,'PREPARING',NULL,NULL,?,?)").bind(id,context.organizationId,p.id,employee,roleCode,now,now).run();for(const entry of JSON.parse(template.access_blueprint_json)){const [name,level]=String(entry).split(':');await db().prepare("INSERT OR IGNORE INTO workforce_access_locker VALUES(?,?,?,?,?,?,?,?,NULL,NULL,NULL)").bind(crypto.randomUUID(),context.organizationId,p.id,employee,"DIGITAL_ACCESS",name,level||"OPERATE","PLANNED").run();}for(const type of JSON.parse(template.custody_blueprint_json))await db().prepare("INSERT INTO workforce_property_custody VALUES(?,?,?,?,?,?,'PLANNED',?,NULL,NULL)").bind(crypto.randomUUID(),context.organizationId,p.id,employee,type,`TO_ASSIGN-${crypto.randomUUID().slice(0,8)}`,now).run();await audit(context,p,"WORKFORCE_ONBOARDING_PREPARED","ONBOARDING_CASE",id,{employee,roleCode,accessTemplateApplied:true,credentialsInvented:false});return{id,status:"PREPARING",next:"Collect profile, consent and provider credentials; planned access remains inactive."};}
 if(action==="CREATE_EMPLOYEE_ACTION"){const employee=clean(input.employeeEmail,240).toLowerCase(),type=clean(input.actionType,80).toUpperCase(),summary=clean(input.summary,4000);if(!employee||summary.length<10)throw new Error("Select an employee and enter factual details.");const allowed=["COACHING","CORRECTIVE_ACTION","WRITTEN_WARNING","FINAL_WARNING","TERMINATION_RECOMMENDATION"];if(!allowed.includes(type))throw new Error("Select a supported action type.");const id=crypto.randomUUID();await db().prepare("INSERT INTO workforce_employee_actions VALUES(?,?,?,?,?,?,?,'[]','DRAFT','PENDING',NULL,?,NULL,?,?)").bind(id,context.organizationId,p.id,employee,type,summary,clean(input.policyReference,200)||null,email,now,now).run();await audit(context,p,"WORKFORCE_DOCUMENT_DRAFTED","EMPLOYEE_ACTION",id,{employee,type,humanDecisionRequired:true});return{id,status:"PENDING_APPROVAL"};}
 if(action==="PREPARE_SEPARATION"){if(context.role!=="admin")return null;const employee=clean(input.employeeEmail,240).toLowerCase();const member=await db().prepare("SELECT role,status FROM staff_members WHERE organization_id=? AND lower(user_email)=?").bind(context.organizationId,employee).first<any>();if(!member)throw new Error("Employee was not found.");if(member.role==="admin")throw new Error("A protected administrator cannot be separated here. Transfer administrator authority first.");const id=crypto.randomUUID(),effective=clean(input.effectiveAt,40)||now;await db().prepare("INSERT INTO workforce_separation_cases VALUES(?,?,?,?,?,'PREPARED','PENDING','PENDING',NULL,?,?)").bind(id,context.organizationId,p.id,employee,effective,now,now).run();const resources=await db().prepare("SELECT resource_type,resource_name FROM workforce_access_locker WHERE organization_id=? AND property_id=? AND employee_email=? AND status!='REVOKED'").bind(context.organizationId,p.id,employee).all<any>();for(const row of resources.results)await db().prepare("INSERT INTO workforce_offboarding_tasks VALUES(?,?,?,?, 'MANUAL_PROVIDER_ACTION','OPEN',NULL,NULL,'{}')").bind(crypto.randomUUID(),id,"REVOKE_ACCESS",`${row.resource_type}:${row.resource_name}`).run();await audit(context,p,"WORKFORCE_SEPARATION_PREPARED","SEPARATION_CASE",id,{employee,externalRevocations:resources.results.length,accessChanged:false});return{id,status:"PREPARED",warning:"No access changed until an administrator approves execution."};}
 if(action==="APPROVE_SEPARATION"){if(context.role!=="admin")return null;const id=clean(input.id,100),row=await db().prepare("SELECT * FROM workforce_separation_cases WHERE id=? AND organization_id=? AND property_id=?").bind(id,context.organizationId,p.id).first<any>();if(!row)throw new Error("Separation case not found.");await db().batch([db().prepare("UPDATE staff_members SET status='suspended' WHERE organization_id=? AND lower(user_email)=?").bind(context.organizationId,row.employee_email),db().prepare("UPDATE property_assignments SET status='INACTIVE' WHERE organization_id=? AND property_id=? AND lower(user_email)=?").bind(context.organizationId,p.id,row.employee_email),db().prepare("UPDATE workforce_access_locker SET status=CASE WHEN resource_name LIKE 'AAIQ_%' THEN 'REVOKED' ELSE 'REVOCATION_REQUIRED' END,revoked_at=CASE WHEN resource_name LIKE 'AAIQ_%' THEN ? ELSE revoked_at END WHERE organization_id=? AND property_id=? AND employee_email=?").bind(now,context.organizationId,p.id,row.employee_email),db().prepare("UPDATE workforce_separation_cases SET status='ACCESS_SUSPENDED',access_revocation_status='PARTIAL_EXTERNAL_ACTION_REQUIRED',approved_by=?,updated_at=? WHERE id=?").bind(email,now,id)]);await audit(context,p,"WORKFORCE_SEPARATION_EXECUTED","SEPARATION_CASE",id,{employee:row.employee_email,aaiqAccessSuspended:true,externalProviderActionsQueued:true});return{id,status:"ACCESS_SUSPENDED",externalProviderActions:"QUEUED_FOR_MANAGEMENT"};}
 throw new Error("Unsupported Workforce Lifecycle action.");}

async function audit(context:any,p:any,eventType:string,entityType:string,entityId:string,delta:any){await recordSystemAudit({organizationId:context.organizationId,propertyId:p.id,eventType,entityType,entityId,authorType:"USER",authorId:context.email,correlationId:crypto.randomUUID(),delta});}
