"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import "./communication-center.css";
import "./master-inbox.css";
import "./master-inbox-certification.css";

export default function CommunicationCenterClient() {
  const [data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null);
  const [source,setSource]=useState("ALL"),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
  async function load(){const r=await fetch("/api/v1/communication-center",{cache:"no-store"});if(r.ok){const d=await r.json();setData(d);setSelected((old:any)=>d.threads.find((t:any)=>t.id===old?.id)||d.threads[0]||null)}}
  useEffect(()=>{void load()},[]);
  async function act(body:any){if(body.action==="CONFIGURE_POLICY"&&body.enabled){const reference=prompt("Enter the legal/privacy review ticket, policy, or counsel reference. It will be written to the audit trail.");if(!reference||!confirm("I attest that the property approved the notice, consent, retention, employee notice, and guest privacy policy for this capture channel."))return false;body={...body,legalReviewReference:reference,attested:true}}setBusy(body.action);setNotice("");const r=await fetch("/api/v1/communication-center",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json();setNotice(r.ok?(x.manualFallback||"Action completed and audited."):x.error||"Action failed.");setBusy("");await load();return r.ok}
  const threads=useMemo(()=>data?.threads?.filter((t:any)=>source==="ALL"||t.source_key===source)||[],[data,source]);
  const messages=data?.messages?.filter((m:any)=>m.thread_id===selected?.id)||[];
  const drafts=data?.drafts?.filter((d:any)=>d.thread_id===selected?.id)||[];
  async function intake(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await act({action:"CREATE_INTAKE",...Object.fromEntries(f)}))e.currentTarget.reset()}
  async function draft(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await act({action:"CREATE_REPLY_DRAFT",threadId:selected.id,body:f.get("body")}))e.currentTarget.reset()}
  return <main className="communication-center">
    <header className="cc-hero"><div><small>AAIQ MASTER INBOX · AAIQ NATIVE COMMUNICATIONS</small><h1>Every conversation, one governed workspace</h1><p>Read, triage and reply across connected email, SMS, website chat, OTA reviews and internal sources. Replies default to the exact account that received the message.</p></div><aside><span>PROPERTY SCOPED</span><strong>{data?.property?.name||"Loading…"}</strong><small>Same-source delivery · override audited</small></aside></header>
    <p className="cc-trust"><strong>Delivery safety</strong><span>Nothing is sent automatically without an approved rule or human action. A different reply channel requires an explicit reason.</span><em>{data?.automation?.status||"LOADING"}</em></p>
    <section className="cc-certification"><header><div><small>ADVERSARIAL LIFECYCLE CERTIFICATION</small><h2>Inbox delivery and policy evidence</h2><p>Tests provider-shaped inbound, threading, duplicate and out-of-order events, unsubscribe, quiet hours, bounce reconciliation, and mandatory approval risks. No real message is sent.</p></div>{data?.role==="admin"&&<button disabled={busy==="RUN_LIFECYCLE_CERTIFICATION"} onClick={()=>void act({action:"RUN_LIFECYCLE_CERTIFICATION"})}>Run certification</button>}</header>{data?.certifications?.length?<div>{data.certifications.map((run:any)=><article key={run.id}><span><strong>{run.status}</strong><small>{run.provider_mode} · {run.passed_cases}/{run.total_cases} passed</small></span><em>{run.production_enabled?"PRODUCTION ENABLED":"MOCK ONLY"}</em><time>{new Date(run.executed_at).toLocaleString()}</time></article>)}</div>:<p className="cc-empty">No lifecycle certification has been run for this property.</p>}</section>
    <section className="cc-metrics">{[["Open",data?.metrics?.open],["Critical",data?.metrics?.critical],["Awaiting approval",data?.metrics?.awaitingApproval],["Sources",data?.sources?.length]].map(([k,v])=><article key={String(k)}><span>{k}</span><strong>{v??"—"}</strong><small>Active property</small></article>)}</section>
    {notice&&<p className="cc-message">{notice}</p>}
    <section className="cc-capture"><header><div><small>CONSENT-GOVERNED CONVERSATION INTELLIGENCE</small><h2>Front desk and phone capture</h2><p>Never always-on. A visible indicator, approved policy, notice and participant consent are required before audio capture. Findings become drafts for review—not silent employee discipline or guest decisions.</p></div><em>{data?.capture?.capabilities?.mediaStorage||"CHECKING STORAGE"}</em></header><div className="cc-capture-grid">{data?.capture?.policies?.map((policy:any)=>{const active=data.capture.sessions.find((x:any)=>x.policy_id===policy.id&&!["ENDED","STOPPED_CONSENT_DECLINED"].includes(x.status));return <article key={policy.id}><span><b>{policy.name}</b><small>{policy.channel.replaceAll('_',' ')}</small></span><p>{policy.notice_text}</p><dl><div><dt>Policy</dt><dd>{policy.enabled?"Enabled":"Disabled"}</dd></div><div><dt>Legal/privacy review</dt><dd>{policy.legal_review_status}</dd></div><div><dt>Retention</dt><dd>{policy.retention_days} days</dd></div><div><dt>Raw audio</dt><dd>{policy.raw_audio_retained?"Retained":"Off"}</dd></div></dl>{data.capture.role==="admin"&&!policy.enabled&&<button onClick={()=>void act({action:"CONFIGURE_POLICY",channel:policy.channel,enabled:true,retentionDays:30,legalReviewStatus:"APPROVED"})}>Record approval & enable</button>}{policy.enabled&&!active&&<button onClick={()=>void act({action:"START_CAPTURE",policyId:policy.id,sourceReference:policy.channel==="PHONE_CALL"?"UCM_CALL_REFERENCE_REQUIRED":"FRONT_DESK_DEVICE"})}>Start with notice</button>}{active?.status==="AWAITING_CONSENT"&&<div className="cc-consent"><strong>Read the notice, then record the response</strong><button onClick={()=>void act({action:"RECORD_CONSENT",id:active.id,response:"CONSENTED",noticeMethod:"AUDIBLE_AND_VISIBLE_NOTICE"})}>Participant consented</button><button onClick={()=>void act({action:"RECORD_CONSENT",id:active.id,response:"DECLINED",noticeMethod:"AUDIBLE_AND_VISIBLE_NOTICE"})}>Participant declined</button></div>}{active?.status==="CAPTURE_READY"&&<button onClick={()=>void act({action:"END_CAPTURE",id:active.id})}>Stop and preserve evidence</button>}</article>})}</div><footer><b>Adapter status:</b> phone calls use a connected Grandstream UCM recording reference or import; an in-person microphone uses an AAIQ secure capture client. Private media storage is required before audio is retained.</footer></section>
    <section className="cc-source-strip"><header><div><small>NAMED SOURCE INBOXES</small><h2>Choose a mailbox or channel</h2></div><a href="/accounts">Connect sources →</a></header>
      <div><button className={source==="ALL"?"selected-source":""} onClick={()=>setSource("ALL")}><i>∞</i><span><b>All conversations</b><small>Unified priority view</small></span></button>{data?.sources?.map((s:any)=><article key={s.source_key}><button onClick={()=>setSource(s.source_key)}><i>{s.source_key.slice(0,2)}</i><span><b>{s.display_name}</b><small>{s.status.replaceAll("_"," ")}</small></span></button>{data.role==="admin"&&<button className="rename" onClick={()=>{const name=prompt("Name this source inbox",s.display_name);if(name)void act({action:"RENAME_SOURCE",sourceKey:s.source_key,displayName:name})}}>Rename</button>}</article>)}</div>
    </section>
    <section className="cc-workspace"><aside><header><small>{source==="ALL"?"UNIFIED INBOX":source}</small><h2>Prioritized conversations</h2><span>{threads.length} visible</span></header><div className="cc-thread-list">{threads.map((t:any)=><button key={t.id} onClick={()=>setSelected(t)} className={selected?.id===t.id?"selected":""}><span><em className={`priority-${t.priority.toLowerCase()}`}>{t.priority}</em><small>{t.source_account}</small></span><b>{t.subject}</b><p>{t.category.replaceAll("_"," ")} · {t.assigned_department}</p><small>{t.status.replaceAll("_"," ")} · {t.confidence}% confidence</small></button>)}</div></aside>
      <article className="cc-detail">{selected?<><header><div><small>{selected.source_key} · {selected.source_account}</small><h2>{selected.subject}</h2><p>{selected.reasoning_summary}</p></div><em>{selected.status.replaceAll("_"," ")}</em></header>
        <section className="cc-transcript"><h3>Conversation</h3>{messages.map((m:any)=><article key={m.id} className={m.direction.toLowerCase()}><small>{m.direction} · {m.sender_label}</small><p>{m.body}</p><time>{new Date(m.received_at).toLocaleString()}</time></article>)}</section>
        <form onSubmit={draft}><small>RESPONSE WORKBENCH</small><h3>Reply from {selected.source_account}</h3><p>The original {selected.source_key} account is selected by default.</p><textarea name="body" required placeholder="Write the response for approval and delivery."/><button disabled={busy==="CREATE_REPLY_DRAFT"}>Create approval draft</button></form>
        {drafts.map((d:any)=><section className="cc-delivery" key={d.id}><b>{d.status.replaceAll("_"," ")}</b><p>{d.body}</p>{data.role==="admin"&&["AWAITING_APPROVAL","APPROVED_MANUAL_SEND"].includes(d.status)&&<><label>Reply channel<select id={`channel-${d.id}`} defaultValue={selected.source_key}>{data.sources.map((s:any)=><option key={s.source_key}>{s.source_key}</option>)}</select></label><label>Reply account<input id={`account-${d.id}`} defaultValue={selected.source_account} aria-label="Reply source account"/></label><label>Override reason<input id={`reason-${d.id}`} placeholder="Required if channel or account changes"/></label><button onClick={()=>void act({action:"SEND_APPROVED_REPLY",id:d.id,sourceKey:(document.getElementById(`channel-${d.id}`) as HTMLSelectElement).value,sourceAccount:(document.getElementById(`account-${d.id}`) as HTMLInputElement).value,overrideReason:(document.getElementById(`reason-${d.id}`) as HTMLInputElement).value})}>Approve & send</button></>}</section>)}
      </>:<div className="cc-empty cc-select"><b>Select a conversation</b></div>}</article>
    </section>
    <section className="cc-intake"><header><div><small>MANUAL FALLBACK</small><h2>Add a message from any source</h2><p>Use when an API is unavailable; it remains classified, reportable and audited.</p></div></header><form onSubmit={intake}><div><label>Source<select name="sourceKey">{data?.sources?.map((s:any)=><option key={s.source_key}>{s.source_key}</option>)}</select></label><label>Source account<input name="sourceAccount" required placeholder="Mailbox, number or profile"/></label><label>Sender<input name="sender" required/></label></div><div><label>Guest/reservation<input name="guestReference"/></label><label>Room<input name="roomReference"/></label><label>Subject<input name="subject" required/></label></div><label>Message<textarea name="body" required/></label><button disabled={busy==="CREATE_INTAKE"}>Save, classify & route</button></form></section>
  </main>;
}
