import{getChatGPTUser}from"../../../chatgpt-auth";import{applyReconciliationPlan,chooseWebsiteOption,createReconciliationPlan,createWebsiteOptionSet,createWebsiteProject,requestDomainConnection,updateWebsiteProject,verifyDomainConnection,websiteFactory}from"../../../../db/website-factory";import{generateWebsiteOptions,narrowToGeneratedOptions}from"../../../server/agents/website-generation-agent";import{cookies}from"next/headers";
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in required."},{status:401});const propertyId=(await cookies()).get("aaiq_active_property")?.value,data=await websiteFactory(user.email,propertyId);return data?Response.json(data,{headers:{"cache-control":"private, no-store"}}):Response.json({error:"Access denied."},{status:403})}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in required."},{status:401});try{const body=await request.json()as any,propertyId=(await cookies()).get("aaiq_active_property")?.value;
  if(body.action==="GENERATE_WEBSITE_OPTIONS"){
    const generated=await generateWebsiteOptions(user.email,{query:String(body.query||""),propertyContextId:propertyId});
    if(!generated)return Response.json({error:"Access denied."},{status:403});
    if(generated.status==="MANUAL_FALLBACK")return Response.json({status:"MANUAL_FALLBACK",runId:generated.runId,message:"The model connection is not configured, or generation failed. The request has been preserved for manual completion in Agent Studio's fallback queue."},{status:202});
    const created=await createWebsiteOptionSet(user.email,{propertyContextId:propertyId,options:narrowToGeneratedOptions(generated.generation),researchUsed:generated.generation.researchUsed,sourcesUsed:generated.generation.sourcesUsed});
    if(!created)return Response.json({error:"Administrator access required."},{status:403});
    return Response.json({status:generated.status,runId:generated.runId,researchUsed:generated.generation.researchUsed,sourcesUsed:generated.generation.sourcesUsed,missingInformation:generated.generation.missingInformation,...created},{status:201});
  }
  if(body.action==="CHOOSE_WEBSITE_OPTION"){const result=await chooseWebsiteOption(user.email,String(body.projectId||""));return result?Response.json(result):Response.json({error:"Administrator access required."},{status:403})}
  if(body.action==="REQUEST_DOMAIN_CONNECTION"){const result=await requestDomainConnection(user.email,{projectId:String(body.projectId||""),domain:String(body.domain||""),targetHostname:String(body.targetHostname||"")});return result?Response.json(result,{status:201}):Response.json({error:"Administrator access required."},{status:403})}
  if(body.action==="VERIFY_DOMAIN_CONNECTION"){const result=await verifyDomainConnection(user.email,String(body.connectionId||""));return result?Response.json(result):Response.json({error:"Administrator access required."},{status:403})}
  const result=body.action==="CREATE_RECONCILIATION_PLAN"?await createReconciliationPlan(user.email,body):body.action==="APPLY_RECONCILIATION_PLAN"?await applyReconciliationPlan(user.email,String(body.planId)):await createWebsiteProject(user.email,body,propertyId);return result?Response.json(result,{status:201}):Response.json({error:"Administrator access required."},{status:403})}catch(error){return Response.json({error:error instanceof Error?error.message:"Website Factory action failed."},{status:409})}}
export async function PATCH(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in required."},{status:401});try{const b=await request.json()as any,result=await updateWebsiteProject(user.email,String(b.id),b);return result?Response.json(result):Response.json({error:"Project not found or access denied."},{status:404})}catch(error){return Response.json({error:error instanceof Error?error.message:"Site update failed."},{status:409})}}
