-- Authoritative Release 68 prerequisites recovered from AAIQ repository history.
-- Sources: d048dbf db/property-workflows.ts; bf4f19c db/property-intelligence.ts;
-- 01eeee9 and 924abd5 db/property-workflows.ts. No inferred columns are included.
CREATE TABLE IF NOT EXISTS operational_work_orders (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT,department TEXT NOT NULL,work_type TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,room_number TEXT,assigned_to TEXT,status TEXT NOT NULL,progress INTEGER NOT NULL DEFAULT 0,priority TEXT NOT NULL,parent_order_id TEXT,due_at TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,completed_at TEXT);
CREATE TABLE IF NOT EXISTS work_order_attachments (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT,work_order_id TEXT NOT NULL,object_key TEXT NOT NULL,file_name TEXT NOT NULL,content_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,uploaded_by TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS maintenance_compliance_templates (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT,code TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL,frequency TEXT NOT NULL,required_evidence TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,next_due_at TEXT NOT NULL,UNIQUE(organization_id,code));
CREATE TABLE IF NOT EXISTS supply_inventory (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,sku TEXT NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,quantity INTEGER NOT NULL,reorder_threshold INTEGER NOT NULL,target_quantity INTEGER NOT NULL,unit_cost_cents INTEGER NOT NULL,updated_at TEXT NOT NULL,UNIQUE(organization_id,sku));
CREATE TABLE IF NOT EXISTS work_order_steps (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT,work_order_id TEXT NOT NULL,step_number INTEGER NOT NULL,instruction TEXT NOT NULL,safety_note TEXT,completed INTEGER NOT NULL DEFAULT 0,completed_by TEXT,completed_at TEXT,UNIQUE(work_order_id,step_number));
CREATE TABLE IF NOT EXISTS night_room_report_imports (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT,object_key TEXT NOT NULL,file_name TEXT NOT NULL,rooms_read INTEGER NOT NULL,assignments_created INTEGER NOT NULL,imported_by TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS work_evidence_reviews (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT,work_order_id TEXT NOT NULL,attachment_id TEXT NOT NULL UNIQUE,evidence_area TEXT NOT NULL,evidence_stage TEXT NOT NULL,review_status TEXT NOT NULL,quality_score INTEGER,deficiencies_json TEXT NOT NULL,provider_label TEXT NOT NULL,reviewer_email TEXT,reviewer_note TEXT,reviewed_at TEXT,created_at TEXT NOT NULL);
