-- AAIQ Intelligent Document Vault. Independent of HNE repositories and schemas.
CREATE TABLE IF NOT EXISTS document_records(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,correlation_id TEXT NOT NULL,title TEXT NOT NULL,document_type TEXT NOT NULL,status TEXT NOT NULL,source_type TEXT NOT NULL,source_record_type TEXT,source_record_id TEXT,department TEXT,guest_reference TEXT,room_reference TEXT,current_version_id TEXT,classification_confidence REAL,classification_evidence TEXT,retention_policy_id TEXT,retention_until TEXT,legal_hold_count INTEGER NOT NULL DEFAULT 0,sensitivity TEXT NOT NULL DEFAULT 'INTERNAL',external_system TEXT,external_entity_type TEXT,external_entity_id TEXT,external_sync_status TEXT NOT NULL DEFAULT 'NOT_CONFIGURED',created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_blobs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,document_id TEXT NOT NULL,object_key TEXT NOT NULL,file_name TEXT NOT NULL,content_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,sha256 TEXT NOT NULL,storage_status TEXT NOT NULL,scan_status TEXT NOT NULL,scan_provider TEXT,scan_reference TEXT,scanned_by TEXT,scanned_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_versions(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,document_id TEXT NOT NULL,version_number INTEGER NOT NULL,blob_id TEXT NOT NULL,change_reason TEXT NOT NULL,is_original INTEGER NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_derivatives(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,document_id TEXT NOT NULL,version_id TEXT NOT NULL,derivative_type TEXT NOT NULL,object_key TEXT,content_text TEXT,model_or_tool TEXT,status TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_ai_decisions(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,document_id TEXT NOT NULL,decision_type TEXT NOT NULL,model_or_rule_version TEXT NOT NULL,structured_output_json TEXT NOT NULL,confidence REAL NOT NULL,evidence_json TEXT NOT NULL,risk_class TEXT NOT NULL,approval_status TEXT NOT NULL,reviewer TEXT,reviewed_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_retention_policies(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT,policy_code TEXT NOT NULL,name TEXT NOT NULL,document_type TEXT NOT NULL,jurisdiction TEXT NOT NULL,retain_days INTEGER NOT NULL,trigger_event TEXT NOT NULL,version INTEGER NOT NULL,status TEXT NOT NULL,effective_from TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_legal_holds(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,document_id TEXT NOT NULL,hold_name TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL,placed_by TEXT NOT NULL,placed_at TEXT NOT NULL,released_by TEXT,released_at TEXT,release_reason TEXT);
CREATE TABLE IF NOT EXISTS document_access_events(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,document_id TEXT NOT NULL,action TEXT NOT NULL,actor TEXT NOT NULL,reason TEXT,ip_hash TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_jobs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,property_id TEXT NOT NULL,document_id TEXT NOT NULL,job_type TEXT NOT NULL,status TEXT NOT NULL,provider TEXT,error_code TEXT,error_message TEXT,attempts INTEGER NOT NULL DEFAULT 0,next_attempt_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS document_records_scope_idx ON document_records(organization_id,property_id,status,created_at);
CREATE INDEX IF NOT EXISTS document_records_search_idx ON document_records(organization_id,property_id,document_type,department,updated_at);
CREATE UNIQUE INDEX IF NOT EXISTS document_blob_hash_idx ON document_blobs(organization_id,property_id,sha256);
CREATE INDEX IF NOT EXISTS document_holds_idx ON document_legal_holds(organization_id,property_id,document_id,status);
CREATE INDEX IF NOT EXISTS document_access_idx ON document_access_events(organization_id,property_id,document_id,created_at);
