import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../../chatgpt-auth";
import { importReservations, otaCenter, resolveOtaException, runOtaReconciliation } from "../../../../db/ota-reconciliation";
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in required."},{status:401});const data=await otaCenter(user.email);return data?Response.json(data,{headers:{"cache-control":"private, no-store"}}):Response.json({error:"Access denied."},{status:403})}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in required."},{status:401});try{
  const type=request.headers.get("content-type")??"";if(type.includes("multipart/form-data")){if(!env.MEDIA)return Response.json({error:"Reservation file storage unavailable."},{status:503});const f=await request.formData(),file=f.get("file");if(!(file instanceof File))return Response.json({error:"Choose a reservation file."},{status:400});if(file.size>15*1024*1024)return Response.json({error:"File must be 15MB or smaller."},{status:413});const text=await file.text(),key=`ota-reconciliation/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await env.MEDIA.put(key,text,{httpMetadata:{contentType:file.type||"text/csv"}});const result=await importReservations(user.email,String(f.get("source")),file.name,text);return result?Response.json(result,{status:202}):Response.json({error:"Administrator access required."},{status:403})}
  const b=await request.json() as any,result=await runOtaReconciliation(user.email,String(b.periodStart),String(b.periodEnd));return result?Response.json(result):Response.json({error:"Administrator access required."},{status:403});
}catch(error){return Response.json({error:error instanceof Error?error.message:"Reconciliation failed."},{status:409})}}
export async function PATCH(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in required."},{status:401});const b=await request.json() as any,result=await resolveOtaException(user.email,String(b.id),String(b.note||"Verified and resolved."));return result?Response.json(result):Response.json({error:"Administrator access required."},{status:403})}
