"use client";import{useEffect,useState}from"react";type Row=Record<string,any>;
export default function OtaClient(){const[data,setData]=useState<any>(null),[notice,setNotice]=useState(""),[source,setSource]=useState("PMS"),[start,setStart]=useState(new Date().toISOString().slice(0,8)+"01"),[end,setEnd]=useState(new Date().toISOString().slice(0,10));
async function load(){const r=await fetch("/api/v1/ota-reconciliation",{cache:"no-store"});setData(await r.json())}useEffect(()=>{void load()},[]);
async function upload(file?:File){if(!file)return;setNotice(`Importing ${source} reservations…`);const f=new FormData();f.set("source",source);f.set("file",file);const r=await fetch("/api/v1/ota-reconciliation",{method:"POST",body:f}),x=await r.json()as any;setNotice(x.error??`${x.imported} ${x.source} records imported; ${x.exceptions.length} row exceptions.`);if(r.ok)await load()}
async function run(){setNotice("Reconciling channel records against PMS…");const r=await fetch("/api/v1/ota-reconciliation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({periodStart:start,periodEnd:end})}),x=await r.json()as any;setNotice(x.error??`${x.matched}/${x.otaCount} OTA records matched; ${x.exceptions} exceptions opened.`);if(r.ok)await load()}
async function resolve(id:string){const r=await fetch("/api/v1/ota-reconciliation",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,note:"Manager verified source records and resolved the exception."})});if(r.ok){setNotice("Exception resolved with audit history.");await load()}}
if(!data)return <main className="ota-shell">Loading OTA reconciliation…</main>;const latest=data.runs[0],money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v||0);
return <main className="ota-shell"><header><a href="/">← AAIQ Home</a><div><p>Distribution control</p><h1>AAIQ OTA Reconciliation</h1><span>Compare PMS, Wyndham, Booking.com, Expedia and other channels without losing a reservation.</span></div><b>{data.exceptions.filter((x:Row)=>x.status==="OPEN").length} OPEN EXCEPTIONS</b></header>{notice&&<div className="ota-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
<section className="ota-import"><div><small>CONNECTOR OR IMPORT</small><h2>Automatic OTA pull with secure fallback</h2><p>Save provider credentials in the encrypted Growth OS vault for certified API synchronization, or upload CSV/text now. Re-imports update the same source reservation.</p><a href="/aaiq-website-factory">Open secure provider vault →</a></div><label>Source<select value={source} onChange={e=>setSource(e.target.value)}><option>PMS</option><option>WYNDHAM</option><option>BOOKING_COM</option><option>EXPEDIA</option><option>OTHER_OTA</option></select></label><label className="ota-upload">Choose report<input type="file" accept=".csv,.txt,text/csv,text/plain" onChange={e=>void upload(e.target.files?.[0])}/></label></section>
<section className="ota-sources">{["PMS","WYNDHAM","BOOKING_COM","EXPEDIA","OTHER_OTA"].map(name=>{const row=data.records.find((r:Row)=>r.source===name);return <article key={name}><b>{name.replace("_"," ")}</b><strong>{row?.count??0}</strong><span>reservations</span><small>{row?.last_import?`Updated ${new Date(row.last_import).toLocaleString()}`:"Not imported"}</small></article>})}</section>
<section className="ota-run"><div><small>RECONCILIATION PERIOD</small><h2>Run reservation-to-PMS audit</h2><div><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><span>through</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><button onClick={()=>void run()}>Reconcile now →</button></section>
{latest&&<section className="ota-metrics"><article><span>PMS reservations</span><strong>{latest.pms_count}</strong></article><article><span>OTA reservations</span><strong>{latest.ota_count}</strong></article><article><span>Matched</span><strong>{latest.matched_count}</strong></article><article><span>Exceptions</span><strong>{latest.exception_count}</strong></article><article><span>Gross OTA value</span><strong>{money(latest.gross_amount)}</strong></article><article><span>Net after commission</span><strong>{money(latest.net_amount)}</strong></article></section>}
<section className="ota-exceptions"><header><div><small>EXCEPTION WORKBENCH</small><h2>Resolve, document and replay</h2></div><span>{data.roomTypes.length} canonical room types available for mapping</span></header>{data.exceptions.length?data.exceptions.map((x:Row)=><article key={x.id} className={x.severity.toLowerCase()}><b>{x.severity}</b><div><strong>{x.exception_type.replaceAll("_"," ")}</strong><p>{x.summary}</p><small>{x.source} · {x.confirmation_number||x.external_id} · {x.status}</small></div>{x.status==="OPEN"&&data.role==="admin"&&<button onClick={()=>void resolve(x.id)}>Mark resolved</button>}</article>):<div className="ota-empty">No reconciliation exceptions yet.</div>}</section></main>}
