"use client";
import { FormEvent, useEffect, useState } from "react";
import "./security-boundary.css";
export default function SecurityBoundaryClient(){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[message,setMessage]=useState(""),[currentIp,setCurrentIp]=useState("");
 async function load(){const response=await fetch("/api/v1/access-boundary",{cache:"no-store"});if(response.ok){const body=await response.json();setData(body);if(!selected&&body.properties[0])setSelected(body.properties[0])}}
 useEffect(()=>{void load()},[]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),body=Object.fromEntries(form);const response=await fetch("/api/v1/access-boundary",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"SAVE_POLICY",propertyId:selected.id,enabled:form.get("enabled")==="on",requireGeofence:form.get("requireGeofence")==="on",requireTrustedIp:form.get("requireTrustedIp")==="on",latitude:form.get("latitude"),longitude:form.get("longitude"),radiusMeters:form.get("radiusMeters"),trustedCidrs:form.get("trustedCidrs")})});const result=await response.json();setMessage(response.ok?"Access policy saved and audited.":result.error||"Policy could not be saved.");if(response.ok)void load()}
 return <main className="security-boundary"><header><div><small>AAIQ ADMINISTRATION</small><h1>Location & Network Security</h1><p>Keep the public site reachable while enforcing trusted-property access for operational apps. Administrator bypass is always audited.</p></div><span>ADMIN ONLY</span></header>
 <section className="security-layout"><aside><h2>Properties</h2>{data?.properties?.map((property:any)=><button className={selected?.id===property.id?"active":""} key={property.id} onClick={()=>setSelected(property)}><strong>{property.name}</strong><small>{property.code} · {property.enabled?"ENFORCED":"NOT CONFIGURED"}</small></button>)}</aside>
 {selected&&<form key={selected.id} onSubmit={save}><div className="policy-title"><span><small>PROPERTY ACCESS POLICY</small><h2>{selected.name}</h2></span><label><input name="enabled" type="checkbox" defaultChecked={Boolean(selected.enabled)}/> Enforce policy</label></div>
  <div className="security-fields"><label>Latitude<input name="latitude" type="number" step="any" required defaultValue={selected.latitude??""}/></label><label>Longitude<input name="longitude" type="number" step="any" required defaultValue={selected.longitude??""}/></label><label>Radius in meters<input name="radiusMeters" type="number" min="50" max="10000" defaultValue={selected.radius_meters??750}/></label></div>
  <div className="security-switches"><label><input name="requireGeofence" type="checkbox" defaultChecked={selected.require_geofence!==0}/> Require device geofence</label><label><input name="requireTrustedIp" type="checkbox" defaultChecked={selected.require_trusted_ip!==0}/> Require trusted IP network</label></div>
  <label>Trusted IPv4 addresses or CIDRs<textarea name="trustedCidrs" placeholder={"Example:\n203.0.113.42/32\n192.0.2.0/24"} defaultValue={(()=>{try{return JSON.parse(selected.trusted_ipv4_cidrs_json||"[]").join("\n")}catch{return""}})()}/><small>Use /32 for one public IP. Staff must satisfy every enabled requirement.</small></label>
  <button className="save-policy">Save & enforce policy</button>{message&&<p className="policy-message">{message}</p>}
 </form>}</section>
 <section className="access-events"><header><div><small>Backup, outage, and privileged-change drill</small><h2>Continuity evidence</h2><p>Creates isolated UAT rows, snapshots them, deletes a subset, restores and verifies checksums, interrupts a simulated connector, and fires a privileged configuration alert. Production records and external providers are not touched.</p></div>{selected&&<button onClick={async()=>{const response=await fetch("/api/v1/access-boundary",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"RUN_CONTINUITY_DRILL",propertyId:selected.id})});const result=await response.json();setMessage(response.ok?`Continuity drill ${result.status}: ${result.restoredRecords}/${result.backupRecords} records restored.`:result.error||"Drill failed.");if(response.ok)void load()}}>Run continuity drill</button>}</header><div className="event-scroll"><table><thead><tr><th>Time</th><th>Status</th><th>Backup / restore</th><th>Integrity</th><th>RPO</th><th>RTO</th></tr></thead><tbody>{data?.drills?.map((run:any)=><tr key={run.id}><td>{new Date(run.executed_at).toLocaleString()}</td><td>{run.status}</td><td>{run.backup_record_count} / {run.restored_record_count}</td><td>{run.integrity_verified?"VERIFIED":"FAILED"}</td><td>{Number(run.rpo_actual_seconds).toFixed(3)}s</td><td>{Number(run.rto_actual_seconds).toFixed(3)}s</td></tr>)}</tbody></table></div></section>
 <section className="access-events"><header><div><small>IMMUTABLE DECISION HISTORY</small><h2>Recent access decisions</h2></div><span>{data?.events?.length??0} events</span></header><div className="event-scroll"><table><thead><tr><th>Time</th><th>User</th><th>Property</th><th>Decision</th><th>Network</th><th>Reason</th></tr></thead><tbody>{data?.events?.map((event:any)=><tr key={event.id}><td>{new Date(event.created_at).toLocaleString()}</td><td>{event.user_email}</td><td>{event.property_id||"—"}</td><td><b className={event.decision==="ALLOW"?"allow":"deny"}>{event.decision}</b></td><td>{event.ip_address||"Unavailable"}</td><td>{event.reason}</td></tr>)}</tbody></table></div></section>
 </main>
}
